# Generated by Django 5.0.3 on 2025-10-08 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du job')),
                ('source_type', models.CharField(choices=[('excel', 'Excel/CSV'), ('quickbooks', 'QuickBooks Online')], max_length=20, verbose_name='Source')),
                ('entity_type', models.CharField(choices=[('suppliers', 'Fournisseurs'), ('products', 'Produits'), ('clients', 'Clients'), ('purchase_orders', 'Bons de commande'), ('invoices', 'Factures')], max_length=30, verbose_name="Type d'entité")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('mapping', 'Configuration du mapping'), ('validating', 'Validation'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='migrations/%Y/%m/', verbose_name='Fichier source')),
                ('file_encoding', models.CharField(default='utf-8', max_length=20, verbose_name='Encodage du fichier')),
                ('delimiter', models.CharField(default=',', max_length=5, verbose_name='Délimiteur CSV')),
                ('has_header', models.BooleanField(default=True, verbose_name='Première ligne contient les en-têtes')),
                ('quickbooks_realm_id', models.CharField(blank=True, max_length=100, verbose_name='QuickBooks Realm ID')),
                ('quickbooks_access_token', models.TextField(blank=True, verbose_name='QuickBooks Access Token')),
                ('quickbooks_refresh_token', models.TextField(blank=True, verbose_name='QuickBooks Refresh Token')),
                ('quickbooks_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expire le')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='Mapping des champs')),
                ('default_values', models.JSONField(blank=True, default=dict, verbose_name='Valeurs par défaut')),
                ('transformation_rules', models.JSONField(blank=True, default=dict, verbose_name='Règles de transformation')),
                ('import_suppliers', models.BooleanField(default=True, verbose_name='Importer les fournisseurs')),
                ('import_products', models.BooleanField(default=True, verbose_name='Importer les produits')),
                ('import_clients', models.BooleanField(default=True, verbose_name='Importer les clients')),
                ('import_purchase_orders', models.BooleanField(default=False, verbose_name='Importer les bons de commande')),
                ('import_invoices', models.BooleanField(default=False, verbose_name='Importer les factures')),
                ('skip_duplicates', models.BooleanField(default=True, verbose_name='Ignorer les doublons')),
                ('update_existing', models.BooleanField(default=False, verbose_name='Mettre à jour les existants')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total de lignes')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes traitées')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Succès')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Erreurs')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Ignorées')),
                ('preview_data', models.JSONField(blank=True, default=list, verbose_name='Aperçu des données')),
                ('error_summary', models.JSONField(blank=True, default=list, verbose_name='Résumé des erreurs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Job de migration',
                'verbose_name_plural': 'Jobs de migration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('success', 'Succès')], max_length=10, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de ligne')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='Données source')),
                ('transformed_data', models.JSONField(blank=True, default=dict, verbose_name='Données transformées')),
                ('created_object_id', models.CharField(blank=True, max_length=100, verbose_name="ID de l'objet créé")),
                ('created_object_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'objet créé")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_migration.migrationjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Log de migration',
                'verbose_name_plural': 'Logs de migration',
                'ordering': ['job', 'row_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realm_id', models.CharField(max_length=100, verbose_name='Realm ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(verbose_name='Token expire le')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Connecté le')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sync')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_connection', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion QuickBooks',
                'verbose_name_plural': 'Connexions QuickBooks',
            },
        ),
    ]
