# Generated by Django 5.0.3 on 2025-10-08 07:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_suppliercategory_supplier_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contrat')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('contract_type', models.CharField(choices=[('purchase', "Contrat d'achat"), ('service', 'Contrat de service'), ('maintenance', 'Contrat de maintenance'), ('lease', 'Contrat de location'), ('nda', 'Accord de confidentialité'), ('partnership', 'Accord de partenariat'), ('other', 'Autre')], max_length=20, verbose_name='Type de contrat')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En révision'), ('pending_approval', "En attente d'approbation"), ('approved', 'Approuvé'), ('active', 'Actif'), ('expiring_soon', 'Expire bientôt'), ('expired', 'Expiré'), ('terminated', 'Résilié'), ('renewed', 'Renouvelé')], default='draft', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name='Description')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Termes et conditions')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='Conditions de paiement')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résiliation')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur totale')),
                ('currency', models.CharField(default='CAD', max_length=3, verbose_name='Devise')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, verbose_name='Jours de préavis pour renouvellement')),
                ('renewal_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de renouvellements')),
                ('alert_days_before_expiry', models.PositiveIntegerField(default=30, verbose_name='Alerte (jours avant expiration)')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True, verbose_name='Dernière alerte envoyée')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('internal_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Contact interne')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('payment', 'Paiement'), ('delivery', 'Livraison'), ('warranty', 'Garantie'), ('liability', 'Responsabilité'), ('termination', 'Résiliation'), ('confidentiality', 'Confidentialité'), ('intellectual_property', 'Propriété intellectuelle'), ('dispute_resolution', 'Résolution des litiges'), ('force_majeure', 'Force majeure'), ('renewal', 'Renouvellement'), ('penalty', 'Pénalité'), ('sla', 'SLA / Niveau de service'), ('other', 'Autre')], max_length=30, verbose_name='Type de clause')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('section_reference', models.CharField(blank=True, max_length=50, verbose_name='Référence de section')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20, null=True, verbose_name='Niveau de risque')),
                ('ai_confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de confiance IA')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Analyse IA')),
                ('ai_recommendations', models.TextField(blank=True, verbose_name='Recommandations IA')),
                ('extracted_by_ai', models.BooleanField(default=False, verbose_name='Extrait par IA')),
                ('verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract', verbose_name='Contrat')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clauses', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Clause de contrat',
                'verbose_name_plural': 'Clauses de contrat',
                'ordering': ['contract', 'clause_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('contract', 'Contrat principal'), ('amendment', 'Amendement'), ('annex', 'Annexe'), ('invoice', 'Facture'), ('correspondence', 'Correspondance'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='contracts/documents/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Contrat')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_docs', to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Document de contrat',
                'verbose_name_plural': 'Documents de contrat',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('delayed', 'Retardé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du paiement')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Complété par')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Jalon de contrat',
                'verbose_name_plural': 'Jalons de contrat',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
