# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='contractclause',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='contractclause',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clauses', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_docs', to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='invoicing.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Complété par'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='Contrat'),
        ),
        migrations.AlterUniqueTogether(
            name='contractitem',
            unique_together={('contract', 'product')},
        ),
    ]
