# Generated by Django 5.0.3 on 2025-10-12 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('invoicing', '0010_add_product_category_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contracted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix contractuel')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité minimum')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité maximum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract', verbose_name='Contrat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='invoicing.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de contrat',
                'verbose_name_plural': 'Articles de contrat',
                'ordering': ['contract', 'product'],
                'unique_together': {('contract', 'product')},
            },
        ),
    ]
