# Generated by Django 5.2.10 on 2026-03-20 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('template_type', models.CharField(choices=[('contract', 'Contrat standard'), ('payment', 'Contrat de paiement'), ('receipt', 'Reçu de paiement'), ('quote', 'Devis'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu du modèle (HTML/Texte)')),
                ('ai_prompt_instructions', models.TextField(blank=True, verbose_name="Instructions pour l'IA")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de contrat',
                'verbose_name_plural': 'Modèles de contrats',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
