# Generated by Django 5.2.10 on 2026-03-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('contracts', '0003_contracttemplate'),
        ('suppliers', '0006_add_activity_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='accounts.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_body',
            field=models.TextField(blank=True, verbose_name='Corps du contrat'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterpart_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la contrepartie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_counterpart',
            field=models.BooleanField(default=False, verbose_name='Signé par la contrepartie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_counterpart_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date signature (contrepartie)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_counterpart_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signataire (contrepartie)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_us',
            field=models.BooleanField(default=False, verbose_name='Signé par nous'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_us_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date signature (nous)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_us_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signataire (notre côté)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/%Y/%m/', verbose_name='PDF signé'),
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='contracts.contracttemplate', verbose_name='Modèle source'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contrat principal'), ('signed_contract', 'Contrat signé (PDF)'), ('amendment', 'Amendement'), ('annex', 'Annexe'), ('invoice', 'Facture'), ('correspondence', 'Correspondance'), ('other', 'Autre')], max_length=20, verbose_name='Type de document'),
        ),
    ]
