# Generated by Django 5.2.10 on 2026-03-21 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('contracts', '0005_make_dates_value_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
