# Generated by Django 5.2.10 on 2026-03-22 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_add_organization_to_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('parties', 'Parties contractantes'), ('object', 'Objet du contrat'), ('duration', 'Durée du contrat'), ('obligations_provider', 'Obligations du prestataire'), ('obligations_client', 'Obligations du client'), ('financial', 'Conditions financières'), ('payment_schedule', 'Échéancier de paiement'), ('payment_terms', 'Modalités de paiement'), ('delivery', 'Délais et livraison'), ('acceptance', 'Livraison et acceptation'), ('intellectual_property', 'Propriété intellectuelle'), ('warranty', 'Garantie'), ('liability', 'Limitation de responsabilité'), ('confidentiality', 'Confidentialité'), ('data_protection', 'Protection des données'), ('subcontracting', 'Sous-traitance'), ('termination', 'Résiliation'), ('force_majeure', 'Force majeure'), ('applicable_law', 'Droit applicable et litiges'), ('general_provisions', 'Dispositions générales'), ('annexes', 'Annexes'), ('signatures', 'Signatures'), ('receipt_info', 'Informations du reçu'), ('receipt_detail', 'Détail financier du reçu'), ('receipt_confirmation', 'Confirmation et signature'), ('custom', 'Section personnalisée')], max_length=30, verbose_name='Type de section')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la section')),
                ('content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Généré par IA')),
                ('ai_tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens IA utilisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='contracts.contract', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Section de contrat',
                'verbose_name_plural': 'Sections de contrat',
                'ordering': ['contract', 'order'],
                'unique_together': {('contract', 'section_type')},
            },
        ),
    ]
