# Generated by Django 5.2.10 on 2026-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_add_contract_section_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=5, verbose_name='Langue du contrat'),
        ),
    ]
