# Generated by Django 5.2.10 on 2026-04-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signed_by_counterpart_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature (contrepartie)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by_counterpart_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du signataire (contrepartie)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by_us_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature (nous)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_by_us_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du signataire (nous)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='PDF signé'),
        ),
    ]
