# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('subscription_type', models.CharField(choices=[('free', 'Gratuit'), ('billing', 'Facturation'), ('procurement', 'Achats'), ('professional', 'Professionnel'), ('strategic', 'Stratégique'), ('enterprise', 'Entreprise')], default='free', max_length=50, verbose_name="Type d'abonnement")),
                ('enabled_modules', models.JSONField(default=list, help_text="Liste des modules disponibles pour l'organisation", verbose_name='Modules activés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Serveur SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_username', models.CharField(max_length=255, verbose_name="Nom d'utilisateur SMTP")),
                ('smtp_password_encrypted', models.TextField(verbose_name='Mot de passe SMTP (chiffré)')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='Email expéditeur par défaut')),
                ('default_from_name', models.CharField(max_length=100, verbose_name='Nom expéditeur par défaut')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configurations email',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom complet du client (obligatoire)', max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne contact')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Numéro de taxe')),
                ('payment_terms', models.CharField(blank=True, default='CASH', max_length=100, verbose_name='Conditions de paiement')),
                ('client_type', models.CharField(choices=[('b2b', 'Entreprise (B2B)'), ('patient', 'Patient'), ('both', 'Les deux')], default='b2b', max_length=20, verbose_name='Type de client')),
                ('patient_number', models.CharField(blank=True, help_text='Généré automatiquement pour les patients', max_length=50, null=True, unique=True, verbose_name='Numéro patient')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, help_text='Liste des allergies connues', verbose_name='Allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Maladies chroniques ou conditions permanentes', verbose_name='Conditions chroniques')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence - Nom")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence - Téléphone")),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp pour notifications', max_length=20, verbose_name='WhatsApp')),
                ('registration_source', models.CharField(blank=True, choices=[('internal', 'Interne'), ('external', 'Externe (autre hôpital)'), ('emergency', 'Urgence')], max_length=20, verbose_name="Source d'inscription")),
                ('referring_hospital', models.CharField(blank=True, help_text='Pour les patients externes', max_length=200, verbose_name='Hôpital référent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('auto_inactive_since', models.DateTimeField(blank=True, null=True, verbose_name='Inactif automatiquement depuis')),
                ('is_manually_active', models.BooleanField(default=False, help_text='Si True, le statut actif/inactif est géré manuellement et ne sera pas modifié automatiquement', verbose_name='Statut manuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise (déprécié)')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('buyer', 'Acheteur'), ('accountant', 'Comptable'), ('viewer', 'Consultation'), ('doctor', 'Médecin'), ('nurse', 'Infirmier/Infirmière'), ('lab_tech', 'Technicien de laboratoire'), ('pharmacist', 'Pharmacien'), ('receptionist', 'Réceptionniste')], default='buyer', max_length=50, verbose_name='Rôle')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Peut créer, modifier et supprimer des utilisateurs', verbose_name='Gérer les utilisateurs')),
                ('can_manage_settings', models.BooleanField(default=False, help_text="Peut modifier les paramètres de l'organisation", verbose_name='Gérer les paramètres')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='Peut accéder aux rapports et analytics', verbose_name='Voir les analytics')),
                ('can_approve_purchases', models.BooleanField(default=False, help_text='Peut approuver les bons de commande', verbose_name='Approuver les achats')),
                ('module_access', models.JSONField(default=list, help_text="Liste des modules accessibles (sous-ensemble des modules de l'organisation)", verbose_name='Accès aux modules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateur',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_modules', models.JSONField(default=list, help_text="Liste des modules auxquels l'utilisateur a accès", verbose_name="Modules activés pour l'utilisateur")),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding complété')),
                ('onboarding_data', models.JSONField(default=dict, help_text="Réponses du questionnaire d'onboarding", verbose_name="Données d'onboarding")),
                ('dashboard_layout', models.JSONField(default=dict, verbose_name='Mise en page du tableau de bord')),
                ('notification_settings', models.JSONField(default=dict, verbose_name='Paramètres de notification')),
                ('preferred_currency', models.CharField(default='EUR', help_text='Code ISO de la devise préférée (EUR, USD, XOF, etc.)', max_length=3, verbose_name='Devise préférée')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
    ]
