# Generated by Django 5.2.10 on 2026-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='antecedents_family',
            field=models.TextField(blank=True, verbose_name='Antécédents familiaux'),
        ),
        migrations.AddField(
            model_name='client',
            name='antecedents_gyneco_obs',
            field=models.TextField(blank=True, verbose_name='Antécédents gynéco-obstétrique'),
        ),
        migrations.AddField(
            model_name='client',
            name='antecedents_immuno_allergies',
            field=models.TextField(blank=True, verbose_name='Antécédents immuno-allergies'),
        ),
        migrations.AddField(
            model_name='client',
            name='antecedents_lifestyle',
            field=models.TextField(blank=True, verbose_name='Mode de vie (Toxicologie/alcool)'),
        ),
        migrations.AddField(
            model_name='client',
            name='antecedents_medical',
            field=models.TextField(blank=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='client',
            name='antecedents_surgical',
            field=models.TextField(blank=True, verbose_name='Antécédents chirurgicaux'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profession'),
        ),
    ]
