# Generated by Django 5.2.10 on 2026-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('buyer', 'Acheteur'), ('accountant', 'Comptable'), ('viewer', 'Consultation'), ('doctor', 'Médecin'), ('nurse', 'Infirmier/Infirmière'), ('lab_tech', 'Technicien de laboratoire'), ('biologist', 'Biologiste'), ('pharmacist', 'Pharmacien'), ('receptionist', 'Réceptionniste')], default='buyer', max_length=50, verbose_name='Rôle'),
        ),
    ]
