# Generated by Django 4.2.11 on 2026-08-17 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_invoice_global_discount_is_surcharge'),
        ('accounts', '0003_add_lab_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_privilege_card',
            field=models.BooleanField(default=False, help_text='Donne droit à une réduction automatique (taux configurable par module) sur les factures', verbose_name='Carte Privilège'),
        ),
        migrations.AddField(
            model_name='client',
            name='privilege_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de carte privilège'),
        ),
        migrations.CreateModel(
            name='PrivilegeCardUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_by_name', models.CharField(blank=True, help_text="Si le proche n'est pas enregistré comme patient", max_length=200, verbose_name='Utilisée par (nom libre)')),
                ('used_by_relationship', models.CharField(blank=True, help_text='Ex: Épouse, Enfant — laisser vide si utilisée par le titulaire lui-même', max_length=100, verbose_name='Lien de parenté')),
                ('module', models.CharField(blank=True, max_length=30, verbose_name='Module')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant économisé')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_card_usages', to='accounts.client', verbose_name='Titulaire de la carte')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privilege_card_usages', to='invoicing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_card_usages', to='accounts.organization', verbose_name='Organisation')),
                ('used_by_patient', models.ForeignKey(blank=True, help_text='Si un proche enregistré comme patient a utilisé la carte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privilege_card_usages_as_relative', to='accounts.client', verbose_name='Utilisée par (patient enregistré)')),
            ],
            options={
                'verbose_name': 'Utilisation carte privilège',
                'verbose_name_plural': 'Utilisations carte privilège',
                'ordering': ['-used_at'],
            },
        ),
    ]
