# Generated by Django 5.0.3 on 2025-10-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_userpreferences_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise (déprécié)'),
        ),
    ]
