# Generated by Django 5.0.3 on 2025-10-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_subscription_types'),
        ('accounts', '0004_alter_customuser_company'),
    ]

    operations = [
    ]
