# Generated by Django 5.0.3 on 2025-10-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251012_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=100, verbose_name='Conditions de paiement'),
        ),
    ]
