# Generated by Django 4.2.11 on 2026-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_privilegecardusage_item_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Ce que l\'utilisateur peut FAIRE dans chaque module, ex: {"laboratory": ["view", "validate"]}. Vide = tous les droits sur les modules auxquels il a accès.', verbose_name='Permissions par module'),
        ),
    ]
