# Generated by Django 5.0.3 on 2025-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_organization_client_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Nom complet du client (obligatoire)', max_length=200, verbose_name='Nom'),
        ),
    ]
