# Generated by Django 5.0.3 on 2025-11-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_email_verified_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_currency',
            field=models.CharField(default='EUR', help_text='Code ISO de la devise préférée (EUR, USD, XOF, etc.)', max_length=3, verbose_name='Devise préférée'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée'),
        ),
    ]
