# Generated by Django 4.2.11 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_activity_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='smtp_username',
            field=models.CharField(max_length=255, verbose_name="Nom d'utilisateur SMTP"),
        ),
    ]
