# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allergies',
            field=models.TextField(blank=True, help_text='Liste des allergies connues', verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='client',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='client',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Maladies chroniques ou conditions permanentes', verbose_name='Conditions chroniques'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('b2b', 'Entreprise (B2B)'), ('patient', 'Patient'), ('both', 'Les deux')], default='b2b', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence - Nom"),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='client',
            name='patient_number',
            field=models.CharField(blank=True, help_text='Généré automatiquement pour les patients', max_length=50, null=True, unique=True, verbose_name='Numéro patient'),
        ),
        migrations.AddField(
            model_name='client',
            name='referring_hospital',
            field=models.CharField(blank=True, help_text='Pour les patients externes', max_length=200, verbose_name='Hôpital référent'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_source',
            field=models.CharField(blank=True, choices=[('internal', 'Interne'), ('external', 'Externe (autre hôpital)'), ('emergency', 'Urgence')], max_length=20, verbose_name="Source d'inscription"),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp pour notifications', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('buyer', 'Acheteur'), ('accountant', 'Comptable'), ('viewer', 'Consultation'), ('doctor', 'Médecin'), ('nurse', 'Infirmier/Infirmière'), ('lab_tech', 'Technicien de laboratoire'), ('pharmacist', 'Pharmacien'), ('receptionist', 'Réceptionniste')], default='buyer', max_length=50, verbose_name='Rôle'),
        ),
    ]
