# Generated by Django 4.2.11 on 2026-09-04 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maternity', '0002_postnatalvisit_consultation_and_more'),
        ('accounts', '0004_client_has_privilege_card_and_more'),
        ('invoicing', '0018_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_categories', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Catégorie de vaccin',
                'verbose_name_plural': 'Catégories de vaccin',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_population', models.CharField(choices=[('child', 'Enfant (PEV)'), ('pregnant_woman', 'Femme enceinte'), ('adult', 'Adulte'), ('traveler', 'Voyageur'), ('other', 'Autre')], default='child', max_length=20, verbose_name='Population cible')),
                ('is_billable', models.BooleanField(default=False, verbose_name='Facturable')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Utilisé seulement si le vaccin est facturable', max_digits=10, verbose_name='Prix')),
                ('standard_doses_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de doses du schéma')),
                ('dose_interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalle entre doses (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_types', to='vaccination.vaccinecategory', verbose_name='Catégorie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_types', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Type de vaccin',
                'verbose_name_plural': 'Types de vaccin',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dose_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de dose')),
                ('administered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'administration")),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('next_dose_due_date', models.DateField(blank=True, null=True, verbose_name='Prochaine dose due')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL, verbose_name='Administré par')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='invoicing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='accounts.client', verbose_name='Patient')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='maternity.pregnancyrecord', verbose_name='Grossesse liée (si vaccination anténatale)')),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='vaccination.vaccinetype', verbose_name='Vaccin')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-administered_date'],
                'indexes': [models.Index(fields=['organization', '-administered_date'], name='vaccination_organiz_4ac24b_idx'), models.Index(fields=['patient'], name='vaccination_patient_3c14ab_idx')],
            },
        ),
    ]
