# Generated by Django 4.2.11 on 2026-09-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_client_has_privilege_card_and_more'),
        ('invoicing', '0017_alter_invoice_invoice_type'),
        ('hospitalizations', '0002_add_bed_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date/heure d'accouchement")),
                ('delivery_type', models.CharField(choices=[('vaginal', 'Voie basse'), ('cesarean', 'Césarienne'), ('instrumental', 'Voie basse instrumentale')], default='vaginal', max_length=20, verbose_name="Type d'accouchement")),
                ('labor_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Durée du travail (heures)')),
                ('complications', models.TextField(blank=True, verbose_name='Complications')),
                ('attending_staff', models.TextField(blank=True, help_text="Médecin(s), sage-femme(s) ayant assisté l'accouchement", verbose_name='Personnel présent')),
                ('mother_condition_after', models.TextField(blank=True, verbose_name='État de la mère après accouchement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='invoicing.invoice', verbose_name='Facture accouchement')),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='hospitalizations.hospitalization', verbose_name="Séjour d'hospitalisation lié")),
            ],
            options={
                'verbose_name': 'Accouchement',
                'verbose_name_plural': 'Accouchements',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('birth_weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids de naissance (g)')),
                ('birth_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Taille (cm)')),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Périmètre crânien (cm)')),
                ('apgar_score_1min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apgar 1 min')),
                ('apgar_score_5min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apgar 5 min')),
                ('apgar_score_10min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apgar 10 min')),
                ('condition_at_birth', models.TextField(blank=True, verbose_name='État à la naissance')),
                ('feeding_type', models.CharField(blank=True, choices=[('breast', 'Allaitement maternel'), ('formula', 'Allaitement artificiel'), ('mixed', 'Mixte')], max_length=20, verbose_name='Alimentation')),
                ('birth_vaccinations', models.CharField(blank=True, help_text='Ex: BCG, Polio 0', max_length=300, verbose_name='Vaccinations à la naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newborns', to='maternity.delivery', verbose_name='Accouchement')),
                ('patient_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newborn_record', to='accounts.client', verbose_name='Fiche patient liée')),
            ],
            options={
                'verbose_name': 'Nouveau-né',
                'verbose_name_plural': 'Nouveau-nés',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lmp_date', models.DateField(blank=True, null=True, verbose_name='Date des dernières règles (DDR)')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name="Date prévue d'accouchement (DPA)")),
                ('gravidity', models.PositiveIntegerField(blank=True, help_text='Nombre total de grossesses', null=True, verbose_name='Gravidité')),
                ('parity', models.PositiveIntegerField(blank=True, help_text="Nombre d'accouchements précédents", null=True, verbose_name='Parité')),
                ('risk_factors', models.TextField(blank=True, help_text='Ex: HTA, diabète gestationnel, grossesse multiple...', verbose_name='Facteurs de risque')),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('delivered', 'Accouchée'), ('terminated', 'Interrompue')], default='ongoing', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_records', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_records', to='accounts.client', verbose_name='Patiente')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_pregnancies', to=settings.AUTH_USER_MODEL, verbose_name='Médecin référent')),
            ],
            options={
                'verbose_name': 'Dossier de grossesse',
                'verbose_name_plural': 'Dossiers de grossesse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la visite')),
                ('gestational_age_weeks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge gestationnel (SA)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tension systolique')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tension diastolique')),
                ('fundal_height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hauteur utérine (cm)')),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bruits du cœur fœtal (bpm)')),
                ('edema', models.BooleanField(default=False, verbose_name='Œdèmes')),
                ('fetal_movements', models.BooleanField(default=True, verbose_name='Mouvements fœtaux actifs')),
                ('urine_test_results', models.CharField(blank=True, max_length=200, verbose_name='Bandelette urinaire (albumine/glucose)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Prochaine visite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenatal_visits_done', to=settings.AUTH_USER_MODEL, verbose_name='Médecin / Sage-femme')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_visits', to='maternity.pregnancyrecord', verbose_name='Grossesse')),
                ('visit_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenatal_visit', to='invoicing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Consultation prénatale',
                'verbose_name_plural': 'Consultations prénatales',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PostnatalVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la visite')),
                ('days_after_delivery', models.PositiveIntegerField(blank=True, null=True, verbose_name="Jours après l'accouchement")),
                ('mother_condition', models.TextField(blank=True, verbose_name='État de la mère')),
                ('mother_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids mère (kg)')),
                ('mother_blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tension systolique mère')),
                ('mother_blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tension diastolique mère')),
                ('newborn_weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids bébé (g)')),
                ('feeding_status', models.CharField(blank=True, choices=[('breast', 'Allaitement maternel'), ('formula', 'Allaitement artificiel'), ('mixed', 'Mixte')], max_length=20, verbose_name='Alimentation')),
                ('complications', models.TextField(blank=True, verbose_name='Complications')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Prochaine visite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_visits', to='maternity.delivery', verbose_name='Accouchement')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_visits_done', to=settings.AUTH_USER_MODEL, verbose_name='Médecin / Sage-femme')),
                ('newborn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_visits', to='maternity.newborn', verbose_name='Nouveau-né concerné')),
                ('visit_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_visit', to='invoicing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Suivi post-natal',
                'verbose_name_plural': 'Suivis post-nataux',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='pregnancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='maternity.pregnancyrecord', verbose_name='Grossesse'),
        ),
    ]
