# Generated by Django 4.2.11 on 2026-09-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_prescribed_imaging_exam_types'),
        ('maternity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnatalvisit',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_visit', to='consultations.consultation', verbose_name='Consultation liée'),
        ),
        migrations.AddField(
            model_name='prenatalvisit',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenatal_visit', to='consultations.consultation', verbose_name='Consultation liée'),
        ),
    ]
