# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('invoicing', '0020_warehouse_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sample_collected', 'Échantillon prélevé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('results_ready', 'Résultats prêts'), ('results_delivered', 'Résultats remis'), ('cancelled', 'Annulé')], default='pending', max_length=30, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immédiat)')], default='routine', max_length=20, verbose_name='Priorité')),
                ('clinical_notes', models.TextField(blank=True, help_text='Informations cliniques pertinentes pour le laborantin', verbose_name='Notes cliniques')),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Prélèvement effectué à')),
                ('results_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Résultats terminés à')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notification envoyée à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='invoicing.invoice', verbose_name='Facture labo')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Prescrit par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='accounts.client', verbose_name='Patient')),
                ('results_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lab_results', to=settings.AUTH_USER_MODEL, verbose_name='Résultats saisis par')),
                ('results_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_results', to=settings.AUTH_USER_MODEL, verbose_name='Résultats validés par')),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL, verbose_name='Prélevé par')),
            ],
            options={
                'verbose_name': 'Commande de labo',
                'verbose_name_plural': 'Commandes de labo',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_categories', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Catégorie de test',
                'verbose_name_plural': 'Catégories de tests',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_code', models.CharField(help_text='Ex: HEM-CBC-001', max_length=50, verbose_name='Code test')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du test')),
                ('short_name', models.CharField(blank=True, help_text='Abréviation pour affichage rapide', max_length=50, verbose_name='Nom court')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix du test en devise locale', max_digits=10, verbose_name='Prix')),
                ('normal_range_male', models.CharField(blank=True, help_text='Ex: 4.5-5.5 x10^6/µL', max_length=200, verbose_name='Valeurs normales (Homme)')),
                ('normal_range_female', models.CharField(blank=True, help_text='Ex: 4.0-5.0 x10^6/µL', max_length=200, verbose_name='Valeurs normales (Femme)')),
                ('normal_range_child', models.CharField(blank=True, max_length=200, verbose_name='Valeurs normales (Enfant)')),
                ('normal_range_general', models.CharField(blank=True, help_text='Si pas de distinction par genre/âge', max_length=200, verbose_name='Valeurs normales (Général)')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Ex: g/dL, cells/mcL, mg/dL', max_length=50, verbose_name='Unité de mesure')),
                ('sample_type', models.CharField(choices=[('blood', 'Sang'), ('urine', 'Urine'), ('stool', 'Selles'), ('swab', 'Prélèvement'), ('sputum', 'Expectoration'), ('csf', 'LCR (Liquide céphalo-rachidien)'), ('tissue', 'Tissu'), ('other', 'Autre')], default='blood', max_length=20, verbose_name="Type d'échantillon")),
                ('sample_volume', models.CharField(blank=True, help_text='Ex: 5ml, 10ml', max_length=50, verbose_name='Volume requis')),
                ('container_type', models.CharField(blank=True, choices=[('edta', 'Tube EDTA (violet)'), ('serum', 'Tube sec (rouge)'), ('citrate', 'Tube citrate (bleu)'), ('heparin', 'Tube héparine (vert)'), ('fluoride', 'Tube fluorure (gris)'), ('urine_cup', 'Pot à urine'), ('stool_cup', 'Pot à selles'), ('swab_kit', 'Kit de prélèvement'), ('other', 'Autre')], max_length=20, verbose_name='Type de tube/conteneur')),
                ('fasting_required', models.BooleanField(default=False, verbose_name='À jeun requis')),
                ('fasting_hours', models.IntegerField(blank=True, help_text="Nombre d'heures de jeûne recommandé", null=True, verbose_name='Heures de jeûne')),
                ('preparation_instructions', models.TextField(blank=True, help_text='Instructions spéciales pour le patient', verbose_name='Instructions de préparation')),
                ('estimated_turnaround_hours', models.IntegerField(default=24, help_text='Temps estimé pour les résultats', verbose_name='Délai estimé (heures)')),
                ('methodology', models.CharField(blank=True, help_text='Ex: Spectrophotométrie, ELISA, PCR', max_length=200, verbose_name='Méthodologie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('requires_approval', models.BooleanField(default=False, help_text='Les résultats doivent être validés par un superviseur', verbose_name='Nécessite approbation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labtestcategory', verbose_name='Catégorie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Test de laboratoire',
                'verbose_name_plural': 'Tests de laboratoire',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_value', models.TextField(blank=True, help_text='Résultat du test (texte libre ou numérique)', verbose_name='Valeur du résultat')),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, help_text='Valeur numérique si applicable', max_digits=15, null=True, verbose_name='Valeur numérique')),
                ('result_unit', models.CharField(blank=True, help_text='Unité du résultat (copié du test ou personnalisé)', max_length=50, verbose_name='Unité')),
                ('reference_range', models.CharField(blank=True, help_text='Plage normale pour ce patient', max_length=200, verbose_name='Valeurs de référence')),
                ('abnormality_type', models.CharField(choices=[('normal', 'Normal'), ('low', 'Bas'), ('high', 'Élevé'), ('critical_low', 'Critique bas'), ('critical_high', 'Critique élevé')], default='normal', max_length=20, verbose_name="Type d'anomalie")),
                ('is_abnormal', models.BooleanField(default=False, help_text='Résultat hors des valeurs normales', verbose_name='Anormal')),
                ('is_critical', models.BooleanField(default=False, help_text='Résultat nécessitant une attention immédiate', verbose_name='Critique')),
                ('interpretation', models.TextField(blank=True, help_text='Interprétation du résultat par le technicien', verbose_name='Interprétation')),
                ('technician_notes', models.TextField(blank=True, help_text='Notes internes', verbose_name='Notes du technicien')),
                ('result_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='Résultat saisi à')),
                ('result_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Résultat validé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder', verbose_name='Commande')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest', verbose_name='Test')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_items', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Item de commande labo',
                'verbose_name_plural': 'Items de commande labo',
                'ordering': ['lab_test__name'],
            },
        ),
    ]
