# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='patients.patientvisit', verbose_name='Visite associée'),
        ),
        migrations.AlterUniqueTogether(
            name='labtestcategory',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['organization', 'is_active'], name='laboratory__organiz_8b0669_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test_code'], name='laboratory__test_co_48df4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('organization', 'test_code')},
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['organization', '-order_date'], name='laboratory__organiz_32d831_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient'], name='laboratory__patient_11fe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='laboratory__status_a16991_idx'),
        ),
    ]
