# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoicing', '0002_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='patients.patientvisit', verbose_name='Visite associée'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='lab_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_items', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='Produit à déduire du stock automatiquement lors du prélèvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_tests', to='invoicing.product', verbose_name='Produit lié'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='labtestcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_categories', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labtestcategory', verbose_name='Catégorie'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['organization', '-order_date'], name='laboratory__organiz_32d831_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient'], name='laboratory__patient_11fe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='laboratory__status_a16991_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labtestcategory',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['organization', 'is_active'], name='laboratory__organiz_8b0669_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test_code'], name='laboratory__test_co_48df4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('organization', 'test_code')},
        ),
    ]
