# Generated by Django 4.2.11 on 2026-01-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_warehouse_is_default_and_more'),
        ('laboratory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='Produit à déduire du stock automatiquement lors du prélèvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_tests', to='invoicing.product', verbose_name='Produit lié'),
        ),
    ]
