# Generated by Django 5.2.10 on 2026-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Réduction totale'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('card', 'Carte Bancaire'), ('insurance', 'Assurance'), ('other', 'Autre')], default='cash', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réduction'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction par défaut pour ce test', max_digits=10, verbose_name='Réduction'),
        ),
        migrations.AlterField(
            model_name='labtestcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
