# Generated by Django 5.2.10 on 2026-01-20 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtest_linked_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='biologist_diagnosis',
            field=models.TextField(blank=True, help_text='Interprétation globale des résultats par le biologiste superviseur', verbose_name='Diagnostic du biologiste'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='diagnosed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du diagnostic'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Diagnostiqué par'),
        ),
    ]
