# Generated by Django 4.2.11 on 2026-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_add_biologist_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix'),
        ),
    ]
