# Generated by Django 5.2.10 on 2026-02-27 06:10

from decimal import Decimal
from django.db import migrations, models


def populate_base_unit(apps, schema_editor):
    LabTest = apps.get_model('laboratory', 'LabTest')
    LabTestParameter = apps.get_model('laboratory', 'LabTestParameter')
    
    for test in LabTest.objects.all():
        test.base_unit = test.unit_of_measurement
        test.save()
        
    for param in LabTestParameter.objects.all():
        param.base_unit = param.unit
        param.save()

class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_add_lab_test_parameter_and_result_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='base_unit',
            field=models.CharField(blank=True, help_text="Unité d'origine stockée en base de données", max_length=50, verbose_name='Unité de base'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text="Multiplicateur pour passer de l'unité de base à l'unité d'affichage", max_digits=10, verbose_name='Facteur de conversion'),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='base_unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité de base'),
        ),
        migrations.AddField(
            model_name='labtestparameter',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10, verbose_name='Facteur de conversion'),
        ),
        migrations.RunPython(populate_base_unit),
    ]
