# Generated by Django 4.2.11 on 2026-03-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_laborder_results_verified_at_and_more'),
        ('laboratory', '0007_labtest_use_large_layout'),
    ]

    operations = [
    ]
