# Generated by Django 5.2.10 on 2026-03-17 06:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('laboratory', '0009_labtestpanel_laborderitem_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Spécialité')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='Cabinet / Structure')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage appliqué sur les factures de labo', max_digits=5, verbose_name='Taux de commission (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribers', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Prescripteur',
                'verbose_name_plural': 'Prescripteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='laboratory.prescriber', verbose_name='Prescripteur externe'),
        ),
    ]
