# Generated by Django 4.2.11 on 2026-03-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_merge_20260303_1036'),
        ('laboratory', '0009_labtestpanel_laborderitem_panel'),
    ]

    operations = [
    ]
