# Generated by Django 4.2.11 on 2026-03-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_merge_20260310_0547'),
        ('laboratory', '0010_prescriber_model'),
    ]

    operations = [
    ]
