# Generated by Django 5.2.10 on 2026-03-20 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('laboratory', '0010_prescriber_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du laboratoire')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, help_text='Logo affiché sur les rapports PDF sous-traités', null=True, upload_to='subcontractors/logos/', verbose_name='Logo')),
                ('header_text', models.TextField(blank=True, help_text="Texte d'entête affiché sur les rapports PDF (adresse complète, accréditations, etc.)", verbose_name='Entête du rapport')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_labs', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Laboratoire sous-traitant',
                'verbose_name_plural': 'Laboratoires sous-traitants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='subcontractor',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, la commande est sous-traitée à ce laboratoire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='laboratory.subcontractorlab', verbose_name='Sous-traitant'),
        ),
        migrations.CreateModel(
            name='SubcontractorPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix facturé au patient pour cet examen chez ce sous-traitant', max_digits=10, verbose_name='Prix sous-traitance')),
                ('turnaround_days', models.IntegerField(default=3, help_text='Délai de rendu des résultats en jours ouvrables', verbose_name='Délai (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_prices', to='laboratory.labtest', verbose_name='Examen')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='laboratory.subcontractorlab', verbose_name='Sous-traitant')),
            ],
            options={
                'verbose_name': 'Tarif sous-traitance',
                'verbose_name_plural': 'Tarifs sous-traitance',
                'ordering': ['lab_test__name'],
                'unique_together': {('subcontractor', 'lab_test')},
            },
        ),
    ]
