# Generated by Django 4.2.11 on 2026-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_add_subcontractor_models'),
        ('laboratory', '0011_merge_0010_merge_20260310_0547_0010_prescriber_model'),
    ]

    operations = [
    ]
