# Generated by Django 5.2.10 on 2026-03-22 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('laboratory', '0011_add_subcontractor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorlab',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='brand_color',
            field=models.CharField(blank=True, default='#2563eb', help_text='Couleur utilisée dans les entêtes des rapports (format: #RRGGBB)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='niu',
            field=models.CharField(blank=True, help_text='Numéro Identifiant Unique (Cameroun)', max_length=50, verbose_name='NIU'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='rc_number',
            field=models.CharField(blank=True, help_text='Registre de Commerce', max_length=50, verbose_name='Numéro RC'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='rccm_number',
            field=models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier', max_length=50, verbose_name='Numéro RCCM'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro contribuable'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='subcontractorlab',
            name='header_text',
            field=models.TextField(blank=True, help_text="Texte libre affiché dans l'entête des rapports (accréditations, mentions légales…)", verbose_name='Entête libre'),
        ),
        migrations.CreateModel(
            name='SubcontractorPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('external_id', models.CharField(blank=True, help_text='Identifiant du patient dans le système du sous-traitant', max_length=100, verbose_name='Référence externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='laboratory.subcontractorlab', verbose_name='Laboratoire sous-traitant')),
            ],
            options={
                'verbose_name': 'Patient sous-traitant',
                'verbose_name_plural': 'Patients sous-traitants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='subcontractor_patient',
            field=models.ForeignKey(blank=True, help_text='Patient du laboratoire sous-traitant (distinct des patients du centre de santé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='laboratory.subcontractorpatient', verbose_name='Patient sous-traitant'),
        ),
        migrations.CreateModel(
            name='SubcontractorDefaultPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix de référence utilisé pour tous les sous-traitants sans tarif spécifique', max_digits=10, verbose_name='Prix par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_default_price', to='laboratory.labtest', verbose_name='Examen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_default_prices', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Tarif sous-traitance par défaut',
                'verbose_name_plural': 'Tarifs sous-traitance par défaut',
                'ordering': ['lab_test__name'],
                'unique_together': {('organization', 'lab_test')},
            },
        ),
    ]
