# Generated by Django 5.2.10 on 2026-03-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('laboratory', '0012_add_subcontractor_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorpatient',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Créé automatiquement lors de la première commande pour ce patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_patient_records', to='accounts.client', verbose_name='Patient interne'),
        ),
    ]
