# Generated by Django 5.2.10 on 2026-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_subcontractorpatient_client_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='show_on_new_page',
            field=models.BooleanField(default=False, help_text='Force le passage à une nouvelle page pour cet examen dans le rapport PDF', verbose_name='Afficher seul sur une page'),
        ),
    ]
