# Generated by Django 4.2.11 on 2026-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_merge_20260322_1409'),
        ('laboratory', '0013_subcontractorpatient_client_link'),
    ]

    operations = [
    ]
