# Generated by Django 5.2.10 on 2026-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_labtest_show_on_new_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorpatient',
            name='age',
            field=models.IntegerField(blank=True, help_text='Utilisé si la date de naissance est inconnue', null=True, verbose_name='Âge'),
        ),
    ]
