# Generated by Django 4.2.11 on 2026-03-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_labtest_show_on_new_page'),
        ('laboratory', '0014_merge_20260322_1700'),
    ]

    operations = [
    ]
