# Generated by Django 4.2.11 on 2026-04-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_add_age_to_subcontractor_patient'),
        ('laboratory', '0015_merge_20260326_0706'),
    ]

    operations = [
    ]
