# Generated by Django 5.2.10 on 2026-04-13 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_add_subcontractor_fields_to_invoice'),
        ('laboratory', '0015_add_age_to_subcontractor_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestConsumable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_test', models.PositiveIntegerField(default=1, help_text="Nombre d'unités de ce produit consommées par test effectué", verbose_name='Quantité par test')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='laboratory.labtest', verbose_name='Examen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_consumables', to='invoicing.product', verbose_name='Produit consommable')),
            ],
            options={
                'verbose_name': 'Consommable de test',
                'verbose_name_plural': 'Consommables de test',
                'ordering': ['lab_test', 'product__name'],
                'unique_together': {('lab_test', 'product')},
            },
        ),
    ]
