# Generated by Django 4.2.11 on 2026-04-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_add_lab_test_consumable'),
        ('laboratory', '0016_merge_20260410_0952'),
    ]

    operations = [
    ]
