# Generated by Django 5.2.10 on 2026-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_add_lab_test_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorlab',
            name='footer_image',
            field=models.ImageField(blank=True, help_text='Image pleine largeur pour le pied de page du rapport PDF', null=True, upload_to='subcontractors/footers/', verbose_name='Image de pied de page'),
        ),
        migrations.AddField(
            model_name='subcontractorlab',
            name='header_image',
            field=models.ImageField(blank=True, help_text="Image pleine largeur pour l'en-tête du rapport PDF", null=True, upload_to='subcontractors/headers/', verbose_name="Image d'en-tête"),
        ),
    ]
