# Generated by Django 4.2.11 on 2026-04-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0017_merge_20260413_2236'),
        ('laboratory', '0017_subcontractorlab_footer_image_and_more'),
    ]

    operations = [
    ]
