# Generated by Django 5.2.10 on 2026-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0017_subcontractorlab_footer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='subcontract_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix appliqué aux laboratoires sous-traitants', max_digits=10, null=True, verbose_name='Prix sous-traitance'),
        ),
    ]
