# Generated by Django 5.2.10 on 2026-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0018_labtest_subcontract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='operating_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût de revient : réactifs, amortissement, charges, salaires… à saisir manuellement', max_digits=10, null=True, verbose_name='Coût de fonctionnement'),
        ),
    ]
