# Generated by Django 4.2.11 on 2026-05-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0018_merge_20260421_0621'),
        ('laboratory', '0019_add_operating_cost_to_labtest'),
    ]

    operations = [
    ]
