# Generated by Django 5.2.10 on 2026-05-19 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_lab_audit_log'),
        ('laboratory', '0020_merge_20260509_2323'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10, verbose_name='Action')),
                ('target_type', models.CharField(choices=[('lab_test', 'Test de laboratoire'), ('subcontractor', 'Laboratoire sous-traitant'), ('subcontractor_price', 'Tarif sous-traitance'), ('lab_order', 'Commande de laboratoire')], max_length=30, verbose_name='Type de cible')),
                ('target_id', models.CharField(max_length=100, verbose_name='ID de la cible')),
                ('target_name', models.CharField(max_length=300, verbose_name='Nom de la cible')),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Diff JSON des champs modifiés : {'field': [old, new]}", verbose_name='Modifications')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_audit_logs', to='accounts.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit laboratoire",
                'verbose_name_plural': "Logs d'audit laboratoire",
                'ordering': ['-timestamp'],
            },
        ),
    ]
