# Generated by Django 4.2.11 on 2026-05-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0018_merge_20260421_0621'),
        ('laboratory', '0021_add_lab_audit_log'),
    ]

    operations = [
    ]
