# Generated by Django 5.2.10 on 2026-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0022_merge_0018_merge_20260421_0621_0021_add_lab_audit_log'),
        ('laboratory', '0020_merge_20260509_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labauditlog',
            name='target_type',
            field=models.CharField(choices=[('lab_test', 'Test de laboratoire'), ('subcontractor', 'Laboratoire sous-traitant'), ('subcontractor_price', 'Tarif sous-traitance'), ('lab_order', 'Commande de laboratoire'), ('invoice', 'Facture')], max_length=30, verbose_name='Type de cible'),
        ),
    ]
