# Generated by Django 5.2.10 on 2026-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0023_add_invoice_target_to_lab_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labauditlog',
            name='target_type',
            field=models.CharField(choices=[('lab_test', 'Test de laboratoire'), ('subcontractor', 'Laboratoire sous-traitant'), ('subcontractor_price', 'Tarif sous-traitance'), ('lab_order', 'Commande de laboratoire'), ('invoice', 'Facture'), ('prescriber', 'Prescripteur')], max_length=30, verbose_name='Type de cible'),
        ),
    ]
