# Generated by Django 4.2.11 on 2026-07-18 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_add_prescriber_target_to_lab_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='laboratory.subcontractorlab', verbose_name='Sous-traitant')),
            ],
            options={
                'verbose_name': 'Contact sous-traitance',
                'verbose_name_plural': 'Contacts sous-traitance',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
    ]
