# Generated by Django 4.2.11 on 2026-07-18 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0025_add_subcontractor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborderitem',
            name='sample_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Échantillon prélevé à'),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='sample_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_lab_items', to=settings.AUTH_USER_MODEL, verbose_name='Prélevé par'),
        ),
    ]
