# Generated by Django 4.2.11 on 2026-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imagingorder_linked_lab_order_imagingorderitem_panel_and_more'),
        ('laboratory', '0026_add_item_sample_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestpanel',
            name='imaging_exam_types',
            field=models.ManyToManyField(blank=True, related_name='panels', to='imaging.imagingexamtype', verbose_name="Examens d'imagerie inclus"),
        ),
    ]
