# Generated by Django 4.2.11 on 2026-08-17 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imagingorder_linked_lab_order_imagingorderitem_panel_and_more'),
        ('laboratory', '0027_labtestpanel_imaging_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriber',
            name='pricing_mode',
            field=models.CharField(choices=[('commission', 'Commission (% sur le prix normal)'), ('custom_price', 'Prix libre (le prescripteur fixe son propre prix)')], default='commission', help_text='Commission : le patient paie le prix normal, le prescripteur touche un %. Prix libre : le patient paie le prix fixé par le prescripteur, la clinique garde son prix normal et reverse la différence au prescripteur.', max_length=20, verbose_name='Mode de tarification'),
        ),
        migrations.CreateModel(
            name='PrescriberCustomPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix fixé par le prescripteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriber_custom_prices', to='imaging.imagingexamtype', verbose_name="Examen d'imagerie")),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriber_custom_prices', to='laboratory.labtest', verbose_name='Test de laboratoire')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='laboratory.prescriber', verbose_name='Prescripteur')),
            ],
            options={
                'verbose_name': 'Prix personnalisé prescripteur',
                'verbose_name_plural': 'Prix personnalisés prescripteur',
            },
        ),
        migrations.AddConstraint(
            model_name='prescribercustomprice',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exam_type__isnull', True), ('lab_test__isnull', False)), models.Q(('exam_type__isnull', False), ('lab_test__isnull', True)), _connector='OR'), name='prescriber_custom_price_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='prescribercustomprice',
            constraint=models.UniqueConstraint(fields=('prescriber', 'lab_test'), name='unique_prescriber_lab_test_price'),
        ),
        migrations.AddConstraint(
            model_name='prescribercustomprice',
            constraint=models.UniqueConstraint(fields=('prescriber', 'exam_type'), name='unique_prescriber_exam_type_price'),
        ),
    ]
