# Generated by Django 4.2.11 on 2026-09-17 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_product_tests_per_unit_product_untracked_tests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userpermissions_module_permissions'),
        ('laboratory', '0028_prescriber_pricing_mode_prescribercustomprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('unit', 'Unité'), ('test', 'Test')], default='unit', max_length=10, verbose_name='Unité')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Utilisé le')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_usages', to='invoicing.productbatch', verbose_name='Lot utilisé')),
                ('lab_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_usages', to='laboratory.laborderitem', verbose_name='Examen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_usages', to='accounts.organization', verbose_name='Organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_usages', to='invoicing.product', verbose_name='Réactif')),
            ],
            options={
                'verbose_name': 'Réactif utilisé',
                'verbose_name_plural': 'Réactifs utilisés',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['batch', '-used_at'], name='laboratory__batch_i_079516_idx'), models.Index(fields=['product', '-used_at'], name='laboratory__product_74f00d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReagentQualityControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_on', models.DateField(verbose_name='Date du contrôle')),
                ('control_type', models.CharField(choices=[('control_serum', 'Sérum de contrôle'), ('positive', 'Témoin positif'), ('negative', 'Témoin négatif'), ('duplicate', 'Double lecture / répétabilité'), ('other', 'Autre')], default='control_serum', max_length=20, verbose_name='Type de contrôle')),
                ('result', models.CharField(choices=[('conform', 'Conforme'), ('non_conform', 'Non conforme')], max_length=15, verbose_name='Résultat')),
                ('values', models.TextField(blank=True, default='', verbose_name='Valeurs mesurées / attendues')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='invoicing.productbatch', verbose_name='Lot de réactif')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_quality_controls', to='accounts.organization', verbose_name='Organisation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_quality_controls', to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
            ],
            options={
                'verbose_name': 'Contrôle qualité de réactif',
                'verbose_name_plural': 'Contrôles qualité de réactifs',
                'ordering': ['-performed_on', '-created_at'],
                'indexes': [models.Index(fields=['batch', '-performed_on'], name='laboratory__batch_i_c63663_idx')],
            },
        ),
    ]
