# Generated by Django 5.2.10 on 2026-05-06 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('laboratory', '0018_labtest_subcontract_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du pack')),
                ('category', models.CharField(choices=[('couples', 'Couples & Bilan Prénuptial'), ('maternity', 'Maternité & Suivi de Grossesse'), ('seniority', 'Sénior & Bilan de Santé Général'), ('general', 'Bilan Général')], default='general', max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name="Description / Note d'intention")),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix original (somme des tests)')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix du pack remisé')),
                ('included_tests_text', models.TextField(blank=True, help_text='Liste des analyses ou prestations (pour affichage PDF si différent de la base)', verbose_name='Analyses incluses (Texte libre)')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_tests', models.ManyToManyField(blank=True, related_name='packages', to='laboratory.labtest', verbose_name='Analyses incluses')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_packages', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Pack Santé',
                'verbose_name_plural': 'Packs Santé',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('price_list_public', 'Liste de prix (Public)'), ('price_list_subcontract', 'Liste de prix (Sous-traitance)'), ('packs_catalog', 'Catalogue de packs'), ('full_catalog', 'Catalogue complet (Tarifs + Infos)')], max_length=50, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='Date de révision')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text="Textes d'introduction, mentions légales, notes de bas de page, etc.", verbose_name='Champs personnalisés')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='document_headers/', verbose_name="Image d'en-tête personnalisée")),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='document_footers/', verbose_name='Image de pied de page personnalisée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Document de l'Organisation",
                'verbose_name_plural': "Documents de l'Organisation",
                'unique_together': {('organization', 'document_type')},
            },
        ),
    ]
