# Generated by Django 5.2.10 on 2026-05-08 14:28

import apps.document_generator.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('document_generator', '0001_initial'),
        ('invoicing', '0009_invoice_global_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.document_generator.models._generate_coupon_code, help_text='Code unique remis à la patiente', max_length=20, unique=True, verbose_name='Code coupon')),
                ('label', models.CharField(blank=True, help_text='Ex: Offre Fête des Mères, Fidélité patiente, Pack prénatal', max_length=150, verbose_name='Libellé')),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage (%)'), ('fixed', 'Montant fixe (FCFA)')], default='percent', max_length=10, verbose_name='Type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Ex: 10 pour 10% ou 5000 pour 5 000 FCFA', max_digits=10, verbose_name='Valeur de la remise')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 = aucun minimum', max_digits=12, verbose_name='Montant minimum de facture')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de remise pour les coupons %. Vide = illimité.', max_digits=12, null=True, verbose_name='Remise maximale (FCFA)')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='1 = usage unique', verbose_name="Nombre d'utilisations max")),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('expires_at', models.DateTimeField(blank=True, help_text="Laisser vide = pas d'expiration", null=True, verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_invoices', models.ManyToManyField(blank=True, related_name='applied_coupons', to='invoicing.invoice', verbose_name='Factures où appliqué')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_coupons', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Coupon de réduction',
                'verbose_name_plural': 'Coupons de réduction',
                'ordering': ['-created_at'],
            },
        ),
    ]
