# Generated by Django 4.2.11 on 2026-08-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0002_add_discount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='is_surcharge',
            field=models.BooleanField(default=False, help_text="Si coché, ce coupon AJOUTE le montant au total au lieu de le retirer (ex: frais d'urgence, majoration de nuit).", verbose_name='Majoration'),
        ),
        migrations.AlterField(
            model_name='organizationdocument',
            name='document_type',
            field=models.CharField(choices=[('price_list_public', 'Liste de prix (Public)'), ('price_list_subcontract', 'Liste de prix (Sous-traitance)'), ('packs_catalog', 'Catalogue de packs'), ('bilans_list', 'Liste des bilans'), ('services_list', 'Liste des soins & services'), ('full_catalog', 'Catalogue complet (Tarifs + Infos)')], max_length=50, verbose_name='Type de document'),
        ),
    ]
