"""
Configuration des 82 tests d'analyse médicale pour le Centre de Santé JULIANNA
Basé sur les standards internationaux et valeurs de référence cliniques
"""

# Catégories de tests
LAB_CATEGORIES = [
    {'name': 'Hématologie', 'slug': 'hematologie', 'order': 1},
    {'name': 'Biochimie Générale', 'slug': 'biochimie', 'order': 2},
    {'name': 'Ionogrammes', 'slug': 'ionogramme', 'order': 3},
    {'name': 'Sérologie', 'slug': 'serologie', 'order': 4},
    {'name': 'Bactériologie', 'slug': 'bacteriologie', 'order': 5},
    {'name': 'Parasitologie', 'slug': 'parasitologie', 'order': 6},
    {'name': 'Hormonologie', 'slug': 'hormonologie', 'order': 7},
    {'name': 'Électrophorèses', 'slug': 'electrophorese', 'order': 8},
]

# 82 Tests d'analyse médicale complets
LAB_TESTS = [
    # BIOCHIMIE GÉNÉRALE (Tests 1-15)
    {
        'code': 'BIO-AU',
        'name': 'ACIDE URIQUE',
        'short_name': 'Acide Urique',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_male': '3.5-7.2',
        'normal_female': '2.6-6.0',
        'methodology': 'Méthode enzymatique uricase',
    },
    {
        'code': 'BIO-ALB',
        'name': 'ALBUMINE (Sérique)',
        'short_name': 'Albumine',
        'category': 'biochimie',
        'price': 800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '2 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 3,
        'unit': 'g/L',
        'normal_general': '35-52',
        'methodology': 'Vert de Bromocrésol',
    },
    {
        'code': 'URO-ALBSUC',
        'name': 'ALBUMINE/SUCRE (Urines)',
        'short_name': 'Albumine/Sucre urines',
        'category': 'biochimie',
        'price': 800,
        'sample_type': 'urine',
        'container': 'urine_cup',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Bandelette urinaire',
    },
    {
        'code': 'BIO-BLIP',
        'name': 'BILAN LIPIDIQUE',
        'short_name': 'Bilan Lipidique',
        'category': 'biochimie',
        'price': 9400,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 6,
        'unit': 'mg/dL',
        'normal_general': 'CT<200, HDL>40, LDL<130, TG<150',
        'methodology': 'Méthode enzymatique colorimétrique',
    },
    {
        'code': 'BIO-BILD',
        'name': 'BILIRUBINE DIRECTE',
        'short_name': 'Bili Directe',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '0-0.3',
        'methodology': 'Méthode de Jendrassik-Grof',
    },
    {
        'code': 'BIO-BILT',
        'name': 'BILIRUBINE TOTALE',
        'short_name': 'Bili Totale',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '0.2-1.2',
        'methodology': 'Méthode de Jendrassik-Grof',
    },
    {
        'code': 'BIO-CAS',
        'name': 'CALCIUM Ca++ (sérum)',
        'short_name': 'Calcium sérique',
        'category': 'biochimie',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '8.6-10.2',
        'methodology': 'Méthode colorimétrique O-crésol',
    },
    {
        'code': 'URO-CAU',
        'name': 'CALCIUM Ca++ (urines)',
        'short_name': 'Calcium urinaire',
        'category': 'biochimie',
        'price': 4800,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/24h',
        'normal_male': '100-300',
        'normal_female': '100-250',
        'methodology': 'Colorimétrique',
    },
    {
        'code': 'URO-CHIM',
        'name': 'CHIMIE URINAIRE',
        'short_name': 'Chimie Urinaire',
        'category': 'biochimie',
        'price': 800,
        'sample_type': 'urine',
        'container': 'urine_cup',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Qualitatif',
        'normal_general': 'pH 5-8, Densité 1.005-1.030',
        'methodology': 'Bandelette réactive',
    },
    {
        'code': 'BIO-CT',
        'name': 'CHOLESTÉROL TOTAL',
        'short_name': 'Cholest. Total',
        'category': 'biochimie',
        'price': 4500,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<200',
        'methodology': 'CHOD-PAP enzymatique',
    },
    {
        'code': 'BIO-HDL',
        'name': 'CHOLESTÉROL HDL',
        'short_name': 'HDL',
        'category': 'biochimie',
        'price': 10000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_male': '>40',
        'normal_female': '>50',
        'methodology': 'Précipitation sélective',
    },
    {
        'code': 'BIO-LDL',
        'name': 'CHOLESTÉROL LDL',
        'short_name': 'LDL',
        'category': 'biochimie',
        'price': 4500,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<130',
        'methodology': 'Formule de Friedewald',
    },
    {
        'code': 'BIO-CREAS',
        'name': 'CRÉATININE (sérum)',
        'short_name': 'Créatinine',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mg/dL',
        'normal_male': '0.7-1.2',
        'normal_female': '0.5-0.9',
        'methodology': 'Méthode de Jaffé',
    },
    {
        'code': 'URO-CREAU',
        'name': 'CRÉATININE (urines)',
        'short_name': 'Créat. urinaire',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 3,
        'unit': 'g/24h',
        'normal_male': '1.0-2.0',
        'normal_female': '0.8-1.8',
        'methodology': 'Méthode de Jaffé',
    },
    {
        'code': 'BIO-CRP',
        'name': 'CRP (C Reactive Protein)',
        'short_name': 'CRP',
        'category': 'biochimie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/L',
        'normal_general': '<5',
        'methodology': 'Immunoturbidimétrie',
    },
    
    # IONOGRAMMES (Tests 16-25)
    {
        'code': 'ION-CS',
        'name': 'IONOGRAMME COMPLET (sérum)',
        'short_name': 'Ionogramme sérum',
        'category': 'ionogramme',
        'price': 24000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mmol/L',
        'normal_general': 'Na 136-145, K 3.5-5.0, Cl 98-106',
        'methodology': 'Électrode sélective (ISE)',
    },
    {
        'code': 'ION-CU',
        'name': 'IONOGRAMME COMPLET (urines)',
        'short_name': 'Ionogramme urines',
        'category': 'ionogramme',
        'price': 24000,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mmol/24h',
        'normal_general': 'Na 40-220, K 25-125',
        'methodology': 'Électrode sélective',
    },
    {
        'code': 'ION-SIMP',
        'name': 'IONOGRAMME SIMPLE',
        'short_name': 'Iono Simple',
        'category': 'ionogramme',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mmol/L',
        'normal_general': 'Na 136-145, K 3.5-5.0, Cl 98-106',
        'methodology': 'ISE',
    },
    {
        'code': 'BIO-MGS',
        'name': 'MAGNÉSIUM Mg++ (sérum)',
        'short_name': 'Mg sérique',
        'category': 'ionogramme',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '1.6-2.6',
        'methodology': 'Colorimétrique',
    },
    {
        'code': 'URO-MGU',
        'name': 'MAGNÉSIUM Mg++ (urines)',
        'short_name': 'Mg urinaire',
        'category': 'ionogramme',
        'price': 4800,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/24h',
        'normal_general': '73-122',
        'methodology': 'Colorimétrique',
    },
    {
        'code': 'BIO-PHS',
        'name': 'PHOSPHORE Ph (sérum)',
        'short_name': 'Phosphore',
        'category': 'ionogramme',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mg/dL',
        'normal_general': '2.5-4.5',
        'methodology': 'Molybdate UV',
    },
    {
        'code': 'URO-PHU',
        'name': 'PHOSPHORE Ph (urines)',
        'short_name': 'Phosphore urinaire',
        'category': 'ionogramme',
        'price': 4000,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mg/24h',
        'normal_general': '400-1300',
        'methodology': 'Molybdate UV',
    },
    {
        'code': 'ION-KS',
        'name': 'POTASSIUM K+ (sérum)',
        'short_name': 'Potassium',
        'category': 'ionogramme',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mmol/L',
        'normal_general': '3.5-5.0',
        'methodology': 'ISE',
    },
    {
        'code': 'URO-KU',
        'name': 'POTASSIUM K+ (urines)',
        'short_name': 'K urinaire',
        'category': 'ionogramme',
        'price': 4800,
        'sample_type': 'urine',
        'container': 'urine_24h',
        'sample_volume': '24h',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mmol/24h',
        'normal_general': '25-125',
        'methodology': 'ISE',
    },
    {
        'code': 'ION-NA',
        'name': 'SODIUM Na+',
        'short_name': 'Sodium',
        'category': 'ionogramme',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mmol/L',
        'normal_general': '136-145',
        'methodology': 'ISE',
    },
    
    # ÉLECTROPHORÈSES (Tests 26-27)
    {
        'code': 'HEM-ELPHB',
        'name': 'ÉLECTROPHORÈSE HÉMOGLOBINE',
        'short_name': 'Électrophorèse Hb',
        'category': 'hematologie',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': '%',
        'normal_general': 'HbA 95-98%, HbA2 2-3%, HbF <2%',
        'methodology': 'Électrophorèse capillaire',
    },
    {
        'code': 'BIO-ELPROT',
        'name': 'ÉLECTROPHORÈSE PROTÉINES',
        'short_name': 'Électrophorèse Prot.',
        'category': 'biochimie',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'g/L',
        'normal_general': 'Albumine 35-52, Globulines normal',
        'methodology': 'Électrophorèse sur gel',
    },
    
    # BIOCHIMIE SPÉCIALISÉE (Tests 28-39)
    {
        'code': 'BIO-FER',
        'name': 'FER SÉRIQUE',
        'short_name': 'Fer',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'turnaround': 4,
        'unit': 'µg/dL',
        'normal_male': '60-160',
        'normal_female': '50-170',
        'methodology': 'Colorimétrique ferrozine',
    },
    {
        'code': 'HEM-G6PD',
        'name': 'G6PDH (G6PD)',
        'short_name': 'G6PD',
        'category': 'hematologie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/g Hb',
        'normal_general': '7-20',
        'methodology': 'Méthode fluorométrique',
    },
    {
        'code': 'BIO-GGT',
        'name': 'GAMMA GT (γGT)',
        'short_name': 'Gamma GT',
        'category': 'biochimie',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_male': '<55',
        'normal_female': '<38',
        'methodology': 'Cinétique IFCC',
    },
    {
        'code': 'BIO-PAL',
        'name': 'PAL (Phosphatase Alcaline)',
        'short_name': 'PAL',
        'category': 'biochimie',
        'price': 8000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_general': '30-120',
        'methodology': 'pNPP IFCC',
    },
    {
        'code': 'BIO-GLU',
        'name': 'GLYCÉMIE À JEUN',
        'short_name': 'Glycémie',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'fluoride',
        'sample_volume': '2 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '70-100',
        'methodology': 'GOD-POD enzymatique',
    },
    {
        'code': 'BIO-GLUPP',
        'name': 'GLYCÉMIE POST PRANDIALE',
        'short_name': 'Glycémie PP',
        'category': 'biochimie',
        'price': 3400,
        'sample_type': 'blood',
        'container': 'fluoride',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '<140',
        'methodology': 'GOD-POD',
    },
    {
        'code': 'HORM-HCG',
        'name': 'HCG GROSSESSE',
        'short_name': 'β-HCG',
        'category': 'hormonologie',
        'price': 6800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_general': '<5 (non enceinte)',
        'methodology': 'ELISA',
    },
    {
        'code': 'BIO-PROT',
        'name': 'PROTÉINES TOTALES',
        'short_name': 'Protéines',
        'category': 'biochimie',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'g/L',
        'normal_general': '60-80',
        'methodology': 'Biuret',
    },
    {
        'code': 'BIO-TRANS',
        'name': 'TRANSAMINASES (SGOT/SGPT)',
        'short_name': 'ASAT/ALAT',
        'category': 'biochimie',
        'price': 8000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_male': 'ASAT<37, ALAT<41',
        'normal_female': 'ASAT<31, ALAT<31',
        'methodology': 'IFCC sans P5P',
    },
    {
        'code': 'BIO-TG',
        'name': 'TRIGLYCÉRIDES',
        'short_name': 'Triglycérides',
        'category': 'biochimie',
        'price': 1000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<150',
        'methodology': 'GPO-PAP enzymatique',
    },
    {
        'code': 'BIO-UREE',
        'name': 'URÉE',
        'short_name': 'Urée',
        'category': 'biochimie',
        'price': 2800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '15-45',
        'methodology': 'Uréase enzymatique',
    },
    {
        'code': 'HEM-VS',
        'name': 'VITESSE DE SÉDIMENTATION',
        'short_name': 'VS',
        'category': 'hematologie',
        'price': 1400,
        'sample_type': 'blood',
        'container': 'citrate',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mm/h',
        'normal_male': '<15',
        'normal_female': '<20',
        'methodology': 'Westergren',
    },
    
    # HÉMATOLOGIE (Tests 40-44)
    {
        'code': 'HEM-GS',
        'name': 'GROUPE SANGUIN (ABO-RH)',
        'short_name': 'Groupe Sanguin',
        'category': 'hematologie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'Qualitatif',
        'normal_general': 'A, B, AB, O, Rh+/-',
        'methodology': 'Agglutination sur carte',
    },
    {
        'code': 'HEM-NFS',
        'name': 'NFS (Numération Formule)',
        'short_name': 'NFS',
        'category': 'hematologie',
        'price': 5400,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'G/L',
        'normal_male': 'Hb 13-17, Leuco 4-10',
        'normal_female': 'Hb 12-16, Leuco 4-10',
        'methodology': 'Automate hématologie',
    },
    {
        'code': 'PARA-PALU',
        'name': 'PALUDISME + Quantification',
        'short_name': 'GE Paludisme',
        'category': 'parasitologie',
        'price': 1600,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Parasites/µL',
        'normal_general': 'Absence de parasites',
        'methodology': 'Microscopie (GE + Frottis)',
    },
    {
        'code': 'HEM-RETIC',
        'name': 'RÉTICULOCYTES',
        'short_name': 'Réticulocytes',
        'category': 'hematologie',
        'price': 1600,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': '%',
        'normal_general': '0.5-2.0',
        'methodology': 'Coloration vital',
    },
    {
        'code': 'HEM-TP',
        'name': 'TAUX PROTHROMBINE (TP)',
        'short_name': 'TP/INR',
        'category': 'hematologie',
        'price': 1200,
        'sample_type': 'blood',
        'container': 'citrate',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': '%',
        'normal_general': '70-100% (INR 0.8-1.2)',
        'methodology': 'Coagulométrie',
    },
    
    # SÉROLOGIE (Tests 45-55)
    {
        'code': 'SERO-ASLO',
        'name': 'ASLO',
        'short_name': 'ASLO',
        'category': 'serologie',
        'price': 5400,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': '<200',
        'methodology': 'Immunoturbidimétrie',
    },
    {
        'code': 'SERO-HEPA',
        'name': 'HÉPATITE A (IgM)',
        'short_name': 'HAV IgM',
        'category': 'serologie',
        'price': 9400,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-HBS',
        'name': 'HÉPATITE B (Ag HBS)',
        'short_name': 'AgHBs',
        'category': 'serologie',
        'price': 9400,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-HCV',
        'name': 'HÉPATITE C (Ac Anti-HCV)',
        'short_name': 'Anti-HCV',
        'category': 'serologie',
        'price': 9000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-HERPES',
        'name': 'HERPES (IgG, IgM)',
        'short_name': 'HSV IgG/IgM',
        'category': 'serologie',
        'price': 9000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-FR',
        'name': 'FACTEUR RHUMATOÏDE',
        'short_name': 'Fact. Rhum.',
        'category': 'serologie',
        'price': 4800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': '<14',
        'methodology': 'Immunoturbidimétrie',
    },
    {
        'code': 'SERO-SYPH',
        'name': 'SYPHILIS (TPHA - VDRL)',
        'short_name': 'TPHA/VDRL',
        'category': 'serologie',
        'price': 6800,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Agglutination + VDRL',
    },
    {
        'code': 'SERO-TESTG',
        'name': 'TEST DE GROSSESSE',
        'short_name': 'Test Grossesse',
        'category': 'serologie',
        'price': 2000,
        'sample_type': 'urine',
        'container': 'urine_cup',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Test rapide HCG',
    },
    {
        'code': 'SERO-HIV',
        'name': 'VIH 1 & VIH 2',
        'short_name': 'HIV 1&2',
        'category': 'serologie',
        'price': 2600,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Test rapide + ELISA',
    },
    {
        'code': 'SERO-TOXO',
        'name': 'TOXOPLASMOSE',
        'short_name': 'Toxo IgG/IgM',
        'category': 'serologie',
        'price': 9000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Variable',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-CHLAM',
        'name': 'CHLAMYDIA TRACHOMATIS',
        'short_name': 'Chlamydia',
        'category': 'serologie',
        'price': 13800,
        'sample_type': 'other',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'PCR',
    },
    
    # BACTÉRIOLOGIE (Tests 56-68)
    {
        'code': 'BACT-ECBU',
        'name': 'ECBU (Examen Cytobact. Urines)',
        'short_name': 'ECBU',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'urine',
        'container': 'sterile',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'UFC/mL',
        'normal_general': '<10³',
        'methodology': 'Culture + Antibiogramme',
    },
    {
        'code': 'BACT-GORGE',
        'name': 'EXAMEN CYTOBACT. Frottis gorge',
        'short_name': 'Frottis gorge',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'swab',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore normale',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-PONCT',
        'name': 'EXAMEN CYTOBACT. Liquide ponction',
        'short_name': 'Ponction',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'other',
        'container': 'sterile',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-PCV',
        'name': 'EXAMEN CYTOBACT. Cervico-vaginal',
        'short_name': 'PCV',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'swab',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore de Döderlein',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-PUS',
        'name': 'EXAMEN CYTOBACT. Pus',
        'short_name': 'Pus',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'other',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Variable',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-NEZ',
        'name': 'EXAMEN CYTOBACT. Nez',
        'short_name': 'Frottis nez',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'swab',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore normale',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-URETH',
        'name': 'EXAMEN CYTOBACT. Urétral',
        'short_name': 'Frottis urétral',
        'category': 'bacteriologie',
        'price': 12800,
        'sample_type': 'swab',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-COPRO',
        'name': 'COPROCULTURE',
        'short_name': 'Coproculture',
        'category': 'bacteriologie',
        'price': 8000,
        'sample_type': 'stool',
        'container': 'stool_cup',
        'sample_volume': '5 g',
        'fasting': False,
        'turnaround': 72,
        'unit': 'Qualitatif',
        'normal_general': 'Flore normale',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-SPERMO',
        'name': 'SPERMOCULTURE',
        'short_name': 'Spermoculture',
        'category': 'bacteriologie',
        'price': 15000,
        'sample_type': 'semen',
        'container': 'sterile',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'UFC/mL',
        'normal_general': '<10³',
        'methodology': 'Culture + ATB',
    },
    {
        'code': 'BACT-SPERMO-EXAM',
        'name': 'SPERMOGRAMME',
        'short_name': 'Spermogramme',
        'category': 'bacteriologie',
        'price': 10000,
        'sample_type': 'semen',
        'container': 'sterile',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'millions/mL',
        'normal_general': '≥16 millions/mL',
        'methodology': 'Microscopie OMS 2021',
    },
    
    # HÉMATOLOGIE SPÉCIALISÉE ET PARASITOLOGIE (Tests 65-66)
    {
        'code': 'HEM-HBA1C',
        'name': 'HbA1C (Hémoglobine glyquée)',
        'short_name': 'HbA1C',
        'category': 'hematologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': '%',
        'normal_general': '<5.7',
        'methodology': 'HPLC',
    },
    {
        'code': 'PARA-KAOP',
        'name': 'SELLES : KAOP',
        'short_name': 'KAOP',
        'category': 'parasitologie',
        'price': 1600,
        'sample_type': 'stool',
        'container': 'stool_cup',
        'sample_volume': '5 g',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Absence de parasites',
        'methodology': 'Examen direct + concentration',
    },
    
    # HORMONOLOGIE (Tests 69-77)
    {
        'code': 'HORM-PSA',
        'name': 'PSA',
        'short_name': 'PSA',
        'category': 'hormonologie',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/mL',
        'normal_male': '<4.0',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-TSH',
        'name': 'TSH',
        'short_name': 'TSH',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'mUI/L',
        'normal_general': '0.4-4.0',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-T3',
        'name': 'T3',
        'short_name': 'T3',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/dL',
        'normal_general': '80-180',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-T4',
        'name': 'T4',
        'short_name': 'T4',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'µg/dL',
        'normal_general': '4.5-12.0',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-OESTRO',
        'name': 'ŒSTROGÈNE',
        'short_name': 'Estradiol',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'pg/mL',
        'normal_female': '20-600 (variable cycle)',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-PROG',
        'name': 'PROGESTÉRONE',
        'short_name': 'Progestérone',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/mL',
        'normal_female': '1.5-28 (variable cycle)',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-TESTO',
        'name': 'TESTOSTÉRONE',
        'short_name': 'Testostérone',
        'category': 'hormonologie',
        'price': 18000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/dL',
        'normal_male': '250-830',
        'normal_female': '15-75',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-FSH',
        'name': 'FSH',
        'short_name': 'FSH',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_female': '3.5-12.5 (variable cycle)',
        'normal_male': '1.5-12.4',
        'methodology': 'ELISA',
    },
    {
        'code': 'HORM-LH',
        'name': 'LH',
        'short_name': 'LH',
        'category': 'hormonologie',
        'price': 15000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_female': '2.4-12.6 (variable cycle)',
        'normal_male': '1.7-8.6',
        'methodology': 'ELISA',
    },
    
    # BILANS COMPLETS (Tests 78-82)
    {
        'code': 'BILAN-HTA-DIAB',
        'name': 'Bilan HTA/Diabète',
        'short_name': 'Bilan HTA/Diab',
        'category': 'biochimie',
        'price': 35000,
        'sample_type': 'blood',
        'container': 'multiple',
        'sample_volume': '10 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 24,
        'unit': 'Multiple',
        'normal_general': 'Bilan complet',
        'methodology': 'Multiple tests',
    },
    {
        'code': 'BILAN-PRENATAL',
        'name': 'Bilan Prénatal',
        'short_name': 'Bilan Prénatal',
        'category': 'biochimie',
        'price': 25000,
        'sample_type': 'blood',
        'container': 'multiple',
        'sample_volume': '15 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Multiple',
        'normal_general': 'Bilan complet',
        'methodology': 'Multiple tests',
    },
    {
        'code': 'BACT-PUS-ATB',
        'name': 'PUS + ATB',
        'short_name': 'Pus + ATB',
        'category': 'bacteriologie',
        'price': 10000,
        'sample_type': 'other',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Variable',
        'methodology': 'Culture + Antibiogramme complet',
    },
    {
        'code': 'BACT-HPYLORI',
        'name': 'H Pylori',
        'short_name': 'H. Pylori',
        'category': 'bacteriologie',
        'price': 5000,
        'sample_type': 'stool',
        'container': 'stool_cup',
        'sample_volume': '5 g',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Antigène dans selles',
    },
    {
        'code': 'BACT-MYCO',
        'name': 'Mycoplasme',
        'short_name': 'Mycoplasme',
        'category': 'bacteriologie',
        'price': -1,  # Sur devis
        'sample_type': 'other',
        'container': 'sterile',
        'sample_volume': 'Écouv.',
        'fasting': False,
        'turnaround': 72,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'PCR + Culture',
    },
]

# Services et Soins médicaux
MEDICAL_SERVICES = [
    # CONSULTATIONS
    {'name': 'Consultation Médecin Généraliste', 'category': 'Consultations', 'price': 10000, 'duration': 30},
    {'name': 'Consultation Pédiatrie', 'category': 'Consultations', 'price': 12000, 'duration': 30},
    {'name': 'Consultation Médecine Interne', 'category': 'Consultations', 'price': 15000, 'duration': 45},
    {'name': 'Consultation Urgence', 'category': 'Consultations', 'price': 15000, 'duration': 30},
    {'name': 'Consultation Gynécologie', 'category': 'Consultations', 'price': 15000, 'duration': 45},
    {'name': 'Consultation Obstétrique', 'category': 'Consultations', 'price': 15000, 'duration': 45},
    {'name': 'Consultation Cardiologie', 'category': 'Consultations', 'price': 20000, 'duration': 45},
    {'name': 'Consultation Dermatologie', 'category': 'Consultations', 'price': 18000, 'duration': 30},
    {'name': 'Consultation Ophtalmologie', 'category': 'Consultations', 'price': 18000, 'duration': 30},
    {'name': 'Visite à domicile', 'category': 'Consultations', 'price': 25000, 'duration': 60},
    {'name': 'Téléconsultation', 'category': 'Consultations', 'price': 8000, 'duration': 20},
    
    # SOINS INFIRMIERS
    {'name': 'Pansement simple', 'category': 'Soins Infirmiers', 'price': 2500},
    {'name': 'Pansement complexe', 'category': 'Soins Infirmiers', 'price': 5000},
    {'name': 'Injection IM/SC', 'category': 'Soins Infirmiers', 'price': 1500},
    {'name': 'Injection IV', 'category': 'Soins Infirmiers', 'price': 2500},
    {'name': 'Pose de perfusion', 'category': 'Soins Infirmiers', 'price': 5000},
    {'name': 'Prise de tension artérielle', 'category': 'Soins Infirmiers', 'price': 500},
    {'name': 'Glycémie capillaire', 'category': 'Soins Infirmiers', 'price': 1000},
    {'name': 'Sondage urinaire', 'category': 'Soins Infirmiers', 'price': 8000},
    {'name': 'Suture simple (<5 cm)', 'category': 'Soins Infirmiers', 'price': 10000},
    {'name': 'Suture complexe (>5 cm)', 'category': 'Soins Infirmiers', 'price': 20000},
    
    # MATERNITÉ
    {'name': 'Consultation prénatale (CPN)', 'category': 'Maternité', 'price': 12000},
    {'name': 'Échographie obstétricale 1er trimestre', 'category': 'Maternité', 'price': 20000},
    {'name': 'Échographie obstétricale 2e trimestre', 'category': 'Maternité', 'price': 25000},
    {'name': 'Échographie obstétricale 3e trimestre', 'category': 'Maternité', 'price': 25000},
    {'name': 'Échographie 3D/4D', 'category': 'Maternité', 'price': 40000},
    {'name': 'Monitoring fœtal (NST)', 'category': 'Maternité', 'price': 10000},
    {'name': 'Accouchement voie basse normal', 'category': 'Maternité', 'price': 150000},
    {'name': 'Césarienne programmée', 'category': 'Maternité', 'price': 350000},
    {'name': 'Césarienne en urgence', 'category': 'Maternité', 'price': 400000},
    
    # IMAGERIE
    {'name': 'Échographie abdominale', 'category': 'Imagerie', 'price': 20000},
    {'name': 'Échographie pelvienne', 'category': 'Imagerie', 'price': 20000},
    {'name': 'Échographie mammaire', 'category': 'Imagerie', 'price': 25000},
    {'name': 'Échographie thyroïde', 'category': 'Imagerie', 'price': 18000},
    {'name': 'Radiographie standard (1 cliché)', 'category': 'Imagerie', 'price': 12000},
    {'name': 'Radiographie standard (2 clichés)', 'category': 'Imagerie', 'price': 18000},
    
    # EXPLORATIONS
    {'name': 'ECG (Électrocardiogramme)', 'category': 'Explorations', 'price': 8000},
    {'name': 'Épreuve d\'effort (ECG effort)', 'category': 'Explorations', 'price': 25000},
    {'name': 'Holter ECG 24h', 'category': 'Explorations', 'price': 40000},
    {'name': 'MAPA (Tension 24h)', 'category': 'Explorations', 'price': 35000},
    {'name': 'Spirométrie (EFR)', 'category': 'Explorations', 'price': 15000},
    
    # PETITE CHIRURGIE
    {'name': 'Incision abcès', 'category': 'Chirurgie', 'price': 15000},
    {'name': 'Exérèse verrue/lipome', 'category': 'Chirurgie', 'price': 20000},
    {'name': 'Circoncision (enfant)', 'category': 'Chirurgie', 'price': 50000},
    {'name': 'Circoncision (adulte)', 'category': 'Chirurgie', 'price': 75000},
    
    # VACCINATIONS
    {'name': 'Vaccin BCG', 'category': 'Vaccinations', 'price': 3500},
    {'name': 'Vaccin DTC-Polio-HepB-Hib (6 en 1)', 'category': 'Vaccinations', 'price': 8000},
    {'name': 'Vaccin ROR', 'category': 'Vaccinations', 'price': 12000},
    {'name': 'Vaccin Pneumocoque', 'category': 'Vaccinations', 'price': 15000},
    {'name': 'Vaccin Fièvre Jaune', 'category': 'Vaccinations', 'price': 10000},
    {'name': 'Vaccin Hépatite B (3 doses)', 'category': 'Vaccinations', 'price': 25000},
    {'name': 'Vaccin Grippe saisonnière', 'category': 'Vaccinations', 'price': 6000},
    
    # BILANS SANTÉ
    {'name': 'Bilan de santé complet', 'category': 'Bilans', 'price': 85000},
    {'name': 'Check-Up Standard', 'category': 'Bilans', 'price': 65000},
    {'name': 'Check-Up Premium', 'category': 'Bilans', 'price': 120000},
    {'name': 'Bilan Femme Complet', 'category': 'Bilans', 'price': 95000},
    {'name': 'Bilan Homme 40+', 'category': 'Bilans', 'price': 100000},
    
    # HOSPITALISATION (tarif journalier)
    {'name': 'Chambre commune (4-6 lits) par jour', 'category': 'Hospitalisation', 'price': 15000},
    {'name': 'Chambre double (2 lits) par jour', 'category': 'Hospitalisation', 'price': 25000},
    {'name': 'Chambre individuelle standard par jour', 'category': 'Hospitalisation', 'price': 40000},
    {'name': 'Chambre VIP par jour', 'category': 'Hospitalisation', 'price': 60000},
    {'name': 'Unité de soins intensifs (USI) par jour', 'category': 'Hospitalisation', 'price': 100000},
]

# Informations du centre
ORGANIZATION_INFO = {
    'name': 'Centre de Santé JULIANNA',
    'address': 'Entrée Marie Lumière, Makepe Saint-Tropez',
    'city': 'Douala',
    'country': 'Cameroun',
    'phone_orange': '+237 6XX XXX XXX',  # À compléter
    'phone_mtn': '+237 6XX XXX XXX',  # À compléter
    'email': 'contact@centreJULIANNA.com',
    'website': 'www.centreJULIANNA.com',
    'facebook': 'Centre de Santé JULIANNA',
    'subscription_type': 'strategic',
    'enabled_modules': [
        'dashboard',
        'healthcare_patients',
        'consultations',
        'laboratory',
        'pharmacy',
        'invoices',
        'analytics',
        'reports',
    ]
}
