"""
Configuration des analyses médicales pour le Centre de Santé JULIANNA
Tarifs officiels 2026 - Source: Liste Analyses Médicales CSJ version finale
B code : 1 point B = 200 FCFA
"""

# Catégories de tests
LAB_CATEGORIES = [
    {'name': 'Hématologie', 'slug': 'hematologie', 'order': 1},
    {'name': 'Biochimie Générale', 'slug': 'biochimie', 'order': 2},
    {'name': 'Ionogrammes', 'slug': 'ionogramme', 'order': 3},
    {'name': 'Sérologie', 'slug': 'serologie', 'order': 4},
    {'name': 'Bactériologie', 'slug': 'bacteriologie', 'order': 5},
    {'name': 'Parasitologie', 'slug': 'parasitologie', 'order': 6},
    {'name': 'Hormonologie', 'slug': 'hormonologie', 'order': 7},
    {'name': 'Électrophorèses', 'slug': 'electrophorese', 'order': 8},
]

# Codes des tests désactivés (non présents dans le catalogue officiel 2026)
DEACTIVATED_TEST_CODES = [
    'URO-CAU',         # Calcium urines (non au catalogue)
    'URO-CREAU',       # Créatinine urines (non au catalogue)
    'ION-CU',          # Ionogramme complet urines (non au catalogue)
    'URO-MGU',         # Magnésium urines (non au catalogue)
    'URO-PHU',         # Phosphore urines (non au catalogue)
    'URO-KU',          # Potassium urines (non au catalogue)
    'SERO-TESTG',      # Test grossesse urinaire (remplacé par HCG sérique)
    'BILAN-HTA-DIAB',  # Bilan HTA/Diabète (forfait retiré)
    'BILAN-PRENATAL',  # Bilan Prénatal (forfait retiré)
    'BACT-PUS-ATB',    # Pus + ATB (fusionné dans BACT-PUS)
    'BACT-HPYLORI',    # H. Pylori (non au catalogue)
]

# Catalogue complet des analyses médicales - Tarifs 2026
LAB_TESTS = [

    # ── BIOCHIMIE GÉNÉRALE ────────────────────────────────────────────────────
    {
        'code': 'BIO-AU',
        'name': 'ACIDE URIQUE',
        'short_name': 'Acide Urique',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_male': '3.5-7.2',
        'normal_female': '2.6-6.0',
        'normal_child': '2.0-5.5',
        'methodology': 'Méthode enzymatique uricase',
    },
    {
        'code': 'BIO-ALB',
        'name': 'ALBUMINE (Sérique)',
        'short_name': 'Albumine',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '2 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 3,
        'unit': 'g/L',
        'normal_general': '35-52',
        'normal_child': '32-48',
        'methodology': 'Vert de Bromocrésol',
    },
    {
        'code': 'URO-CHIM',
        'name': 'CHIMIE URINAIRE (Bandelette multi-paramètres)',
        'short_name': 'Chimie Urinaire',
        'category': 'biochimie',
        'price': 12000,
        'sample_type': 'urine',
        'container': 'urine_cup',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Qualitatif',
        'normal_general': 'pH 5-8, Densité 1.005-1.030, Leucocytes <10/µL, Nitrites Nég, Protéines Nég, Glucose Nég, Sang Nég',
        'methodology': 'Bandelette réactive multi-paramètres (Leucocytes, Nitrites, Urobilinogène, Protéines, pH, Sang, Densité, Corps cétoniques, Bilirubine, Glucose)',
    },
    {
        'code': 'BIO-BLIP',
        'name': 'BILAN LIPIDIQUE (Cholestérol total, HDL, LDL, Triglycérides)',
        'short_name': 'Bilan Lipidique',
        'category': 'biochimie',
        'price': 18000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 6,
        'unit': 'mg/dL',
        'normal_general': 'CT<200, HDL>40 (H)/>50 (F), LDL<130, TG<150',
        'methodology': 'Méthode enzymatique colorimétrique',
    },
    {
        'code': 'BIO-BILD',
        'name': 'BILIRUBINE DIRECTE',
        'short_name': 'Bili Directe',
        'category': 'biochimie',
        'price': 3000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '0-0.3',
        'normal_child': '0-0.2',
        'methodology': 'Méthode de Jendrassik-Grof',
    },
    {
        'code': 'BIO-BILT',
        'name': 'BILIRUBINE TOTALE',
        'short_name': 'Bili Totale',
        'category': 'biochimie',
        'price': 3000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '0.2-1.2',
        'normal_child': '0.1-1.0',
        'methodology': 'Méthode de Jendrassik-Grof',
    },
    {
        'code': 'BIO-CAS',
        'name': 'CALCIUM Ca++ (sérum)',
        'short_name': 'Calcium sérique',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '8.6-10.2',
        'normal_child': '8.8-10.8',
        'methodology': 'Méthode colorimétrique O-crésol',
    },
    {
        'code': 'BIO-CT',
        'name': 'CHOLESTÉROL TOTAL',
        'short_name': 'Cholest. Total',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<200',
        'methodology': 'CHOD-PAP enzymatique',
    },
    {
        'code': 'BIO-HDL',
        'name': 'CHOLESTÉROL HDL',
        'short_name': 'HDL',
        'category': 'biochimie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_male': '>40',
        'normal_female': '>50',
        'methodology': 'Précipitation sélective',
    },
    {
        'code': 'BIO-LDL',
        'name': 'CHOLESTÉROL LDL DOSAGE',
        'short_name': 'LDL',
        'category': 'biochimie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<130',
        'methodology': 'Formule de Friedewald ou dosage direct',
    },
    {
        'code': 'BIO-CREAS',
        'name': 'CRÉATININE (sérum)',
        'short_name': 'Créatinine',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mg/dL',
        'normal_male': '0.7-1.2',
        'normal_female': '0.5-0.9',
        'normal_child': '0.3-0.7',
        'methodology': 'Méthode de Jaffé',
    },
    {
        'code': 'BIO-CRP',
        'name': 'CRP (C Reactive Protein) - Réaction inflammatoire',
        'short_name': 'CRP',
        'category': 'biochimie',
        'price': 8000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/L',
        'normal_general': '<5',
        'methodology': 'Immunoturbidimétrie',
    },
    {
        'code': 'BIO-FER',
        'name': 'FER SÉRIQUE',
        'short_name': 'Fer',
        'category': 'biochimie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 4,
        'unit': 'µg/dL',
        'normal_male': '60-160',
        'normal_female': '50-170',
        'normal_child': '50-120',
        'methodology': 'Colorimétrique ferrozine',
    },
    {
        'code': 'BIO-GGT',
        'name': 'GAMMA GT (γGT)',
        'short_name': 'Gamma GT',
        'category': 'biochimie',
        'price': 5000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_male': '<55',
        'normal_female': '<38',
        'methodology': 'Cinétique IFCC',
    },
    {
        'code': 'BIO-PAL',
        'name': 'PAL (Phosphatase Alcaline)',
        'short_name': 'PAL',
        'category': 'biochimie',
        'price': 5000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_general': '30-120',
        'normal_child': '100-400',
        'methodology': 'pNPP IFCC',
    },
    {
        'code': 'BIO-GLU',
        'name': 'GLYCÉMIE À JEUN',
        'short_name': 'Glycémie',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'fluoride',
        'sample_volume': '2 ml',
        'fasting': True,
        'fasting_hours': 8,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '70-100',
        'normal_child': '60-100',
        'methodology': 'GOD-POD enzymatique',
    },
    {
        'code': 'BIO-GLUPP',
        'name': 'GLYCÉMIE POST PRANDIALE',
        'short_name': 'Glycémie PP',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'fluoride',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '<140 (2h après repas)',
        'methodology': 'GOD-POD enzymatique',
    },
    {
        'code': 'BIO-PROT',
        'name': 'PROTÉINES TOTALES',
        'short_name': 'Protéines',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'g/L',
        'normal_general': '60-80',
        'normal_child': '50-75',
        'methodology': 'Biuret',
    },
    {
        'code': 'BIO-TRANS',
        'name': 'SGOT/SGPT (TRANSAMINASES) ASAT/ALAT',
        'short_name': 'ASAT/ALAT',
        'category': 'biochimie',
        'price': 9000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'UI/L',
        'normal_male': 'ASAT<37, ALAT<41',
        'normal_female': 'ASAT<31, ALAT<31',
        'normal_child': 'ASAT<40, ALAT<35',
        'methodology': 'IFCC sans P5P',
    },
    {
        'code': 'BIO-TG',
        'name': 'TRIGLYCÉRIDES',
        'short_name': 'Triglycérides',
        'category': 'biochimie',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': True,
        'fasting_hours': 12,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '<150',
        'methodology': 'GPO-PAP enzymatique',
    },
    {
        'code': 'BIO-UREE',
        'name': 'URÉE',
        'short_name': 'Urée',
        'category': 'biochimie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mg/dL',
        'normal_general': '15-45',
        'normal_child': '10-35',
        'methodology': 'Uréase enzymatique',
    },

    # ── ÉLECTROPHORÈSES ───────────────────────────────────────────────────────
    {
        'code': 'HEM-ELPHB',
        'name': 'ÉLECTROPHORÈSE DE L\'HÉMOGLOBINE (EHB)',
        'short_name': 'Électrophorèse Hb',
        'category': 'hematologie',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': '%',
        'normal_general': 'HbA 95-98%, HbA2 2-3.5%, HbF <2%',
        'methodology': 'Électrophorèse capillaire ou HPLC',
    },
    {
        'code': 'BIO-ELPROT',
        'name': 'ÉLECTROPHORÈSE PROTÉINES',
        'short_name': 'Électrophorèse Prot.',
        'category': 'biochimie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'g/L',
        'normal_general': 'Albumine 35-52, α1 2-5, α2 5-11, β 8-14, γ 7-16 g/L',
        'methodology': 'Électrophorèse sur gel agarose',
    },

    # ── IONOGRAMMES ───────────────────────────────────────────────────────────
    {
        'code': 'ION-CS',
        'name': 'IONOGRAMME COMPLET (Na+, K+, Cl-, Ph, Mg++, Ca++) sérum',
        'short_name': 'Ionogramme Complet',
        'category': 'ionogramme',
        'price': 23000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mmol/L',
        'normal_general': 'Na 136-145, K 3.5-5.0, Cl 98-106, Ph 0.8-1.45, Mg 0.75-1.1, Ca 2.2-2.6 mmol/L',
        'methodology': 'Électrode sélective (ISE) + colorimétrique',
    },
    {
        'code': 'ION-SIMP',
        'name': 'IONOGRAMME SIMPLE (Na+, K+, Cl-)',
        'short_name': 'Iono Simple',
        'category': 'ionogramme',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mmol/L',
        'normal_general': 'Na 136-145, K 3.5-5.0, Cl 98-106 mmol/L',
        'methodology': 'Électrode sélective (ISE)',
    },
    {
        'code': 'BIO-MGS',
        'name': 'MAGNÉSIUM Mg++ (sérum)',
        'short_name': 'Mg sérique',
        'category': 'ionogramme',
        'price': 4000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'mg/dL',
        'normal_general': '1.6-2.6',
        'methodology': 'Colorimétrique Xylidyl Bleu',
    },
    {
        'code': 'BIO-PHS',
        'name': 'PHOSPHORE Ph (sérum)',
        'short_name': 'Phosphore',
        'category': 'ionogramme',
        'price': 3000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 3,
        'unit': 'mg/dL',
        'normal_general': '2.5-4.5',
        'normal_child': '4.0-7.0',
        'methodology': 'Molybdate UV',
    },
    {
        'code': 'ION-KS',
        'name': 'POTASSIUM K+ (sérum)',
        'short_name': 'Potassium',
        'category': 'ionogramme',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mmol/L',
        'normal_general': '3.5-5.0',
        'normal_child': '3.5-5.5',
        'methodology': 'Électrode sélective (ISE)',
    },
    {
        'code': 'ION-NA',
        'name': 'SODIUM Na+',
        'short_name': 'Sodium',
        'category': 'ionogramme',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mmol/L',
        'normal_general': '136-145',
        'normal_child': '135-145',
        'methodology': 'Électrode sélective (ISE)',
    },

    # ── HÉMATOLOGIE ───────────────────────────────────────────────────────────
    {
        'code': 'HEM-VS',
        'name': 'VITESSE DE SÉDIMENTATION',
        'short_name': 'VS',
        'category': 'hematologie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'mm/h',
        'normal_male': '<15 (1h), <20 (2h)',
        'normal_female': '<20 (1h), <30 (2h)',
        'normal_child': '<10',
        'methodology': 'Westergren',
    },
    {
        'code': 'HEM-G6PD',
        'name': 'G6PDH (G6PD)',
        'short_name': 'G6PD',
        'category': 'hematologie',
        'price': 10000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/g Hb',
        'normal_general': '7-20',
        'methodology': 'Méthode fluorométrique / colorimétrique',
    },
    {
        'code': 'HEM-GS',
        'name': 'GROUPE SANGUIN (ABO-RH) CARTE DE GROUPE',
        'short_name': 'Groupe Sanguin',
        'category': 'hematologie',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'Qualitatif',
        'normal_general': 'A, B, AB, O – Rh+ ou Rh-',
        'methodology': 'Agglutination sur carte ID-gel',
    },
    {
        'code': 'HEM-NFS',
        'name': 'NUMÉRATION FORMULE SANGUINE (NFS)',
        'short_name': 'NFS',
        'category': 'hematologie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': 'G/L',
        'normal_male': 'Hb 13-17 g/dL, Leuco 4-10 G/L, Plaq 150-400 G/L',
        'normal_female': 'Hb 12-16 g/dL, Leuco 4-10 G/L, Plaq 150-400 G/L',
        'normal_child': 'Hb 11-14 g/dL, Leuco 5-15 G/L',
        'methodology': 'Automate hématologie (impédancemétrie + cytométrie)',
    },
    {
        'code': 'HEM-RETIC',
        'name': 'TAUX DE RÉTICULOCYTES',
        'short_name': 'Réticulocytes',
        'category': 'hematologie',
        'price': 2000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': '%',
        'normal_general': '0.5-2.0',
        'normal_child': '0.5-3.0',
        'methodology': 'Coloration vital bleu de méthylène / automate',
    },
    {
        'code': 'HEM-TP',
        'name': 'TAUX DE PROTHROMBINE (TP) / TEMPS DE QUICK (TQ) & TCK & FIBRINOGÈNE',
        'short_name': 'TP/TQ/TCK/FIB',
        'category': 'hematologie',
        'price': 5000,
        'sample_type': 'blood',
        'container': 'citrate',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 2,
        'unit': '%',
        'normal_general': 'TP 70-100% (INR 0.8-1.2), TCK 25-35s, Fibrinogène 2-4 g/L',
        'methodology': 'Coagulométrie automatisée',
    },
    {
        'code': 'HEM-HBA1C',
        'name': 'HÉMOGLOBINE HbA1C (Hémoglobine glyquée)',
        'short_name': 'HbA1C',
        'category': 'hematologie',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': '%',
        'normal_general': '<5.7% (normal), 5.7-6.4% (prédiabète), ≥6.5% (diabète)',
        'methodology': 'HPLC (High Performance Liquid Chromatography)',
    },

    # ── SÉROLOGIE ─────────────────────────────────────────────────────────────
    {
        'code': 'SERO-ASLO',
        'name': 'ASLO (Antistreptolysines O)',
        'short_name': 'ASLO',
        'category': 'serologie',
        'price': 7000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': '<200 UI/mL',
        'methodology': 'Immunoturbidimétrie',
    },
    {
        'code': 'SERO-HEPA',
        'name': 'HÉPATITE A (IgM anti-HAV)',
        'short_name': 'HAV IgM',
        'category': 'serologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-HBS',
        'name': 'HÉPATITE B (Ag HBs)',
        'short_name': 'AgHBs',
        'category': 'serologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA / Test rapide',
    },
    {
        'code': 'SERO-HCV',
        'name': 'HÉPATITE C (Ac Anti-HCV)',
        'short_name': 'Anti-HCV',
        'category': 'serologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-HERPES',
        'name': 'HERPÈS (IgG, IgM)',
        'short_name': 'HSV IgG/IgM',
        'category': 'serologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'IgM: Négatif (infection active = positif), IgG: variable (immunité passée)',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-FR',
        'name': 'FACTEUR RHUMATOÏDE',
        'short_name': 'Fact. Rhum.',
        'category': 'serologie',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': '<14 UI/mL',
        'methodology': 'Immunoturbidimétrie',
    },
    {
        'code': 'SERO-SYPH',
        'name': 'SYPHILIS (TPHA - VDRL) - BW',
        'short_name': 'TPHA/VDRL',
        'category': 'serologie',
        'price': 8000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'TPHA: Négatif, VDRL: Négatif',
        'methodology': 'Agglutination (TPHA) + floculation (VDRL)',
    },
    {
        'code': 'SERO-HIV',
        'name': 'VIH 1 & VIH 2',
        'short_name': 'HIV 1&2',
        'category': 'serologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Test rapide 4ème génération + ELISA confirmateur',
    },
    {
        'code': 'SERO-TOXO',
        'name': 'TOXOPLASMOSE (IgG, IgM)',
        'short_name': 'Toxo IgG/IgM',
        'category': 'serologie',
        'price': 12000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': 'IgM: <6 UI/mL (négatif), IgG variable selon exposition',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-RUBEO',
        'name': 'RUBÉOLE (IgG, IgM)',
        'short_name': 'Rubéole IgG/IgM',
        'category': 'serologie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/mL',
        'normal_general': 'IgG > 10 UI/mL = Immunisé, IgM: Négatif (infection active = positif)',
        'methodology': 'ELISA',
    },
    {
        'code': 'SERO-CHLAM',
        'name': 'CHLAMYDIA TRACHOMATIS',
        'short_name': 'Chlamydia',
        'category': 'serologie',
        'price': 30000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'PCR en temps réel',
    },

    # ── BACTÉRIOLOGIE ─────────────────────────────────────────────────────────
    {
        'code': 'BACT-ECBU',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE DES URINES (ECBU)',
        'short_name': 'ECBU',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'urine',
        'container': 'other',
        'sample_volume': '10 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'UFC/mL',
        'normal_general': 'Leucocytes <10/µL, Bactéries <10³ UFC/mL',
        'methodology': 'Cytologie + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-GORGE',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Frottis de gorge',
        'short_name': 'Frottis gorge',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore résidente normale',
        'methodology': 'Culture + Antibiogramme',
    },
    {
        'code': 'BACT-PONCT',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Liquide de ponction',
        'short_name': 'Ponction',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'other',
        'container': 'other',
        'sample_volume': '5 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile',
        'methodology': 'Cytologie + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-PCV',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Cervico-vaginal (PCV)',
        'short_name': 'PCV',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore de Döderlein (Lactobacillus spp.)',
        'methodology': 'Examen direct + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-PUS',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Pus (aspiration / écouvillonnage)',
        'short_name': 'Pus',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'other',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile (variable selon localisation)',
        'methodology': 'Examen direct + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-NEZ',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Nez',
        'short_name': 'Frottis nez',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore résidente normale',
        'methodology': 'Culture + Antibiogramme',
    },
    {
        'code': 'BACT-URETH',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Urétral (PU)',
        'short_name': 'Frottis urétral',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile',
        'methodology': 'Examen direct + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-CUTANE',
        'name': 'EXAMEN CYTOBACTÉRIOLOGIQUE - Prélèvements cutanés',
        'short_name': 'Prélèv. cutanés',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage / grattage',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Flore résidente normale ou Stérile',
        'methodology': 'Examen direct + Culture + Antibiogramme',
    },
    {
        'code': 'BACT-GONOC',
        'name': 'GONOCOQUE (Recherche de Neisseria gonorrhoeae)',
        'short_name': 'Gonocoque',
        'category': 'bacteriologie',
        'price': 24000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage (PU ou PCV)',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'Culture spécifique (chocolat PolyvitX) + PCR',
    },
    {
        'code': 'BACT-HEMO',
        'name': 'HÉMOCULTURE',
        'short_name': 'Hémoculture',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'other',
        'sample_volume': '2-3 flacons sur 24h',
        'fasting': False,
        'turnaround': 48,
        'unit': 'Qualitatif',
        'normal_general': 'Stérile',
        'methodology': 'Culture sur flacons Bactec (aérobie + anaérobie)',
    },
    {
        'code': 'BACT-COPRO',
        'name': 'COPROCULTURE (Salmonelle, Shigelle, Campylobacter, E.Coli pathogène)',
        'short_name': 'Coproculture',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'stool',
        'container': 'stool_cup',
        'sample_volume': '5 g',
        'fasting': False,
        'turnaround': 72,
        'unit': 'Qualitatif',
        'normal_general': 'Flore intestinale normale, absence de germes pathogènes',
        'methodology': 'Culture sélective + Antibiogramme',
    },
    {
        'code': 'BACT-SPERMO',
        'name': 'SPERMOCULTURE',
        'short_name': 'Spermoculture',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'other',
        'container': 'other',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 48,
        'unit': 'UFC/mL',
        'normal_general': '<10³ UFC/mL',
        'methodology': 'Culture + Antibiogramme',
    },
    {
        'code': 'BACT-SPERMO-EXAM',
        'name': 'SPERMOGRAMME',
        'short_name': 'Spermogramme',
        'category': 'bacteriologie',
        'price': 14000,
        'sample_type': 'other',
        'container': 'other',
        'sample_volume': '2 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'millions/mL',
        'normal_general': 'Volume ≥1.5ml, Conc. ≥16M/mL, Mobilité prog. ≥30%, Formes normales ≥4%',
        'methodology': 'Microscopie optique OMS 2021',
    },
    {
        'code': 'BACT-MYCO',
        'name': 'MYCOPLASME (Prélèvement génital)',
        'short_name': 'Mycoplasme',
        'category': 'bacteriologie',
        'price': 72000,
        'sample_type': 'swab',
        'container': 'other',
        'sample_volume': 'Écouvillonnage génital',
        'fasting': False,
        'turnaround': 72,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif',
        'methodology': 'PCR + Culture (Mycoplasma hominis, Ureaplasma urealyticum)',
    },

    # ── PARASITOLOGIE ─────────────────────────────────────────────────────────
    {
        'code': 'PARA-PALU',
        'name': 'PALUDISME + Quantification (Goutte Épaisse)',
        'short_name': 'GE Paludisme',
        'category': 'parasitologie',
        'price': 5000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': 'Goutte de sang sur lame',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Parasites/µL',
        'normal_general': 'Absence de parasites',
        'methodology': 'Microscopie (Goutte Épaisse + Frottis colorés Giemsa)',
    },
    {
        'code': 'PARA-KAOP',
        'name': 'SELLES : KAOP (Kato + Direct)',
        'short_name': 'KAOP',
        'category': 'parasitologie',
        'price': 10000,
        'sample_type': 'stool',
        'container': 'stool_cup',
        'sample_volume': '5 g',
        'fasting': False,
        'turnaround': 24,
        'unit': 'Qualitatif',
        'normal_general': 'Absence de parasites et œufs de parasites',
        'methodology': 'Examen direct + Kato-Katz + Concentration',
    },

    # ── HORMONOLOGIE ─────────────────────────────────────────────────────────
    {
        'code': 'HORM-HCG',
        'name': 'HCG GROSSESSE (test rapide)',
        'short_name': 'HCG Rapide',
        'category': 'hormonologie',
        'price': 6000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 1,
        'unit': 'Qualitatif',
        'normal_general': 'Négatif (<5 UI/L) chez la femme non enceinte',
        'methodology': 'Test immunochromatographique rapide',
    },
    {
        'code': 'HORM-HCG-Q',
        'name': 'HCG GROSSESSE (automate hormone - dosage quantitatif)',
        'short_name': 'β-HCG Quantitatif',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_general': '<5 UI/L (non enceinte)',
        'normal_female': '1er trim: 1000-200000 UI/L, 2e trim: 2000-45000 UI/L',
        'methodology': 'Immunoluminescence (ECLIA) sur automate',
    },
    {
        'code': 'HORM-PSA',
        'name': 'PSA Total (Antigène Spécifique Prostatique)',
        'short_name': 'PSA Total',
        'category': 'hormonologie',
        'price': 14000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/mL',
        'normal_male': '<4.0 ng/mL (zone de surveillance 4-10, élevé >10)',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-PSAL',
        'name': 'PSA libre',
        'short_name': 'PSA libre',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/mL',
        'normal_male': 'Ratio PSA libre/total >20% = faible risque de cancer',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-TSH',
        'name': 'TSH (Thyréostimuline)',
        'short_name': 'TSH',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'mUI/L',
        'normal_general': '0.4-4.0 mUI/L',
        'normal_child': '0.7-5.7 mUI/L',
        'methodology': 'ELISA 3ème génération / Immunoluminescence',
    },
    {
        'code': 'HORM-T3',
        'name': 'T3 (Triiodothyronine)',
        'short_name': 'T3',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'pg/mL',
        'normal_general': '2.3-4.2 pg/mL (T3 libre) / 80-180 ng/dL (T3 totale)',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-T4',
        'name': 'T4 (Thyroxine)',
        'short_name': 'T4',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'serum',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/dL',
        'normal_general': '0.8-1.8 ng/dL (T4 libre) / 4.5-12.0 µg/dL (T4 totale)',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-OESTRO',
        'name': 'ŒSTROGÈNE (Estradiol E2)',
        'short_name': 'Estradiol E2',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'pg/mL',
        'normal_female': 'Folliculaire: 20-350, Ovulatoire: 150-750, Lutéale: 30-450, Post-ménopause: <20 pg/mL',
        'normal_male': '10-40 pg/mL',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-PROG',
        'name': 'PROGESTÉRONE',
        'short_name': 'Progestérone',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/mL',
        'normal_female': 'Folliculaire: <1, Lutéale: 1.5-28, Grossesse: 10-290 ng/mL',
        'normal_male': '0.2-1.4 ng/mL',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-TESTO',
        'name': 'TESTOSTÉRONE',
        'short_name': 'Testostérone',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'ng/dL',
        'normal_male': '250-830',
        'normal_female': '15-75',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-FSH',
        'name': 'FSH (Hormone Folliculo-Stimulante)',
        'short_name': 'FSH',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_female': 'Folliculaire: 3.5-12.5, Ovulatoire: 4.7-21.5, Post-ménopause: 25-135 UI/L',
        'normal_male': '1.5-12.4 UI/L',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-LH',
        'name': 'LH (Hormone Lutéinisante)',
        'short_name': 'LH',
        'category': 'hormonologie',
        'price': 20000,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 24,
        'unit': 'UI/L',
        'normal_female': 'Folliculaire: 2.4-12.6, Ovulatoire: 14-96, Lutéale: 1-11.4, Post-ménopause: 7.7-59 UI/L',
        'normal_male': '1.7-8.6 UI/L',
        'methodology': 'ELISA / Immunoluminescence',
    },
    {
        'code': 'HORM-PCT',
        'name': 'PROCALCITONINE (PCT)',
        'short_name': 'PCT',
        'category': 'hormonologie',
        'price': 49600,
        'sample_type': 'blood',
        'container': 'edta',
        'sample_volume': '3 ml',
        'fasting': False,
        'turnaround': 4,
        'unit': 'ng/mL',
        'normal_general': '<0.05 ng/mL (normal), 0.05-0.5 (légère), 0.5-2 (modérée), >2 (sévère/sepsis)',
        'methodology': 'Immunoturbidimétrie BRAHMS / ECLIA',
    },
]

# Services et Soins médicaux
MEDICAL_SERVICES = [
    # ── CONSULTATIONS ─────────────────────────────────────────────────────────
    {'code': 'CONS-INF',    'name': 'Consultation Infirmier',            'category': 'Consultations', 'price': 3000},
    {'code': 'CONS-MED',    'name': 'Consultation Médecin général',      'category': 'Consultations', 'price': 5000},

    # ── HOSPITALISATION ────────────────────────────────────
    {'code': 'HOSP-CATH',   'name': 'Pose de cathéter - Perfusion',      'category': 'Hospitalisation', 'price': 1000},
    {'code': 'HOSP-SOND',   'name': 'Pose de sonde urinaire',            'category': 'Hospitalisation', 'price': 1000},
    {'code': 'HOSP-DRAP',   'name': 'Drap pour lit',                     'category': 'Hospitalisation', 'price': 1000},
    {'code': 'HOSP-F2L',    'name': 'Forfait simple deux lits',          'category': 'Hospitalisation', 'price': 7500},
    {'code': 'HOSP-F2L-V',  'name': 'Forfait VIP deux lits',              'category': 'Hospitalisation', 'price': 7500},
    {'code': 'HOSP-MEO',    'name': 'Mise En Observation (MEO) - Soins', 'category': 'Hospitalisation', 'price': 1500},
    {'code': 'HOSP-CONC',   'name': 'Forfait concentrateur / Heure',     'category': 'Hospitalisation', 'price': 5000},
    {'code': 'HOSP-PONC-P', 'name': 'Ponction pleural',                  'category': 'Hospitalisation', 'price': 7500},
    {'code': 'HOSP-PONC-A', 'name': 'Ponction d\'ascite',                'category': 'Hospitalisation', 'price': 7500},
    {'code': 'HOSP-NEBU',   'name': 'Nebulisation',                      'category': 'Hospitalisation', 'price': 5000},

    # ── PETITE CHIRURGIE ──────────────────────────────────────────────────────
    {'code': 'CHIR-ONG',    'name': 'Ongle incarné',                     'category': 'Petite Chirurgie', 'price': 15000},
    {'code': 'CHIR-PAN-I',  'name': 'Incision et drainage panaris',      'category': 'Petite Chirurgie', 'price': 10000},
    {'code': 'CHIR-INF-C',  'name': 'Infiltration corticoïdes',          'category': 'Petite Chirurgie', 'price': 2500},
    {'code': 'CHIR-KYS',    'name': 'Kystectomie/Lipomectomie S-C',      'category': 'Petite Chirurgie', 'price': 5000},
    {'code': 'CHIR-CHEL',   'name': 'Petite cheloïdectomie',             'category': 'Petite Chirurgie', 'price': 5000},
    {'code': 'CHIR-PAN-S',  'name': 'Pansement simple',                  'category': 'Petite Chirurgie', 'price': 500},
    {'code': 'CHIR-SUT-5',  'name': 'Suture +5 points/trois plans',      'category': 'Petite Chirurgie', 'price': 12000},
    {'code': 'CHIR-SUT-1',  'name': 'Suture 1 à 3 points/un plan',       'category': 'Petite Chirurgie', 'price': 3000},
    {'code': 'CHIR-SUT-3',  'name': 'Suture 3 à 5 points/deux plans',     'category': 'Petite Chirurgie', 'price': 4000},
    {'code': 'CHIR-CE',     'name': 'Extraction corps étranger',         'category': 'Petite Chirurgie', 'price': 5000},
    {'code': 'CHIR-ABC-I',  'name': 'Incision + drainage Abcès',         'category': 'Petite Chirurgie', 'price': 15000},
    {'code': 'CHIR-CIRC',   'name': 'Circonsition',                      'category': 'Petite Chirurgie', 'price': 5000},
    {'code': 'CHIR-LIP-A',  'name': 'Ablation petite lipome',            'category': 'Petite Chirurgie', 'price': 10000},
    {'code': 'CHIR-INJ-S',  'name': 'Injection simple',                  'category': 'Petite Chirurgie', 'price': 500},
    {'code': 'CHIR-ORE',    'name': 'Lavage des oreilles',               'category': 'Petite Chirurgie', 'price': 5000},
    {'code': 'CHIR-FREIN',  'name': 'Ablation d\'un frein de langue',    'category': 'Petite Chirurgie', 'price': 1500},
    {'code': 'CHIR-PLAT',   'name': 'Attelle plâtrée/Plâtre',            'category': 'Petite Chirurgie', 'price': 7000},
    {'code': 'CHIR-ABC-C',  'name': 'Incision d\'Abcès complexe',        'category': 'Petite Chirurgie', 'price': 6000},
    {'code': 'CHIR-PAN-C',  'name': 'Pansement complexe',                'category': 'Petite Chirurgie', 'price': 2500},
    {'code': 'CHIR-ABC-S',  'name': 'Incision d\'Abcès simple',          'category': 'Petite Chirurgie', 'price': 3000},
    {'code': 'CHIR-LAV-P',  'name': 'Lavage plaies',                     'category': 'Petite Chirurgie', 'price': 3000},

    # ── ORL ───────────────────────────────────────────────────────────────────
    {'code': 'ORL-NAS',     'name': 'Lavage nasal',                      'category': 'ORL', 'price': 500},

    # ── KIT PRÉLÈVEMENT ───────────────────────────────────────────────────────
    {'code': 'KIT-PRELEV',  'name': 'Kit de prélèvement',                'category': 'Kit Prélèvement', 'price': 500},
]

# Informations du centre
ORGANIZATION_INFO = {
    'name': 'Centre de Santé JULIANNA',
    'address': 'Entrée Marie Lumière, Makepe Saint-Tropez',
    'city': 'Douala',
    'country': 'Cameroun',
    'phone_orange': '+237 6XX XXX XXX',  # À compléter
    'phone_mtn': '+237 6XX XXX XXX',  # À compléter
    'email': 'contact@centreJULIANNA.com',
    'website': 'www.centreJULIANNA.com',
    'facebook': 'Centre de Santé JULIANNA',
    'subscription_type': 'strategic',
    'enabled_modules': [
        'dashboard',
        'healthcare_patients',
        'consultations',
        'laboratory',
        'pharmacy',
        'invoices',
        'analytics',
        'reports',
    ]
}
