# Generated by Django 5.2.10 on 2026-05-06 11:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'admission")),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('admission_reason', models.TextField(blank=True, verbose_name="Motif d'hospitalisation")),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnostic')),
                ('treatment_during_stay', models.TextField(blank=True, verbose_name='Traitement reçu pendant le séjour')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='Résumé de sortie / Évolution')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Recommandations / Instructions')),
                ('prescribed_treatment_after', models.TextField(blank=True, verbose_name='Traitement de sortie (Ordonnance)')),
                ('next_appointment_date', models.DateField(blank=True, null=True, verbose_name='Date du prochain RDV de suivi')),
                ('status', models.CharField(choices=[('admitted', 'Admis'), ('discharged', 'Sorti'), ('transferred', 'Transféré')], default='admitted', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant / admission')),
                ('discharging_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharged_patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin autorisant la sortie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='accounts.client', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
                'ordering': ['-admission_date'],
            },
        ),
    ]
