# Generated by Django 4.2.11 on 2026-07-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de lit'),
        ),
    ]
