# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_address', models.TextField(blank=True, verbose_name='Adresse')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company_website', models.URLField(blank=True, verbose_name='Site web')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/', verbose_name='Logo')),
                ('tax_region', models.CharField(choices=[('cameroon', 'Cameroun (OHADA)'), ('ohada', 'OHADA (Afrique francophone)'), ('eu', 'Union Européenne'), ('usa', 'États-Unis'), ('canada', 'Canada'), ('international', 'International (champs universels)')], default='international', help_text='Détermine les champs obligatoires selon la législation locale', max_length=20, verbose_name='Région fiscale')),
                ('company_niu', models.CharField(blank=True, help_text='Obligatoire au Cameroun - Identifiant fiscal unique', max_length=50, verbose_name='NIU (Numéro Identifiant Unique)')),
                ('company_tax_number', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, verbose_name='Numéro de contribuable')),
                ('company_rc_number', models.CharField(blank=True, help_text="Numéro d'immatriculation au registre de commerce", max_length=50, verbose_name='Numéro de Registre de Commerce (RC)')),
                ('company_rccm_number', models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier (OHADA)', max_length=50, verbose_name='Numéro RCCM')),
                ('company_vat_number', models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire (si applicable)', max_length=50, verbose_name='Numéro de TVA')),
                ('company_gst_number', models.CharField(blank=True, help_text="Numéro d'inscription TPS/TVH (obligatoire au Canada si > 30 000$ CA/an)", max_length=50, verbose_name='Numéro TPS/TVH (GST/HST)')),
                ('company_qst_number', models.CharField(blank=True, help_text="Numéro d'inscription TVQ (obligatoire au Québec si > 30 000$ CA/an)", max_length=50, verbose_name='Numéro TVQ (QST)')),
                ('company_neq', models.CharField(blank=True, help_text="Numéro d'entreprise du Québec - Obligatoire pour les entreprises québécoises", max_length=50, verbose_name="NEQ (Numéro d'entreprise du Québec)")),
                ('company_bank_name', models.CharField(blank=True, help_text='Nom de la banque de domiciliation', max_length=200, verbose_name='Nom de la banque')),
                ('company_bank_account', models.CharField(blank=True, help_text='Numéro de compte ou IBAN', max_length=100, verbose_name='Numéro de compte bancaire')),
                ('company_bank_swift', models.CharField(blank=True, help_text="Code d'identification de la banque (transactions internationales)", max_length=20, verbose_name='Code SWIFT/BIC')),
                ('brand_color', models.CharField(default='#2563eb', help_text='Couleur utilisée dans les factures et documents (format: #RRGGBB)', max_length=7, verbose_name='Couleur principale de la marque')),
                ('auto_generate_lab_kits', models.BooleanField(default=False, help_text='Créer automatiquement un produit consommable pour chaque nouveau test de laboratoire', verbose_name='Génération automatique des kits labo')),
                ('default_tax_rate', models.DecimalField(decimal_places=3, default=15.0, max_digits=5, verbose_name='Taux de taxe par défaut (%)')),
                ('gst_hst_rate', models.DecimalField(decimal_places=3, default=5.0, max_digits=5, verbose_name='Taux TPS/TVH (%)')),
                ('qst_rate', models.DecimalField(decimal_places=3, default=9.975, max_digits=5, verbose_name='Taux TVQ (%)')),
                ('enable_tax_calculation', models.BooleanField(default=True, verbose_name='Activer le calcul automatique des taxes')),
                ('invoice_prefix', models.CharField(default='FAC-', max_length=20, verbose_name='Préfixe des factures')),
                ('po_prefix', models.CharField(default='BC-', max_length=20, verbose_name='Préfixe des bons de commande')),
                ('default_invoice_template', models.CharField(choices=[('standard', 'Standard'), ('modern', 'Moderne'), ('classic', 'Classique'), ('thermal', 'Thermique (Ticket)')], default='standard', help_text="Template utilisé par défaut pour l'impression des factures", max_length=50, verbose_name='Modèle de facture par défaut')),
                ('invoice_terms', models.CharField(blank=True, default='Net 30', max_length=100, verbose_name='Conditions de paiement par défaut')),
                ('default_currency', models.CharField(choices=[('CAD', 'CAD - Dollar canadien'), ('USD', 'USD - Dollar américain'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Livre sterling'), ('CHF', 'CHF - Franc suisse'), ('JPY', 'JPY - Yen japonais'), ('CNY', 'CNY - Yuan chinois'), ('AUD', 'AUD - Dollar australien'), ('NZD', 'NZD - Dollar néo-zélandais'), ('INR', 'INR - Roupie indienne'), ('BRL', 'BRL - Real brésilien'), ('MXN', 'MXN - Peso mexicain'), ('ZAR', 'ZAR - Rand sud-africain'), ('XOF', "XOF - Franc CFA (Afrique de l'Ouest)"), ('XAF', 'XAF - Franc CFA (Afrique centrale)'), ('MAD', 'MAD - Dirham marocain'), ('TND', 'TND - Dinar tunisien'), ('DZD', 'DZD - Dinar algérien'), ('NGN', 'NGN - Naira nigérian'), ('KES', 'KES - Shilling kényan'), ('GHS', 'GHS - Cedi ghanéen'), ('EGP', 'EGP - Livre égyptienne'), ('AED', 'AED - Dirham des Émirats'), ('SAR', 'SAR - Riyal saoudien'), ('QAR', 'QAR - Riyal qatari'), ('SEK', 'SEK - Couronne suédoise'), ('NOK', 'NOK - Couronne norvégienne'), ('DKK', 'DKK - Couronne danoise'), ('PLN', 'PLN - Zloty polonais'), ('CZK', 'CZK - Couronne tchèque'), ('HUF', 'HUF - Forint hongrois'), ('RON', 'RON - Leu roumain'), ('TRY', 'TRY - Livre turque'), ('RUB', 'RUB - Rouble russe'), ('SGD', 'SGD - Dollar de Singapour'), ('HKD', 'HKD - Dollar de Hong Kong'), ('KRW', 'KRW - Won sud-coréen'), ('THB', 'THB - Baht thaïlandais'), ('MYR', 'MYR - Ringgit malaisien'), ('IDR', 'IDR - Roupie indonésienne'), ('PHP', 'PHP - Peso philippin'), ('VND', 'VND - Dong vietnamien'), ('ILS', 'ILS - Shekel israélien'), ('CLP', 'CLP - Peso chilien'), ('ARS', 'ARS - Peso argentin'), ('COP', 'COP - Peso colombien'), ('PEN', 'PEN - Sol péruvien')], default='CAD', max_length=3, verbose_name='Devise par défaut')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('invoice_reminders', models.BooleanField(default=True, verbose_name='Rappels de factures')),
                ('low_stock_alerts', models.BooleanField(default=True, verbose_name='Alertes stock bas')),
                ('order_status_updates', models.BooleanField(default=True, verbose_name='Mises à jour statut commandes')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='Format de date')),
                ('time_format', models.CharField(choices=[('24h', '24 heures'), ('12h', '12 heures (AM/PM)')], default='24h', max_length=10, verbose_name="Format d'heure")),
                ('session_timeout', models.IntegerField(default=30, verbose_name="Délai d'expiration session (minutes)")),
                ('require_strong_passwords', models.BooleanField(default=True, verbose_name='Exiger mots de passe forts')),
                ('enable_two_factor', models.BooleanField(default=False, verbose_name='Authentification à deux facteurs')),
                ('login_attempts', models.IntegerField(default=5, verbose_name='Tentatives de connexion max')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('Letter', 'Letter (8.5 × 11 in)'), ('Legal', 'Legal (8.5 × 14 in)'), ('A5', 'A5 (148 × 210 mm)'), ('thermal_80', 'Thermique 80mm (Ticket de caisse)'), ('thermal_58', 'Thermique 58mm (Ticket de caisse)')], default='A4', max_length=20, verbose_name='Taille du papier')),
                ('paper_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', max_length=20, verbose_name='Orientation du papier')),
                ('print_margins', models.CharField(choices=[('narrow', 'Étroites'), ('normal', 'Normales'), ('wide', 'Larges')], default='normal', max_length=20, verbose_name='Marges')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='Inclure code QR')),
                ('print_colors', models.BooleanField(default=True, verbose_name='Impression couleur')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Toutes les heures'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20, verbose_name='Fréquence de sauvegarde')),
                ('backup_retention', models.IntegerField(default=30, verbose_name='Rétention sauvegardes (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Paramètres d'organisation",
                'verbose_name_plural': "Paramètres d'organisations",
            },
        ),
    ]
