# Generated by Django 5.0.3 on 2025-11-11 02:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_currency_and_language_preferences'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_address', models.TextField(blank=True, verbose_name='Adresse')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company_website', models.URLField(blank=True, verbose_name='Site web')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/', verbose_name='Logo')),
                ('default_tax_rate', models.DecimalField(decimal_places=3, default=15.0, max_digits=5, verbose_name='Taux de taxe par défaut (%)')),
                ('gst_hst_rate', models.DecimalField(decimal_places=3, default=5.0, max_digits=5, verbose_name='Taux TPS/TVH (%)')),
                ('qst_rate', models.DecimalField(decimal_places=3, default=9.975, max_digits=5, verbose_name='Taux TVQ (%)')),
                ('enable_tax_calculation', models.BooleanField(default=True, verbose_name='Activer le calcul automatique des taxes')),
                ('invoice_prefix', models.CharField(default='FAC-', max_length=20, verbose_name='Préfixe des factures')),
                ('po_prefix', models.CharField(default='BC-', max_length=20, verbose_name='Préfixe des bons de commande')),
                ('invoice_terms', models.CharField(blank=True, default='Net 30', max_length=100, verbose_name='Conditions de paiement par défaut')),
                ('default_currency', models.CharField(choices=[('CAD', 'CAD - Dollar canadien'), ('USD', 'USD - Dollar américain'), ('EUR', 'EUR - Euro')], default='CAD', max_length=3, verbose_name='Devise par défaut')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('invoice_reminders', models.BooleanField(default=True, verbose_name='Rappels de factures')),
                ('low_stock_alerts', models.BooleanField(default=True, verbose_name='Alertes stock bas')),
                ('order_status_updates', models.BooleanField(default=True, verbose_name='Mises à jour statut commandes')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='Format de date')),
                ('time_format', models.CharField(choices=[('24h', '24 heures'), ('12h', '12 heures (AM/PM)')], default='24h', max_length=10, verbose_name="Format d'heure")),
                ('session_timeout', models.IntegerField(default=30, verbose_name="Délai d'expiration session (minutes)")),
                ('require_strong_passwords', models.BooleanField(default=True, verbose_name='Exiger mots de passe forts')),
                ('enable_two_factor', models.BooleanField(default=False, verbose_name='Authentification à deux facteurs')),
                ('login_attempts', models.IntegerField(default=5, verbose_name='Tentatives de connexion max')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=20, verbose_name='Taille du papier')),
                ('print_margins', models.CharField(choices=[('narrow', 'Étroites'), ('normal', 'Normales'), ('wide', 'Larges')], default='normal', max_length=20, verbose_name='Marges')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='Inclure code QR')),
                ('print_colors', models.BooleanField(default=True, verbose_name='Impression couleur')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Toutes les heures'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20, verbose_name='Fréquence de sauvegarde')),
                ('backup_retention', models.IntegerField(default=30, verbose_name='Rétention sauvegardes (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Paramètres d'organisation",
                'verbose_name_plural': "Paramètres d'organisations",
            },
        ),
    ]
