# Generated by Django 5.2.10 on 2026-03-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Taux de taxe par défaut (%)'),
        ),
    ]
