# Generated by Django 4.2.11 on 2026-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organizationsettings_default_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='privilege_card_consultation_discount_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Réduction carte privilège — Consultation (%)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='privilege_card_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer la carte privilège'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='privilege_card_imaging_discount_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Réduction carte privilège — Imagerie (%)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='privilege_card_laboratory_discount_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Réduction carte privilège — Laboratoire (%)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='privilege_card_pharmacy_discount_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Réduction carte privilège — Pharmacie (%)'),
        ),
    ]
