# Generated by Django 5.0.3 on 2025-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='brand_color',
            field=models.CharField(default='#2563eb', help_text='Couleur utilisée dans les factures et documents (format: #RRGGBB)', max_length=7, verbose_name='Couleur principale de la marque'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='default_currency',
            field=models.CharField(choices=[('CAD', 'CAD - Dollar canadien'), ('USD', 'USD - Dollar américain'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Livre sterling'), ('CHF', 'CHF - Franc suisse'), ('JPY', 'JPY - Yen japonais'), ('CNY', 'CNY - Yuan chinois'), ('AUD', 'AUD - Dollar australien'), ('NZD', 'NZD - Dollar néo-zélandais'), ('INR', 'INR - Roupie indienne'), ('BRL', 'BRL - Real brésilien'), ('MXN', 'MXN - Peso mexicain'), ('ZAR', 'ZAR - Rand sud-africain'), ('XOF', "XOF - Franc CFA (Afrique de l'Ouest)"), ('XAF', 'XAF - Franc CFA (Afrique centrale)'), ('MAD', 'MAD - Dirham marocain'), ('TND', 'TND - Dinar tunisien'), ('DZD', 'DZD - Dinar algérien'), ('NGN', 'NGN - Naira nigérian'), ('KES', 'KES - Shilling kényan'), ('GHS', 'GHS - Cedi ghanéen'), ('EGP', 'EGP - Livre égyptienne'), ('AED', 'AED - Dirham des Émirats'), ('SAR', 'SAR - Riyal saoudien'), ('QAR', 'QAR - Riyal qatari'), ('SEK', 'SEK - Couronne suédoise'), ('NOK', 'NOK - Couronne norvégienne'), ('DKK', 'DKK - Couronne danoise'), ('PLN', 'PLN - Zloty polonais'), ('CZK', 'CZK - Couronne tchèque'), ('HUF', 'HUF - Forint hongrois'), ('RON', 'RON - Leu roumain'), ('TRY', 'TRY - Livre turque'), ('RUB', 'RUB - Rouble russe'), ('SGD', 'SGD - Dollar de Singapour'), ('HKD', 'HKD - Dollar de Hong Kong'), ('KRW', 'KRW - Won sud-coréen'), ('THB', 'THB - Baht thaïlandais'), ('MYR', 'MYR - Ringgit malaisien'), ('IDR', 'IDR - Roupie indonésienne'), ('PHP', 'PHP - Peso philippin'), ('VND', 'VND - Dong vietnamien'), ('ILS', 'ILS - Shekel israélien'), ('CLP', 'CLP - Peso chilien'), ('ARS', 'ARS - Peso argentin'), ('COP', 'COP - Peso colombien'), ('PEN', 'PEN - Sol péruvien')], default='CAD', max_length=3, verbose_name='Devise par défaut'),
        ),
    ]
