# Generated by Django 5.0.3 on 2025-12-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationsettings_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='paper_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', max_length=20, verbose_name='Orientation du papier'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('Letter', 'Letter (8.5 × 11 in)'), ('Legal', 'Legal (8.5 × 14 in)'), ('A5', 'A5 (148 × 210 mm)'), ('thermal_80', 'Thermique 80mm (Ticket de caisse)'), ('thermal_58', 'Thermique 58mm (Ticket de caisse)')], default='A4', max_length=20, verbose_name='Taille du papier'),
        ),
    ]
