# Generated by Django 4.2.11 on 2026-09-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationsettings_privilege_card_consultation_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='stock_barcode_enabled',
            field=models.BooleanField(default=False, help_text="Impression d'etiquettes produit/lot et recherche par scan", verbose_name='Codes-barres / QR sur le stock'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='stock_inventory_enabled',
            field=models.BooleanField(default=False, help_text='Mode comptage : saisie du stock reel compte, ecarts et ajustement trace', verbose_name='Inventaire physique'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='stock_reception_enabled',
            field=models.BooleanField(default=False, help_text='Ecran de reception : quantites recues, n° de lot et peremption en une fois', verbose_name='Reception de marchandise'),
        ),
    ]
