# Generated by Django 5.0.3 on 2025-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_paper_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='company_bank_account',
            field=models.CharField(blank=True, help_text='Numéro de compte ou IBAN', max_length=100, verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_bank_name',
            field=models.CharField(blank=True, help_text='Nom de la banque de domiciliation', max_length=200, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_bank_swift',
            field=models.CharField(blank=True, help_text="Code d'identification de la banque (transactions internationales)", max_length=20, verbose_name='Code SWIFT/BIC'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_niu',
            field=models.CharField(blank=True, help_text='Obligatoire au Cameroun - Identifiant fiscal unique', max_length=50, verbose_name='NIU (Numéro Identifiant Unique)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_rc_number',
            field=models.CharField(blank=True, help_text="Numéro d'immatriculation au registre de commerce", max_length=50, verbose_name='Numéro de Registre de Commerce (RC)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_rccm_number',
            field=models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier (OHADA)', max_length=50, verbose_name='Numéro RCCM'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_tax_number',
            field=models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, verbose_name='Numéro de contribuable'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_vat_number',
            field=models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire (si applicable)', max_length=50, verbose_name='Numéro de TVA'),
        ),
    ]
