# Generated by Django 5.0.3 on 2025-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organizationsettings_company_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='tax_region',
            field=models.CharField(choices=[('cameroon', 'Cameroun (OHADA)'), ('ohada', 'OHADA (Afrique francophone)'), ('eu', 'Union Européenne'), ('usa', 'États-Unis'), ('canada', 'Canada'), ('international', 'International (champs universels)')], default='international', help_text='Détermine les champs obligatoires selon la législation locale', max_length=20, verbose_name='Région fiscale'),
        ),
    ]
