# Generated by Django 5.0.3 on 2025-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizationsettings_tax_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='company_gst_number',
            field=models.CharField(blank=True, help_text="Numéro d'inscription TPS/TVH (obligatoire au Canada si > 30 000$ CA/an)", max_length=50, verbose_name='Numéro TPS/TVH (GST/HST)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_neq',
            field=models.CharField(blank=True, help_text="Numéro d'entreprise du Québec - Obligatoire pour les entreprises québécoises", max_length=50, verbose_name="NEQ (Numéro d'entreprise du Québec)"),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_qst_number',
            field=models.CharField(blank=True, help_text="Numéro d'inscription TVQ (obligatoire au Québec si > 30 000$ CA/an)", max_length=50, verbose_name='Numéro TVQ (QST)'),
        ),
    ]
