# Generated by Django 4.2.11 on 2026-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationsettings_company_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='auto_generate_lab_kits',
            field=models.BooleanField(default=False, help_text='Créer automatiquement un produit consommable pour chaque nouveau test de laboratoire', verbose_name='Génération automatique des kits labo'),
        ),
    ]
