# Generated by Django 5.2.10 on 2026-03-24 20:15

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationsettings_company_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.organization_logo_upload, verbose_name='Logo'),
        ),
    ]
