# Generated by Django 5.2.10 on 2026-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organizationsettings_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='auto_reminders_enabled',
            field=models.BooleanField(default=False, verbose_name="Relances automatiques d'impayés activées"),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='reminder_delay_1',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Délai avant 1ère relance (jours après échéance)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='reminder_delay_2',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Délai avant 2ème relance (jours après échéance)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='reminder_delay_3',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Délai avant 3ème relance (jours après échéance)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='reminder_max_count',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Nombre maximum de relances automatiques'),
        ),
    ]
