# Generated by Django 5.2.10 on 2026-02-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizationsettings_auto_generate_lab_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='default_invoice_template',
            field=models.CharField(choices=[('standard', 'Standard'), ('modern', 'Moderne'), ('classic', 'Classique'), ('thermal', 'Thermique (Ticket)')], default='standard', help_text="Template utilisé par défaut pour l'impression des factures", max_length=50, verbose_name='Modèle de facture par défaut'),
        ),
    ]
