# Generated by Django 5.2.10 on 2026-03-23 06:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_client_marital_profession_antecedents'),
        ('invoicing', '0007_add_healthcare_services_invoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Numéro de compte')),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux Propres'), ('revenue', 'Produit'), ('expense', 'Charge')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_system', models.BooleanField(default=False, help_text='Compte prédéfini, non supprimable', verbose_name='Compte système')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.organization', verbose_name='Organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Plan Comptable',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AccountingJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('journal_type', models.CharField(choices=[('sales', 'Journal des Ventes'), ('purchases', 'Journal des Achats'), ('cash', 'Journal de Caisse'), ('bank', 'Journal de Banque'), ('misc', 'Opérations Diverses')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_journals', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=50, verbose_name="Numéro d'écriture")),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=300, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('posted', 'Validée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('invoice', 'Facture'), ('payment', 'Paiement'), ('purchase_order', 'Bon de commande')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries_created', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.accountingjournal', verbose_name='Journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.organization')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='invoicing.invoice', verbose_name='Facture source')),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='invoicing.payment', verbose_name='Paiement source')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account', verbose_name='Compte')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['created_at'],
            },
        ),
    ]
