# Generated by Django 5.2.10 on 2026-03-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('invoice', 'Facture'), ('invoice_reversal', 'Extourne facture'), ('payment', 'Paiement'), ('purchase_order', 'Bon de commande')], default='manual', max_length=20),
        ),
    ]
