# Generated by Django 5.2.10 on 2026-07-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_journalentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('invoice', 'Facture'), ('invoice_reversal', 'Extourne facture'), ('credit_note', 'Avoir'), ('payment', 'Paiement'), ('purchase_order', 'Bon de commande')], default='manual', max_length=20),
        ),
    ]
