# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True, verbose_name='Code du plan')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix mensuel (€)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix annuel (€)')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('max_invoices_per_month', models.IntegerField(blank=True, null=True, verbose_name='Factures max/mois')),
                ('max_clients', models.IntegerField(blank=True, null=True, verbose_name='Clients maximum')),
                ('max_products', models.IntegerField(blank=True, null=True, verbose_name='Produits maximum')),
                ('max_purchase_orders_per_month', models.IntegerField(blank=True, null=True, verbose_name='Bons de commande max/mois')),
                ('max_suppliers', models.IntegerField(blank=True, null=True, verbose_name='Fournisseurs maximum')),
                ('max_storage_mb', models.IntegerField(blank=True, null=True, verbose_name='Stockage max (MB)')),
                ('max_ai_requests_per_month', models.IntegerField(blank=True, null=True, verbose_name='Requêtes IA max/mois')),
                ('has_ads', models.BooleanField(default=False, verbose_name='Afficher publicités')),
                ('has_ai_assistant', models.BooleanField(default=False, verbose_name='Assistant IA')),
                ('has_purchase_orders', models.BooleanField(default=False, verbose_name='Bons de commande')),
                ('has_suppliers', models.BooleanField(default=False, verbose_name='Fournisseurs')),
                ('has_e_sourcing', models.BooleanField(default=False, verbose_name='E-Sourcing')),
                ('has_contracts', models.BooleanField(default=False, verbose_name='Contrats')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Analytics avancés')),
                ('trial_days', models.IntegerField(default=0, verbose_name="Jours d'essai gratuit")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', "Période d'essai"), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=20, verbose_name='Statut')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10, verbose_name='Période de facturation')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name="Fin de la période d'essai")),
                ('current_period_start', models.DateTimeField(verbose_name='Début période actuelle')),
                ('current_period_end', models.DateTimeField(verbose_name='Fin période actuelle')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('credit_card', 'Carte de crédit'), ('bank_transfer', 'Virement bancaire'), ('manual', 'Manuel (admin)')], default='paypal', max_length=50, verbose_name='Méthode de paiement')),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='ID abonnement PayPal')),
                ('invoices_this_month', models.IntegerField(default=0, verbose_name='Factures ce mois')),
                ('purchase_orders_this_month', models.IntegerField(default=0, verbose_name='BC ce mois')),
                ('ai_requests_this_month', models.IntegerField(default=0, verbose_name='Requêtes IA ce mois')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization', verbose_name='Organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Méthode de paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID de transaction')),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, verbose_name='ID commande PayPal')),
                ('period_start', models.DateTimeField(verbose_name='Début de période couverte')),
                ('period_end', models.DateTimeField(verbose_name='Fin de période couverte')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
