# Generated by Django 5.2.10 on 2026-05-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID actuel'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID mensuel'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID annuel'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('credit_card', 'Carte de crédit'), ('bank_transfer', 'Virement bancaire'), ('manual', 'Manuel (admin)')], default='stripe', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de période couverte'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de période couverte'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('success', 'Réussi (legacy)'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('free', 'Libre'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True, verbose_name='Code du plan'),
        ),
    ]
