# Generated by Django 5.2.10 on 2026-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_accounting',
            field=models.BooleanField(default=False, verbose_name='Comptabilité'),
        ),
    ]
