# Generated by Django 5.2.10 on 2026-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_has_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='extra_user_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Prix par utilisateur supplémentaire'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_users',
            field=models.IntegerField(default=1, verbose_name='Utilisateurs inclus'),
        ),
    ]
