# Generated by Django 5.2.10 on 2026-06-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_user_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='extra_seats',
            field=models.IntegerField(default=0, verbose_name='Sièges supplémentaires payés'),
        ),
    ]
