# Generated by Django 5.2.10 on 2026-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_add_extra_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_seat_price_id_monthly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID siège mensuel'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_seat_price_id_yearly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID siège annuel'),
        ),
    ]
