# Generated by Django 5.2.10 on 2026-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_seat_price_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_reminder_1d_sent',
            field=models.BooleanField(default=False, verbose_name='Relance essai J-1 envoyée'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_reminder_7d_sent',
            field=models.BooleanField(default=False, verbose_name='Relance essai J-7 envoyée'),
        ),
    ]
