# Generated by Django 5.2.10 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_trial_reminder_1d_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien facture PDF (Stripe)'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_hosted_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien page facture (Stripe)'),
        ),
    ]
