# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro consultation')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('vitals_pending', 'Paramètres à prendre'), ('ready_for_doctor', 'Prêt pour médecin'), ('in_consultation', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=20, verbose_name='Statut')),
                ('queue_position', models.IntegerField(blank=True, help_text="Position dans la file d'attente", null=True, verbose_name='Position dans la file')),
                ('vitals_taken_at', models.DateTimeField(blank=True, help_text='Heure à laquelle les paramètres vitaux ont été pris', null=True, verbose_name='Paramètres pris à')),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de consultation')),
                ('started_at', models.DateTimeField(blank=True, help_text='Heure à laquelle la consultation a commencé', null=True, verbose_name='Heure de début')),
                ('ended_at', models.DateTimeField(blank=True, help_text="Heure à laquelle la consultation s'est terminée", null=True, verbose_name='Heure de fin')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de consultation')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='Tension artérielle (systolique)')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Tension artérielle (diastolique)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie (mg/dL)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='Saturation O2 (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('chief_complaint', models.TextField(blank=True, help_text='Raison principale de la visite', verbose_name='Motif de consultation')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='Histoire de la maladie actuelle')),
                ('physical_examination', models.TextField(blank=True, help_text="Résultats de l'examen clinique", verbose_name='Examen physique')),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnostic principal et différentiels', verbose_name='Diagnostic')),
                ('diagnosis_codes', models.JSONField(blank=True, default=list, help_text='Codes ICD-10 ou autres', verbose_name='Codes diagnostiques')),
                ('treatment_plan', models.TextField(blank=True, help_text='Traitement prescrit et recommandations', verbose_name='Plan de traitement')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Suivi requis')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Date de suivi')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Instructions de suivi')),
                ('private_notes', models.TextField(blank=True, help_text='Notes réservées au personnel médical', verbose_name='Notes privées')),
                ('patient_instructions', models.TextField(blank=True, help_text='Instructions à remettre au patient', verbose_name='Instructions au patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'ordonnance")),
                ('prescribed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de prescription')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partially_filled', 'Partiellement dispensée'), ('filled', 'Dispensée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text='Informations supplémentaires pour le pharmacien', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(blank=True, help_text="Utilisé si le médicament n'est pas dans l'inventaire", max_length=200, verbose_name='Nom du médicament')),
                ('is_external_medication', models.BooleanField(default=False, help_text="Si True, le médicament n'est pas disponible dans l'inventaire", verbose_name='Médicament externe')),
                ('dosage', models.CharField(help_text='Ex: 500mg, 1 comprimé, 5ml', max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(help_text='Ex: 3 fois par jour, matin et soir, toutes les 8h', max_length=100, verbose_name='Fréquence')),
                ('duration', models.CharField(blank=True, help_text="Ex: 7 jours, 2 semaines, jusqu'à amélioration", max_length=100, verbose_name='Durée')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intraveineuse (IV)'), ('im', 'Intramusculaire (IM)'), ('sc', 'Sous-cutanée (SC)'), ('topical', 'Topique'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('ophthalmic', 'Ophtalmique'), ('otic', 'Auriculaire'), ('nasal', 'Nasal'), ('other', 'Autre')], default='oral', max_length=20, verbose_name="Voie d'administration")),
                ('quantity_prescribed', models.IntegerField(help_text="Nombre total d'unités prescrites", verbose_name='Quantité prescrite')),
                ('quantity_dispensed', models.IntegerField(default=0, verbose_name='Quantité dispensée')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Dispensé')),
                ('instructions', models.TextField(blank=True, help_text='Instructions supplémentaires (ex: prendre avec repas)', verbose_name='Instructions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Item d'ordonnance",
                'verbose_name_plural': "Items d'ordonnance",
                'ordering': ['medication__name'],
            },
        ),
    ]
