# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('pharmacy', '0001_initial'),
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_dispensing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacy.pharmacydispensing', verbose_name='Dispensation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescripteur'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='patients.patientvisit', verbose_name='Visite'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['organization', '-prescribed_date'], name='consultatio_organiz_6652aa_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='consultatio_patient_a51fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='consultatio_status_49f832_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['organization', '-consultation_date'], name='consultatio_organiz_39b5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', '-consultation_date'], name='consultatio_patient_fd44e8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor'], name='consultatio_doctor__6ce364_idx'),
        ),
    ]
