# Generated by Django 4.2.11 on 2026-01-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_warehouse_is_default_and_more'),
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='invoicing.invoice', verbose_name='Facture consultation'),
        ),
    ]
