# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('consultations', '0002_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='lab_orders',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='laboratory.laborder', verbose_name="Prescriptions d'examens"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.client', verbose_name='Patient'),
        ),
    ]
