# Generated by Django 5.2.10 on 2026-01-20 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_add_consultation_invoice'),
        ('invoicing', '0025_add_multi_unit_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='is_external_medication',
            field=models.BooleanField(default=False, help_text="Si True, le médicament n'est pas disponible dans l'inventaire", verbose_name='Médicament externe'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='invoicing.product', verbose_name='Médicament'),
        ),
    ]
