# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('consultations', '0003_initial'),
        ('invoicing', '0002_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='patients.patientvisit', verbose_name='Visite'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitals_taken_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['nurse', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_taken_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Paramètres pris par'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation', verbose_name='Consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_dispensing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacy.pharmacydispensing', verbose_name='Dispensation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescripteur'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='invoicing.product', verbose_name='Médicament'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.prescription', verbose_name='Ordonnance'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['organization', '-consultation_date'], name='consultatio_organiz_39b5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', '-consultation_date'], name='consultatio_patient_fd44e8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor'], name='consultatio_doctor__6ce364_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['organization', '-prescribed_date'], name='consultatio_organiz_6652aa_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='consultatio_patient_a51fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='consultatio_status_49f832_idx'),
        ),
    ]
