# Generated by Django 4.2.11 on 2026-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_add_external_medication_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de consultation'),
        ),
    ]
