# Generated by Django 5.2.10 on 2026-02-22 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_initial'),
        ('laboratory', '0003_laborder_discount_laborder_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='antecedents_family',
            field=models.TextField(blank=True, verbose_name='Antécédents familiaux'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents_gyneco_obs',
            field=models.TextField(blank=True, verbose_name='Antécédents gynéco-obstétrique'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents_immuno_allergies',
            field=models.TextField(blank=True, verbose_name='Antécédents immuno-allergies'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents_lifestyle',
            field=models.TextField(blank=True, verbose_name='Mode de vie (Toxicologie/alcool)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents_medical',
            field=models.TextField(blank=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents_surgical',
            field=models.TextField(blank=True, verbose_name='Antécédents chirurgicaux'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='complementary_exams',
            field=models.TextField(blank=True, verbose_name='Examens complémentaires (morphologiques & biologiques)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Terminé par'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='enquetes_systeme',
            field=models.TextField(blank=True, verbose_name='Enquêtes & système'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='imaging',
            field=models.TextField(blank=True, verbose_name='Imagerie'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescribed_lab_tests',
            field=models.ManyToManyField(blank=True, related_name='consultation_prescriptions', to='laboratory.labtest', verbose_name='Examens prescrits (Indicatif)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='lab_orders',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='laboratory.laborder', verbose_name='Commandes de laboratoire (Générées)'),
        ),
    ]
