# Generated by Django 5.2.10 on 2026-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_antecedents_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, help_text='Ex: 500mg, 1 comprimé, 5ml', max_length=100, verbose_name='Dosage'),
        ),
    ]
