# Generated by Django 5.2.10 on 2026-02-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie (mg/dL)'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescripteur'),
        ),
    ]
