# Generated by Django 4.2.11 on 2026-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imagingorder_linked_lab_order_imagingorderitem_panel_and_more'),
        ('consultations', '0006_prescriptionitem_dosage_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescribed_imaging_exam_types',
            field=models.ManyToManyField(blank=True, related_name='consultation_prescriptions', to='imaging.imagingexamtype', verbose_name="Examens d'imagerie prescrits (Indicatif)"),
        ),
    ]
