# Generated by Django 5.2.10 on 2026-02-07 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultation_created_by_prescription_created_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='queue_position',
            field=models.IntegerField(blank=True, help_text="Position dans la file d'attente", null=True, verbose_name='Position dans la file'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente'), ('vitals_pending', 'Paramètres à prendre'), ('ready_for_doctor', 'Prêt pour médecin'), ('in_consultation', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitals_taken_at',
            field=models.DateTimeField(blank=True, help_text='Heure à laquelle les paramètres vitaux ont été pris', null=True, verbose_name='Paramètres pris à'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitals_taken_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['nurse', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_taken_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Paramètres pris par'),
        ),
    ]
