# Generated by Django 5.2.10 on 2026-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_consultation_queue_position_consultation_status_and_more'),
        ('laboratory', '0005_laborder_total_price_laborderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='lab_orders',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='laboratory.laborder', verbose_name="Prescriptions d'examens"),
        ),
    ]
