# Generated by Django 4.2.11 on 2026-08-01 22:31

import apps.imaging.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_rename_patients_followup_pat_date_idx_patients_pa_patient_179b52_idx_and_more'),
        ('invoicing', '0014_alter_invoice_invoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0026_add_item_sample_collection'),
        ('accounts', '0003_add_lab_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingExamCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_exam_categories', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Catégorie d'examen d'imagerie",
                'verbose_name_plural': "Catégories d'examen d'imagerie",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_code', models.CharField(blank=True, max_length=50, verbose_name='Code examen')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Nom court')),
                ('modality', models.CharField(choices=[('xray', 'Radio'), ('ultrasound', 'Échographie'), ('ct', 'Scanner'), ('mri', 'IRM'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Modalité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réduction')),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée estimée (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_types', to='imaging.imagingexamcategory', verbose_name='Catégorie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_exam_types', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Type d'examen d'imagerie",
                'verbose_name_plural': "Types d'examen d'imagerie",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('status', models.CharField(choices=[('prescribed', 'Prescrit'), ('in_progress', 'En cours'), ('results_ready', 'Résultats prêts'), ('results_delivered', 'Résultats remis'), ('cancelled', 'Annulé')], default='prescribed', max_length=30, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immédiat)')], default='routine', max_length=20, verbose_name='Priorité')),
                ('clinical_notes', models.TextField(blank=True, help_text='Indication clinique pour le radiologue/technicien', verbose_name='Notes cliniques')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Réduction totale')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('card', 'Carte Bancaire'), ('insurance', 'Assurance'), ('other', 'Autre')], default='cash', max_length=50, verbose_name='Méthode de paiement')),
                ('results_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Résultats terminés à')),
                ('results_delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Résultats remis à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imaging_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='invoicing.invoice', verbose_name='Facture imagerie')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_imaging_exams', to=settings.AUTH_USER_MODEL, verbose_name='Prescrit par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='accounts.client', verbose_name='Patient')),
                ('prescriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='laboratory.prescriber', verbose_name='Prescripteur externe')),
                ('results_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_imaging_results', to=settings.AUTH_USER_MODEL, verbose_name='Résultats saisis par')),
                ('subcontractor', models.ForeignKey(blank=True, help_text="Si renseigné, l'examen est sous-traité à ce partenaire", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='laboratory.subcontractorlab', verbose_name='Sous-traitant')),
                ('subcontractor_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='laboratory.subcontractorpatient', verbose_name='Patient sous-traitant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='patients.patientvisit', verbose_name='Visite associée')),
            ],
            options={
                'verbose_name': "Commande d'imagerie",
                'verbose_name_plural': "Commandes d'imagerie",
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réduction')),
                ('report_text', models.TextField(blank=True, help_text='Rapport du radiologue/technicien : constatations et conclusion', verbose_name='Compte-rendu')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_urgent_finding', models.BooleanField(default=False, help_text='À signaler en priorité au médecin traitant', verbose_name='Découverte urgente')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examen réalisé à')),
                ('report_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='Rapport saisi à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='imaging.imagingexamtype', verbose_name='Examen')),
                ('imaging_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imaging.imagingorder', verbose_name='Commande')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_imaging_exams', to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
                ('report_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_imaging_exams', to=settings.AUTH_USER_MODEL, verbose_name='Rapport saisi par')),
            ],
            options={
                'verbose_name': "Examen d'imagerie (commande)",
                'verbose_name_plural': "Examens d'imagerie (commande)",
                'ordering': ['exam_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingResultFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.imaging.models.imaging_result_file_upload_path, verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10, verbose_name='Type de fichier')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_files', to='imaging.imagingorderitem', verbose_name='Examen')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_imaging_files', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': "Fichier de résultat d'imagerie",
                'verbose_name_plural': "Fichiers de résultat d'imagerie",
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['organization', '-order_date'], name='imaging_ima_organiz_682429_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['patient'], name='imaging_ima_patient_9e3d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['status'], name='imaging_ima_status_14d5d5_idx'),
        ),
    ]
