# Generated by Django 4.2.11 on 2026-08-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0026_add_item_sample_collection'),
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingorder',
            name='linked_lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_imaging_orders', to='laboratory.laborder', verbose_name='Commande labo liée'),
        ),
        migrations.AddField(
            model_name='imagingorderitem',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_order_items', to='laboratory.labtestpanel', verbose_name='Bilan'),
        ),
        migrations.AddField(
            model_name='imagingorderitem',
            name='panel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix du bilan (part imagerie)'),
        ),
    ]
