# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de fournisseur',
                'verbose_name_plural': 'Catégories de fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('province', models.CharField(blank=True, choices=[('QC', 'Québec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britannique'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('NS', 'Nouvelle-Écosse'), ('NB', 'Nouveau-Brunswick'), ('NL', 'Terre-Neuve-et-Labrador'), ('PE', 'Île-du-Prince-Édouard'), ('NT', 'Territoires du Nord-Ouest'), ('YT', 'Yukon'), ('NU', 'Nunavut')], max_length=2, verbose_name='Province')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('inactive', 'Inactif'), ('blocked', 'Bloqué')], default='pending', max_length=20, verbose_name='Statut')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Note')),
                ('is_local', models.BooleanField(default=False, verbose_name='Fournisseur local')),
                ('is_minority_owned', models.BooleanField(default=False, verbose_name='Propriété minoritaire')),
                ('is_woman_owned', models.BooleanField(default=False, verbose_name='Propriété féminine')),
                ('is_indigenous', models.BooleanField(default=False, verbose_name='Entreprise autochtone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('auto_inactive_since', models.DateTimeField(blank=True, null=True, verbose_name='Inactif automatiquement depuis')),
                ('is_manually_active', models.BooleanField(default=False, help_text='Si True, le statut est géré manuellement et ne sera pas modifié automatiquement', verbose_name='Statut manuel')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.organization', verbose_name='Organisation')),
                ('categories', models.ManyToManyField(blank=True, to='suppliers.suppliercategory', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_reference', models.CharField(blank=True, help_text='Référence ou SKU utilisé par le fournisseur pour ce produit', max_length=100, verbose_name='Référence chez le fournisseur')),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat chez ce fournisseur (peut différer du cost_price du produit)", max_digits=10, null=True, verbose_name='Prix chez ce fournisseur')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Délai moyen de livraison pour ce produit par ce fournisseur', verbose_name='Délai de livraison (jours)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Marquer ce fournisseur comme préféré pour ce produit', verbose_name='Fournisseur préféré')),
                ('is_active', models.BooleanField(default=True, verbose_name='Association active')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette relation fournisseur-produit', verbose_name='Notes')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name="Dernière date d'achat")),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Dernier prix d'achat")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='invoicing.product', verbose_name='Produit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit Fournisseur',
                'verbose_name_plural': 'Produits Fournisseurs',
                'ordering': ['-is_preferred', 'supplier__name'],
                'indexes': [models.Index(fields=['supplier', 'product'], name='suppliers_s_supplie_ae870f_idx'), models.Index(fields=['supplier', 'is_preferred'], name='suppliers_s_supplie_fe7518_idx'), models.Index(fields=['product', 'is_preferred'], name='suppliers_s_product_dc087b_idx')],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
