# Generated by Django 5.0.3 on 2025-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_supplier_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de fournisseur',
                'verbose_name_plural': 'Catégories de fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(blank=True, to='suppliers.suppliercategory', verbose_name='Catégories'),
        ),
    ]
