# Generated by Django 5.0.3 on 2025-10-23 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_add_product_type_validation'),
        ('suppliers', '0003_suppliercategory_supplier_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_reference', models.CharField(blank=True, help_text='Référence ou SKU utilisé par le fournisseur pour ce produit', max_length=100, verbose_name='Référence chez le fournisseur')),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat chez ce fournisseur (peut différer du cost_price du produit)", max_digits=10, null=True, verbose_name='Prix chez ce fournisseur')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Délai moyen de livraison pour ce produit par ce fournisseur', verbose_name='Délai de livraison (jours)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Marquer ce fournisseur comme préféré pour ce produit', verbose_name='Fournisseur préféré')),
                ('is_active', models.BooleanField(default=True, verbose_name='Association active')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette relation fournisseur-produit', verbose_name='Notes')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name="Dernière date d'achat")),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Dernier prix d'achat")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='invoicing.product', verbose_name='Produit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit Fournisseur',
                'verbose_name_plural': 'Produits Fournisseurs',
                'ordering': ['-is_preferred', 'supplier__name'],
                'indexes': [models.Index(fields=['supplier', 'product'], name='suppliers_s_supplie_ae870f_idx'), models.Index(fields=['supplier', 'is_preferred'], name='suppliers_s_supplie_fe7518_idx'), models.Index(fields=['product', 'is_preferred'], name='suppliers_s_product_dc087b_idx')],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
