# Generated by Django 5.0.3 on 2025-12-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_currency_and_language_preferences'),
        ('suppliers', '0004_create_supplier_product_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
