# Generated by Django 4.2.11 on 2026-07-19 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0006_prescriptionitem_dosage_optional'),
        ('accounts', '0003_add_lab_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('referral', 'Fiche de référence médicale'), ('rest_note', 'Fiche de repos médical'), ('nursing_care', 'Fiche de soins infirmiers'), ('referral_counter_referral', 'Fiche de référence et contre-référence')], max_length=30, verbose_name='Type de document')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de délivrance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('referred_to', models.CharField(blank=True, max_length=255, verbose_name='Structure / médecin destinataire')),
                ('referral_reason', models.TextField(blank=True, verbose_name='Motif de référence')),
                ('clinical_summary', models.TextField(blank=True, verbose_name='Résumé clinique')),
                ('exams_done', models.TextField(blank=True, verbose_name='Examens déjà réalisés')),
                ('provisional_diagnosis', models.TextField(blank=True, verbose_name='Diagnostic présomptif')),
                ('counter_referral_diagnosis', models.TextField(blank=True, verbose_name='Diagnostic retenu')),
                ('counter_referral_treatment', models.TextField(blank=True, verbose_name='Traitement donné')),
                ('counter_referral_recommendations', models.TextField(blank=True, verbose_name='Recommandations de suivi')),
                ('rest_start_date', models.DateField(blank=True, null=True, verbose_name='Début du repos')),
                ('rest_end_date', models.DateField(blank=True, null=True, verbose_name='Fin du repos')),
                ('rest_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jours')),
                ('rest_reason', models.CharField(blank=True, max_length=255, verbose_name='Motif du repos')),
                ('care_acts', models.TextField(blank=True, verbose_name='Soins effectués')),
                ('vital_signs', models.TextField(blank=True, verbose_name='Constantes (TA, T°, pouls…)')),
                ('next_care_date', models.DateField(blank=True, null=True, verbose_name='Prochain soin prévu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='consultations.consultation', verbose_name='Consultation liée')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Délivré par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='accounts.client', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
