# Generated by Django 4.2.11 on 2026-10-01 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_userpermissions_module_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=150, verbose_name='Nom (sans fiche)')),
                ('person_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone (sans fiche)')),
                ('kind', models.CharField(choices=[('passage', 'Passage'), ('note', 'Note')], default='passage', max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('information', 'Renseignement'), ('appointment', 'Rendez-vous'), ('results', 'Résultats ou documents'), ('payment', 'Règlement'), ('medication', 'Médicaments'), ('complaint', 'Réclamation'), ('other', 'Autre')], max_length=20)),
                ('text', models.TextField(blank=True, verbose_name='Détail')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du passage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_interactions', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_interactions', to='accounts.client', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Interaction patient',
                'verbose_name_plural': 'Interactions patients',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='crm_patient_organiz_37d460_idx'), models.Index(fields=['patient', '-occurred_at'], name='crm_patient_patient_9c0540_idx')],
            },
        ),
    ]
