# Generated by Django 4.2.11 on 2026-10-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userpermissions_module_permissions'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('label', models.CharField(max_length=80, verbose_name='Libellé')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_origins', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Provenance',
                'verbose_name_plural': 'Provenances',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PatientCRMProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='Précision')),
                ('unknown', models.BooleanField(default=False, verbose_name='Provenance inconnue')),
                ('do_not_contact', models.BooleanField(default=False, verbose_name='Ne plus relancer')),
                ('filled_by', models.CharField(default='manual', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profiles', to='accounts.organization', verbose_name='Organisation')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='crm.patientorigin', verbose_name='Provenance')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to='accounts.client', verbose_name='Patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Profil CRM patient',
                'verbose_name_plural': 'Profils CRM patients',
            },
        ),
    ]
