# Generated by Django 4.2.11 on 2026-10-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpermissions_module_permissions'),
        ('crm', '0002_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('recipients', models.TextField(blank=True, help_text='Adresses séparées par une virgule')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text="Jour d'envoi (1 à 28)")),
                ('last_sent_for', models.DateField(blank=True, help_text='Premier jour du dernier mois envoyé', null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_report_schedule', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Envoi mensuel du rapport patients financiers',
            },
        ),
    ]
