# Generated by Django 4.2.11 on 2026-10-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_product_tests_per_unit_product_untracked_tests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userpermissions_module_permissions'),
        ('crm', '0003_monthly_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80, verbose_name='Libellé')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Mots-clés (facture)')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_reasons', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Motif de contact',
                'verbose_name_plural': 'Motifs de contact',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCRMInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upsold', models.BooleanField(default=False, verbose_name='Montée en gamme')),
                ('came_for', models.CharField(blank=True, max_length=200, verbose_name='Venu pour')),
                ('planned_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_info', to='invoicing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_invoice_infos', to='accounts.organization', verbose_name='Organisation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_invoice_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info CRM de facture',
                'verbose_name_plural': 'Infos CRM de factures',
            },
        ),
        migrations.CreateModel(
            name='CRMCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('kind', models.CharField(choices=[('door_to_door', 'Porte-à-porte'), ('social', 'Facebook / réseaux sociaux'), ('onsite', 'Dépistage / soins sur place'), ('flyers', 'Affiches / flyers'), ('partner', 'Partenariat'), ('other', 'Autre')], default='other', max_length=20)),
                ('zone', models.CharField(blank=True, max_length=120, verbose_name='Quartier / zone')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_campaigns', to='accounts.organization', verbose_name='Organisation')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.contactreason', verbose_name='Motif')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-is_active', '-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='patientcrmprofile',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='crm.crmcampaign', verbose_name='Campagne'),
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Appel'), ('visit', 'Visite'), ('other', 'Autre')], default='whatsapp', max_length=10)),
                ('outcome', models.CharField(choices=[('sent', 'Contacté, sans réponse précise'), ('agreed', "D'accord pour venir"), ('callback', 'À rappeler'), ('no_answer', 'Pas de réponse'), ('declined', 'Pas intéressé')], default='sent', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('came_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoicing.invoice')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.crmcampaign', verbose_name='Campagne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contact_logs', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='accounts.client', verbose_name='Patient')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.contactreason', verbose_name='Motif')),
            ],
            options={
                'verbose_name': 'Relance',
                'verbose_name_plural': 'Relances',
                'ordering': ['-contacted_at'],
                'indexes': [models.Index(fields=['organization', '-contacted_at'], name='crm_contact_organiz_8aa74f_idx'), models.Index(fields=['patient', '-contacted_at'], name='crm_contact_patient_0321f3_idx')],
            },
        ),
    ]
