# Generated by Django 4.2.11 on 2026-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_relances_campagnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='contactreason',
            name='message_template',
            field=models.TextField(blank=True, verbose_name='Message proposé'),
        ),
    ]
