# Generated by Django 4.2.11 on 2026-10-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpermissions_module_permissions'),
        ('crm', '0005_modeles_et_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecrminfo',
            name='revisit_date',
            field=models.DateField(blank=True, null=True, verbose_name='À revoir le'),
        ),
        migrations.AddField(
            model_name='patientcrmprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=80, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='patientcrmprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_referrals', to='accounts.client', verbose_name='Envoyé par'),
        ),
        migrations.AddField(
            model_name='patientinteraction',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price', 'Trop cher'), ('stock', 'Produit ou examen indisponible'), ('wait', 'Attente trop longue'), ('doctor', 'Médecin absent'), ('other', 'Autre raison')], max_length=10, verbose_name='Reparti sans acheter'),
        ),
    ]
