# Generated by Django 4.2.11 on 2026-10-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_quartier_parrain_controle_perte'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcrmprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Fiche créée par'),
        ),
    ]
