# Generated by Django 5.0.3 on 2025-09-19 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='special_conditions',
            field=models.TextField(blank=True, verbose_name='Conditions spéciales'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_reference',
            field=models.CharField(default='REF-001', max_length=100, verbose_name='Référence produit'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Spécifications'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_of_measure',
            field=models.CharField(default='unité', max_length=20, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
    ]
