# Generated by Django 5.0.3 on 2025-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité reçue'),
        ),
    ]
