# Generated by Django 5.0.3 on 2025-10-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_invoiceitem_product_product_organization_and_more'),
        ('purchase_orders', '0003_purchaseorderitem_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='invoicing.product', verbose_name='Produit'),
        ),
    ]
