# Generated by Django 5.2.10 on 2026-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date requise'),
        ),
    ]
