# Generated by Django 5.2.10 on 2026-04-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_make_required_date_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence produit'),
        ),
    ]
