# Generated by Django 5.2.10 on 2026-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_make_product_reference_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True, verbose_name='Analyse IA (JSON)'),
        ),
    ]
