# Generated by Django 4.2.11 on 2026-08-17 15:58

import apps.support.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_client_has_privilege_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('module', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('suppliers', 'Fournisseurs'), ('purchase-orders', "Commandes d'achat"), ('invoices', 'Factures'), ('products', 'Produits'), ('clients', 'Clients'), ('e-sourcing', 'E-sourcing'), ('contracts', 'Contrats'), ('analytics', 'Analytique'), ('patients', 'Patients'), ('consultations', 'Consultations'), ('laboratory', 'Laboratoire'), ('imaging', 'Imagerie'), ('pharmacy', 'Pharmacie'), ('ai-assistant', 'Assistant IA'), ('integrations', 'Intégrations'), ('data-migration', 'Migration de données'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Module')),
                ('category', models.CharField(choices=[('bug', 'Bug / erreur'), ('facturation', 'Erreur de facturation'), ('lenteur', 'Lenteur'), ('affichage', "Problème d'affichage"), ('donnee_manquante', 'Donnée manquante ou incorrecte'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute')], default='normal', max_length=10, verbose_name='Priorité')),
                ('admin_response', models.TextField(blank=True, verbose_name='Réponse')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Page concernée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.organization', verbose_name='Organisation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.support.models.support_ticket_attachment_upload_path, verbose_name="Capture d'écran")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Pièce jointe ticket',
                'verbose_name_plural': 'Pièces jointes ticket',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
