# Generated by Django 5.0.3 on 2025-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoiceitem'),
    ]

    operations = [
    ]
