# Generated by Django 5.2.10 on 2026-02-08 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoicing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='holding_cost_percent',
            field=models.DecimalField(decimal_places=2, default=20, help_text="Pourcentage du coût d'achat pour le stockage annuel", max_digits=5, verbose_name="Coût de stockage (% du prix d'achat/an)"),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering_cost',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Coût fixe par commande passée', max_digits=10, verbose_name='Coût de passation de commande (XAF)'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot fournisseur')),
                ('quantity', models.IntegerField(verbose_name='Quantité initiale')),
                ('quantity_remaining', models.IntegerField(verbose_name='Quantité restante')),
                ('expiry_date', models.DateField(verbose_name='Date de péremption')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('shelf_life_after_opening_days', models.PositiveIntegerField(blank=True, help_text='Ex: 14 jours pour réactifs', null=True, verbose_name='Durée de vie après ouverture (jours)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('opened', 'Ouvert'), ('expired', 'Périmé'), ('depleted', 'Épuisé')], default='available', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='accounts.organization', verbose_name='Organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='invoicing.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Lot de produit',
                'verbose_name_plural': 'Lots de produits',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='invoicing.productbatch', verbose_name='Lot'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'status'], name='invoicing_p_product_5fc0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['organization', 'expiry_date'], name='invoicing_p_organiz_360987_idx'),
        ),
    ]
