# Generated by Django 5.0.3 on 2025-09-19 15:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20250919_1631'),
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Configuration par défaut', max_length=200, verbose_name='Nom de la configuration')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('LETTER', 'Letter (8.5 × 11 in)'), ('LEGAL', 'Legal (8.5 × 14 in)')], default='A4', max_length=10, verbose_name='Taille du papier')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', max_length=10, verbose_name='Orientation')),
                ('margin_top', models.PositiveIntegerField(default=20, verbose_name='Marge haute (mm)')),
                ('margin_bottom', models.PositiveIntegerField(default=20, verbose_name='Marge basse (mm)')),
                ('margin_left', models.PositiveIntegerField(default=20, verbose_name='Marge gauche (mm)')),
                ('margin_right', models.PositiveIntegerField(default=20, verbose_name='Marge droite (mm)')),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans')], default='Arial', max_length=50, verbose_name='Police')),
                ('font_size_normal', models.PositiveIntegerField(default=10, verbose_name='Taille police normale')),
                ('font_size_small', models.PositiveIntegerField(default=8, verbose_name='Taille police petite')),
                ('font_size_large', models.PositiveIntegerField(default=14, verbose_name='Taille police grande')),
                ('invoice_number_prefix', models.CharField(default='FAC-', max_length=10, verbose_name='Préfixe facture')),
                ('po_number_prefix', models.CharField(default='BC-', max_length=10, verbose_name='Préfixe bon de commande')),
                ('include_duplicate_watermark', models.BooleanField(default=False, verbose_name='Filigrane duplicata')),
                ('include_page_numbers', models.BooleanField(default=True, verbose_name='Numéros de page')),
                ('include_total_pages', models.BooleanField(default=True, verbose_name='Total des pages')),
                ('is_default', models.BooleanField(default=False, verbose_name='Configuration par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Configuration d'impression",
                'verbose_name_plural': "Configurations d'impression",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande')], max_length=20, verbose_name='Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='print_templates/logos/', verbose_name='Logo')),
                ('header_company_name', models.CharField(default='ProcureGenius', max_length=200, verbose_name="Nom de l'entreprise")),
                ('header_address', models.TextField(default='', verbose_name='Adresse')),
                ('header_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('header_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('header_website', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Texte du pied de page')),
                ('footer_conditions', models.TextField(blank=True, default='', verbose_name='Conditions générales')),
                ('primary_color', models.CharField(default='#0066cc', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#00d4ff', max_length=7, verbose_name='Couleur secondaire')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Couleur du texte')),
                ('show_qr_code', models.BooleanField(default=True, verbose_name='Afficher le QR code')),
                ('qr_code_position', models.CharField(choices=[('top-right', 'En haut à droite'), ('bottom-right', 'En bas à droite'), ('bottom-left', 'En bas à gauche')], default='bottom-right', max_length=20, verbose_name='Position du QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'impression",
                'verbose_name_plural': "Templates d'impression",
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Adresse de facturation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='CAD', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(default='Net 30', max_length=100, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorder', verbose_name='Bon de commande associé'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='detailed_description',
            field=models.TextField(blank=True, default='', verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Référence produit'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_of_measure',
            field=models.CharField(default='unité', max_length=20, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.CreateModel(
            name='PrintHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande')], max_length=20, verbose_name='Type de document')),
                ('document_id', models.UUIDField(verbose_name='ID du document')),
                ('document_number', models.CharField(max_length=100, verbose_name='Numéro du document')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'impression")),
                ('print_format', models.CharField(default='PDF', max_length=20, verbose_name="Format d'impression")),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('configuration_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.printconfiguration', verbose_name='Configuration utilisée')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('template_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.printtemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': "Historique d'impression",
                'verbose_name_plural': "Historiques d'impression",
                'ordering': ['-printed_at'],
            },
        ),
    ]
