# Generated by Django 5.2.10 on 2026-02-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_add_batch_wilson_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_shelf_life_after_opening',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre de jours de validité après ouverture d'un flacon/lot. Ex: 14 jours pour un réactif.", null=True, verbose_name='Durée de vie après ouverture (jours)'),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_lead_time_days',
            field=models.PositiveIntegerField(default=7, help_text='Temps moyen entre la commande et la réception du produit', verbose_name='Délai de livraison (jours)'),
        ),
    ]
