# Generated by Django 5.0.3 on 2025-09-20 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_printconfiguration_printtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code-barres')),
                ('product_type', models.CharField(choices=[('physical', 'Produit physique'), ('service', 'Service'), ('digital', 'Produit numérique')], default='physical', max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de revient')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='Seuil de stock bas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
    ]
