# Generated by Django 5.2.10 on 2026-02-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_add_supply_lead_time_and_shelf_life_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique pour la traçabilité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoicing.productbatch', verbose_name='Lot / Batch'),
        ),
    ]
