# Generated by Django 5.0.3 on 2025-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code-barres'),
        ),
    ]
