# Generated by Django 5.2.10 on 2026-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoiceitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant remise'),
        ),
    ]
