# Generated by Django 5.0.3 on 2025-10-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_alter_product_barcode'),
        ('suppliers', '0003_suppliercategory_supplier_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_type',
            field=models.CharField(choices=[('purchased', 'Acheté (fournisseur)'), ('manufactured', 'Fabriqué (maison)'), ('resale', 'Revente')], default='purchased', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente'),
        ),
    ]
