# Generated by Django 5.2.10 on 2026-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoiceitem_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Vente de produits'), ('healthcare_consultation', 'Consultation médicale'), ('healthcare_laboratory', 'Laboratoire'), ('healthcare_pharmacy', 'Pharmacie / Médicaments'), ('healthcare_services', 'Soins / Petite chirurgie / Hospitalisation'), ('credit_note', 'Avoir - Note de crédit')], default='standard', max_length=30, verbose_name='Type de facture'),
        ),
    ]
