# Generated by Django 5.0.3 on 2025-10-08 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_product_source_type_product_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('reception', 'Réception (Bon de commande)'), ('sale', 'Vente (Facture)'), ('adjustment', 'Ajustement manuel'), ('return', 'Retour'), ('initial', 'Stock initial')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('quantity_before', models.IntegerField(verbose_name='Quantité avant')),
                ('quantity_after', models.IntegerField(verbose_name='Quantité après')),
                ('reference_type', models.CharField(blank=True, choices=[('purchase_order', 'Bon de commande'), ('invoice', 'Facture'), ('manual', 'Manuel')], max_length=20, null=True, verbose_name='Type de référence')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='ID de référence')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='invoicing.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='invoicing_s_product_b35fc4_idx'), models.Index(fields=['reference_type', 'reference_id'], name='invoicing_s_referen_4a5914_idx')],
            },
        ),
    ]
