# Generated by Django 5.2.10 on 2026-04-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_add_healthcare_services_invoice_type'),
        ('laboratory', '0015_add_age_to_subcontractor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_subcontractor_invoice',
            field=models.BooleanField(default=False, help_text='Indique que cette facture correspond à un dépôt de sous-traitance groupé', verbose_name='Facture sous-traitance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subcontractor',
            field=models.ForeignKey(blank=True, help_text="Laboratoire sous-traitant à l'origine de cette facture batch", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='laboratory.subcontractorlab', verbose_name='Laboratoire sous-traitant'),
        ),
    ]
