# Generated by Django 5.0.3 on 2025-10-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='loss_description',
            field=models.TextField(blank=True, verbose_name='Description détaillée de la perte'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Produit endommagé'), ('expired', 'Produit périmé'), ('stolen', 'Vol'), ('lost', 'Perte/Égarement'), ('quality_issue', 'Problème de qualité'), ('other', 'Autre raison')], max_length=20, null=True, verbose_name='Raison de la perte'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='loss_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur de la perte'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('reception', 'Réception (Bon de commande)'), ('sale', 'Vente (Facture)'), ('adjustment', 'Ajustement manuel'), ('return', 'Retour'), ('loss', 'Perte/Casse/Vol'), ('initial', 'Stock initial')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('purchase_order', 'Bon de commande'), ('invoice', 'Facture'), ('manual', 'Manuel'), ('loss_report', 'Rapport de perte')], max_length=20, null=True, verbose_name='Type de référence'),
        ),
    ]
