# Generated by Django 5.2.10 on 2026-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_global_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operating_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour les services/soins : coût de revient (charges, salaires, amortissement…)', max_digits=10, null=True, verbose_name='Coût de fonctionnement'),
        ),
    ]
