# Generated by Django 5.0.3 on 2025-10-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251012_0341'),
        ('invoicing', '0010_add_product_category_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Produit facturé (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoicing.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoicing.warehouse', verbose_name='Entrepôt principal'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_reference',
            field=models.CharField(blank=True, default='', help_text='Référence manuelle si produit non lié', max_length=100, verbose_name='Référence produit'),
        ),
    ]
