# Generated by Django 5.2.10 on 2026-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_exempt',
            field=models.BooleanField(default=False, help_text="Si activé, aucune remise (coupon, remise globale) ne s'applique à ce service. Uniquement pour la Consultation médicale.", verbose_name='Insensible aux réductions'),
        ),
    ]
