# Generated by Django 5.0.3 on 2025-10-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_organization_client_payment_terms'),
        ('invoicing', '0011_invoiceitem_product_product_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.client', verbose_name='Client'),
        ),
    ]
