# Generated by Django 4.2.11 on 2026-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_add_discount_exempt_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Comptant'), ('mobile_money', 'Mobile Money'), ('check', 'Chèque'), ('credit_card', 'Carte de crédit'), ('bank_transfer', 'Virement bancaire'), ('paypal', 'PayPal'), ('other', 'Autre')], default='bank_transfer', max_length=50, verbose_name='Mode de paiement'),
        ),
    ]
