# Generated by Django 5.0.3 on 2025-10-12 14:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_payment_terms_if_missing'),
        ('invoicing', '0013_product_organization_alter_invoice_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('cash', 'Comptant'), ('check', 'Chèque'), ('credit_card', 'Carte de crédit'), ('bank_transfer', 'Virement bancaire'), ('paypal', 'PayPal'), ('other', 'Autre')], default='bank_transfer', max_length=50, verbose_name='Mode de paiement')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice', 'payment_date'], name='invoicing_p_invoice_dff618_idx'), models.Index(fields=['payment_method'], name='invoicing_p_payment_39f572_idx')],
            },
        ),
    ]
