# Generated by Django 5.0.3 on 2025-10-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_organization_client_payment_terms'),
        ('invoicing', '0014_add_payment_model'),
        ('purchase_orders', '0004_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchase_orders.purchaseorder', verbose_name='Bon de commande associé'),
        ),
    ]
