# Generated by Django 4.2.11 on 2026-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exclude_from_cash_stats',
            field=models.BooleanField(default=False, help_text="Paiement exceptionnel (ex: régularisation rétroactive) à ne pas comptabiliser dans les totaux encaissés d'une journée précise, tout en restant visible sur la facture.", verbose_name='Exclu des stats de caisse journalières'),
        ),
    ]
