# Generated by Django 4.2.11 on 2026-08-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_payment_exclude_from_cash_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='global_discount_is_surcharge',
            field=models.BooleanField(default=False, help_text='Si coché, global_discount_value AJOUTE au total au lieu de le retirer', verbose_name='Remise globale = majoration'),
        ),
    ]
