# Generated by Django 5.0.3 on 2025-10-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_product_type_validation'),
        ('invoicing', '0015_fix_purchase_order_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
