# Generated by Django 5.0.3 on 2025-11-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_currency_and_language_preferences'),
        ('invoicing', '0016_add_product_type_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='printconfiguration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_configurations', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
