# Generated by Django 4.2.11 on 2026-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Vente de produits'), ('healthcare_consultation', 'Consultation médicale'), ('healthcare_laboratory', 'Laboratoire'), ('healthcare_imaging', 'Imagerie médicale'), ('healthcare_maternity', 'Maternité'), ('healthcare_vaccination', 'Vaccination'), ('healthcare_pharmacy', 'Pharmacie / Médicaments'), ('healthcare_services', 'Soins / Petite chirurgie / Hospitalisation'), ('credit_note', 'Avoir - Note de crédit')], default='standard', max_length=30, verbose_name='Type de facture'),
        ),
    ]
