# Generated by Django 4.2.11 on 2026-09-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0018_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(blank=True, default='', help_text='Ex: 2-8 °C, température ambiante, -20 °C', max_length=100, verbose_name='Conditions de conservation'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_batches', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='closure_notes',
            field=models.TextField(blank=True, default='', verbose_name='Note de clôture'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('depleted', 'Flacon terminé'), ('expired', 'Périmé'), ('contaminated', 'Contaminé / altéré'), ('qc_failed', 'Contrôle qualité non conforme'), ('other', 'Autre')], default='', max_length=20, verbose_name='Motif de clôture'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_batches', to=settings.AUTH_USER_MODEL, verbose_name='Ouvert par'),
        ),
    ]
