# Generated by Django 4.2.11 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_add_price_editable_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Entrepôt par défaut'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='header_address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
    ]
