# Generated by Django 4.2.11 on 2026-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_product_storage_conditions_productbatch_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tests_per_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de tests réalisables avec un flacon ou un kit. Vide : décompte en unités.', null=True, verbose_name='Tests par flacon / kit'),
        ),
        migrations.AddField(
            model_name='product',
            name='untracked_tests',
            field=models.PositiveIntegerField(default=0, verbose_name='Tests en attente de décompte'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='tests_remaining',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tests restants dans le flacon ouvert'),
        ),
    ]
