# Generated by Django 4.2.11 on 2026-01-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('invoicing', '0020_warehouse_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('healthcare_consultation', 'Consultation médicale'), ('healthcare_laboratory', 'Laboratoire'), ('healthcare_pharmacy', 'Pharmacie')], default='standard', max_length=30, verbose_name='Type de facture'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_by_org', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
