# Generated by Django 5.2.10 on 2026-03-20 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_warehouse_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='Quantité initiale')),
                ('current_quantity', models.IntegerField(default=0, verbose_name='Quantité actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='invoicing.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Lot de produit',
                'verbose_name_plural': 'Lots de produits',
                'ordering': ['expiration_date', 'created_at'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='invoicing.productbatch', verbose_name='Lot'),
        ),
    ]
