# Generated by Django 5.2.10 on 2026-03-20 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_productbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Lot du produit (si géré par lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoicing.productbatch', verbose_name='Lot'),
        ),
    ]
