# Generated by Django 4.2.11 on 2026-01-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_invoice_invoice_type_invoice_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro de chèque'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='success', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID de transaction'),
        ),
    ]
