# Generated by Django 5.2.10 on 2026-03-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contracttemplate'),
        ('invoicing', '0022_invoiceitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract', verbose_name='Contrat associé'),
        ),
    ]
