# Generated by Django 5.2.10 on 2026-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('cash', 'Comptant'), ('', 'Non spécifié')], help_text='Mode de paiement: Mobile Money ou Comptant', max_length=50, verbose_name='Mode de paiement'),
        ),
    ]
