# Generated by Django 5.2.10 on 2026-03-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_invoice_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='supplier_batch_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence lot fournisseur'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='invoicing.warehouse', verbose_name='Entrepôt'),
        ),
    ]
