# Generated by Django 5.2.10 on 2026-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_productbatch_supplier_batch_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='converted_from_quote',
            field=models.BooleanField(default=False, verbose_name='Converti depuis un devis'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière relance envoyée'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='next_reminder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine relance prévue'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation du devis"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise devis (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote_terms',
            field=models.TextField(blank=True, verbose_name='Conditions du devis'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de relances envoyées'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name="Devis valable jusqu'au"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('quote', 'Devis'), ('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
