# Generated by Django 5.2.10 on 2026-01-20 00:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_add_payment_method_choices_and_auto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('tablet', 'Comprimé'), ('capsule', 'Gélule'), ('blister', 'Plaquette'), ('box', 'Boîte'), ('bottle', 'Flacon'), ('vial', 'Ampoule'), ('sachet', 'Sachet'), ('tube', 'Tube'), ('ml', 'Millilitre'), ('l', 'Litre'), ('g', 'Gramme'), ('kg', 'Kilogramme')], default='piece', help_text='Unité stockée en base de données (la plus petite unité)', max_length=20, verbose_name='Unité de base'),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='1 unité de vente = X unités de base. Ex: 1 boîte = 10 plaquettes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Facteur de conversion'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('tablet', 'Comprimé'), ('capsule', 'Gélule'), ('blister', 'Plaquette'), ('box', 'Boîte'), ('bottle', 'Flacon'), ('vial', 'Ampoule'), ('sachet', 'Sachet'), ('tube', 'Tube'), ('ml', 'Millilitre'), ('l', 'Litre'), ('g', 'Gramme'), ('kg', 'Kilogramme')], default='piece', help_text='Unité affichée au client lors de la vente', max_length=20, verbose_name='Unité de vente'),
        ),
    ]
