# Generated by Django 5.2.10 on 2026-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0025_add_multi_unit_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('cash', 'Comptant'), ('check', 'Chèque'), ('bank_transfer', 'Virement bancaire'), ('', 'Non spécifié')], help_text='Mode de paiement: Mobile Money ou Comptant', max_length=50, verbose_name='Mode de paiement'),
        ),
    ]
