# Generated by Django 5.2.10 on 2026-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_add_organization_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du lot'),
        ),
    ]
