# Generated by Django 5.2.10 on 2026-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_alter_invoice_due_date_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, default='/', max_length=200, verbose_name='Titre'),
        ),
    ]
