# Generated by Django 5.2.10 on 2026-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0027_add_description_to_productbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Titre'),
        ),
    ]
