# Generated by Django 4.2.11 on 2026-01-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0027_alter_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('', 'Non spécifié')], help_text='Mode de paiement: Mobile Money ou Comptant', max_length=50, verbose_name='Mode de paiement'),
        ),
    ]
