# Generated by Django 5.2.10 on 2026-01-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0028_product_metadata_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, help_text="Date d'expiration du produit", null=True, verbose_name='Date de péremption'),
        ),
    ]
