# Generated by Django 5.2.10 on 2026-05-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_invoice_due_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='completed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('quote', 'Devis'), ('draft', 'Brouillon'), ('sent', 'Envoyée'), ('pending', 'En attente'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
