# Generated by Django 5.2.10 on 2026-06-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0030_add_payment_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Pourcentage (%)'), ('amount', 'Montant fixe')], default='percent', max_length=10, verbose_name='Type de remise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur de la remise'),
        ),
    ]
