# Generated by Django 5.2.10 on 2026-07-04 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('invoicing', '0031_invoice_discount_type_invoice_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminders_disabled',
            field=models.BooleanField(default=False, verbose_name='Relances automatiques désactivées pour cette facture'),
        ),
        migrations.CreateModel(
            name='InvoiceReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(verbose_name='Niveau de relance (1, 2, 3...)')),
                ('sent_to', models.EmailField(blank=True, max_length=254, verbose_name='Envoyé à')),
                ('triggered_by', models.CharField(choices=[('auto', 'Automatique'), ('manual', 'Manuelle')], default='auto', max_length=10, verbose_name='Déclenchée par')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='invoicing.invoice', verbose_name='Facture')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reminder_logs', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Relance de facture',
                'verbose_name_plural': 'Relances de factures',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['invoice', '-sent_at'], name='invoicing_i_invoice_06714f_idx'), models.Index(fields=['organization', '-sent_at'], name='invoicing_i_organiz_95f115_idx')],
            },
        ),
    ]
