# Generated by Django 5.2.10 on 2026-07-05 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('invoicing', '0032_invoice_reminders_disabled_invoicereminderlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=50, verbose_name="Numéro d'avoir")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant crédité')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('status', models.CharField(choices=[('issued', 'Émis'), ('cancelled', 'Annulé')], default='issued', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice', verbose_name="Facture d'origine")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='invoicing_c_invoice_e46469_idx'), models.Index(fields=['organization', '-created_at'], name='invoicing_c_organiz_596425_idx')],
                'unique_together': {('organization', 'credit_note_number')},
            },
        ),
    ]
