# Generated by Django 5.2.10 on 2026-07-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('invoicing', '0033_creditnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='Numéro de facture'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'invoice_number')},
        ),
    ]
