# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Document patient',
                'verbose_name_plural': 'Documents patients',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de visite')),
                ('visit_type', models.CharField(choices=[('consultation', 'Consultation Médicale'), ('lab_results', 'Retrait Résultats Labo'), ('follow_up_exam', 'Suivi après Examens'), ('prescription_renewal', 'Renouvellement Ordonnance'), ('laboratory', 'Examens Laboratoire'), ('pharmacy', 'Dispensation Pharmacie'), ('emergency', 'Urgence'), ('follow_up', 'Consultation de Suivi'), ('vaccination', 'Vaccination'), ('imaging', 'Imagerie Médicale'), ('administrative', 'Démarche Administrative'), ('wound_care', 'Soins Infirmiers'), ('physiotherapy', 'Kinésithérapie'), ('other', 'Autre')], default='consultation', max_length=20, verbose_name='Type de visite')),
                ('status', models.CharField(choices=[('registered', 'Enregistré'), ('waiting_consultation', 'En attente consultation'), ('in_consultation', 'En consultation'), ('waiting_lab', 'En attente labo'), ('in_lab', 'Au laboratoire'), ('waiting_results', 'En attente résultats'), ('waiting_pharmacy', 'En attente pharmacie'), ('at_pharmacy', 'À la pharmacie'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Non présenté')], default='registered', max_length=30, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Urgence')], default='routine', max_length=20, verbose_name='Priorité')),
                ('chief_complaint', models.TextField(blank=True, help_text='Raison principale de la visite', verbose_name='Motif de consultation')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles pour cette visite', verbose_name='Notes')),
                ('vitals_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('vitals_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('vitals_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('vitals_systolic', models.IntegerField(blank=True, null=True, verbose_name='Systolique (mmHg)')),
                ('vitals_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Diastolique (mmHg)')),
                ('vitals_blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie (g/L)')),
                ('vitals_spo2', models.IntegerField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Heure d'arrivée")),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début consultation')),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin consultation')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visite patient',
                'verbose_name_plural': 'Visites patients',
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCareService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('nursing_care', 'Soin infirmier'), ('laboratory', 'Analyse laboratoire'), ('pharmacy', 'Dispensation médicament'), ('imaging', 'Imagerie'), ('procedure', 'Procédure/Intervention'), ('other', 'Autre')], max_length=20, verbose_name='Type de service')),
                ('service_name', models.CharField(help_text='Dupliqué depuis Product ou saisi manuellement', max_length=200, verbose_name='Nom du service')),
                ('service_category', models.CharField(blank=True, help_text='Ex: Soins Infirmiers, Consultations, etc.', max_length=100, verbose_name='Catégorie')),
                ('provided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/heure du soin')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Facturé')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('notes', models.TextField(blank=True, help_text='Détails cliniques, observations', verbose_name='Notes/Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='consultations.consultation', verbose_name='Consultation associée')),
            ],
            options={
                'verbose_name': 'Service de soin patient',
                'verbose_name_plural': 'Services de soins patients',
                'ordering': ['-provided_at'],
            },
        ),
    ]
