# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('invoicing', '0020_warehouse_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de visite')),
                ('visit_type', models.CharField(choices=[('consultation', 'Consultation'), ('laboratory', 'Laboratoire'), ('pharmacy', 'Pharmacie'), ('emergency', 'Urgence'), ('follow_up', 'Suivi'), ('vaccination', 'Vaccination'), ('imaging', 'Imagerie'), ('other', 'Autre')], default='consultation', max_length=20, verbose_name='Type de visite')),
                ('status', models.CharField(choices=[('registered', 'Enregistré'), ('waiting_consultation', 'En attente consultation'), ('in_consultation', 'En consultation'), ('waiting_lab', 'En attente labo'), ('in_lab', 'Au laboratoire'), ('waiting_results', 'En attente résultats'), ('waiting_pharmacy', 'En attente pharmacie'), ('at_pharmacy', 'À la pharmacie'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Non présenté')], default='registered', max_length=30, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Urgence')], default='routine', max_length=20, verbose_name='Priorité')),
                ('chief_complaint', models.TextField(blank=True, help_text='Raison principale de la visite', verbose_name='Motif de consultation')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles pour cette visite', verbose_name='Notes')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Heure d'arrivée")),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début consultation')),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin consultation')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL, verbose_name='Médecin assigné')),
                ('consultation_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_visits', to='invoicing.invoice', verbose_name='Facture consultation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.client', verbose_name='Patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Visite patient',
                'verbose_name_plural': 'Visites patients',
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['organization', '-arrived_at'], name='patients_pa_organiz_ff203a_idx'), models.Index(fields=['patient', '-arrived_at'], name='patients_pa_patient_7e4ba8_idx'), models.Index(fields=['status'], name='patients_pa_status_4f8464_idx'), models.Index(fields=['visit_type'], name='patients_pa_visit_t_99b6d6_idx')],
            },
        ),
    ]
