# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoicing', '0002_initial'),
        ('laboratory', '0002_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcareservice',
            name='dispensing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='pharmacy.pharmacydispensing', verbose_name='Dispensation associée'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='invoicing.invoice', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='invoicing.invoiceitem', verbose_name='Ligne de facture'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='laboratory.laborder', verbose_name='Commande labo associée'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_services', to='accounts.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='provided_by',
            field=models.ForeignKey(blank=True, help_text='Médecin, infirmier, technicien, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_care_services', to=settings.AUTH_USER_MODEL, verbose_name='Fourni par'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='service_product',
            field=models.ForeignKey(blank=True, help_text='Pour les services facturables via catalogue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_care_records', to='invoicing.product', verbose_name='Service (Product)'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL, verbose_name='Médecin assigné'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='consultation_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_visits', to='invoicing.invoice', verbose_name='Facture consultation'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='accounts.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.client', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='patientcareservice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='patients.patientvisit', verbose_name='Visite associée'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['organization', '-arrived_at'], name='patients_pa_organiz_ff203a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['patient', '-arrived_at'], name='patients_pa_patient_7e4ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['status'], name='patients_pa_status_4f8464_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['visit_type'], name='patients_pa_visit_t_99b6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcareservice',
            index=models.Index(fields=['patient', '-provided_at'], name='patients_pa_patient_ea5923_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcareservice',
            index=models.Index(fields=['service_type'], name='patients_pa_service_d50516_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcareservice',
            index=models.Index(fields=['is_billed'], name='patients_pa_is_bill_c06a4e_idx'),
        ),
    ]
