# Generated by Django 4.2.11 on 2026-01-13 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(limit_choices_to={'client_type__in': ['patient', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.client', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Document patient',
                'verbose_name_plural': 'Documents patients',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
