# Generated by Django 5.2.10 on 2026-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcareservice',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('nursing_care', 'Soin infirmier'), ('laboratory', 'Analyse laboratoire'), ('pharmacy', 'Dispensation médicament'), ('imaging', 'Imagerie'), ('procedure', 'Procédure/Intervention'), ('vaccination', 'Vaccination'), ('physiotherapy', 'Kinésithérapie'), ('other', 'Autre')], max_length=20, verbose_name='Type de service'),
        ),
    ]
