# Generated by Django 4.2.11 on 2026-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_diastolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diastolique (mmHg)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fréquence Cardiaque (bpm)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_spo2',
            field=models.IntegerField(blank=True, null=True, verbose_name='SpO2 (%)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_systolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Systolique (mmHg)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
    ]
