# Generated by Django 5.2.10 on 2026-01-15 05:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('consultations', '0003_add_consultation_invoice'),
        ('invoicing', '0021_invoice_invoice_type_invoice_organization'),
        ('laboratory', '0003_labtest_linked_product'),
        ('patients', '0003_patientvisit_vitals_diastolic_and_more'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCareService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('nursing_care', 'Soin infirmier'), ('laboratory', 'Analyse laboratoire'), ('pharmacy', 'Dispensation médicament'), ('imaging', 'Imagerie'), ('procedure', 'Procédure/Intervention'), ('other', 'Autre')], max_length=20, verbose_name='Type de service')),
                ('service_name', models.CharField(help_text='Dupliqué depuis Product ou saisi manuellement', max_length=200, verbose_name='Nom du service')),
                ('service_category', models.CharField(blank=True, help_text='Ex: Soins Infirmiers, Consultations, etc.', max_length=100, verbose_name='Catégorie')),
                ('provided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/heure du soin')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Facturé')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('notes', models.TextField(blank=True, help_text='Détails cliniques, observations', verbose_name='Notes/Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='consultations.consultation', verbose_name='Consultation associée')),
                ('dispensing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='pharmacy.pharmacydispensing', verbose_name='Dispensation associée')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='invoicing.invoice', verbose_name='Facture')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='invoicing.invoiceitem', verbose_name='Ligne de facture')),
                ('lab_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='laboratory.laborder', verbose_name='Commande labo associée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_services', to='accounts.client', verbose_name='Patient')),
                ('provided_by', models.ForeignKey(blank=True, help_text='Médecin, infirmier, technicien, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_care_services', to=settings.AUTH_USER_MODEL, verbose_name='Fourni par')),
                ('service_product', models.ForeignKey(blank=True, help_text='Pour les services facturables via catalogue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_care_records', to='invoicing.product', verbose_name='Service (Product)')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_services', to='patients.patientvisit', verbose_name='Visite associée')),
            ],
            options={
                'verbose_name': 'Service de soin patient',
                'verbose_name_plural': 'Services de soins patients',
                'ordering': ['-provided_at'],
                'indexes': [models.Index(fields=['patient', '-provided_at'], name='patients_pa_patient_ea5923_idx'), models.Index(fields=['service_type'], name='patients_pa_service_d50516_idx'), models.Index(fields=['is_billed'], name='patients_pa_is_bill_c06a4e_idx')],
            },
        ),
    ]
