# Generated by Django 5.2.10 on 2026-01-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_add_patient_care_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_type',
            field=models.CharField(choices=[('consultation', 'Consultation Médicale'), ('lab_results', 'Retrait Résultats Labo'), ('follow_up_exam', 'Suivi après Examens'), ('prescription_renewal', 'Renouvellement Ordonnance'), ('laboratory', 'Examens Laboratoire'), ('pharmacy', 'Dispensation Pharmacie'), ('emergency', 'Urgence'), ('follow_up', 'Consultation de Suivi'), ('vaccination', 'Vaccination'), ('imaging', 'Imagerie Médicale'), ('administrative', 'Démarche Administrative'), ('wound_care', 'Soins Infirmiers'), ('physiotherapy', 'Kinésithérapie'), ('other', 'Autre')], default='consultation', max_length=20, verbose_name='Type de visite'),
        ),
    ]
