# Generated by Django 5.2.10 on 2026-03-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientfollowup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientfollowup',
            new_name='patients_pa_patient_179b52_idx',
            old_name='patients_followup_pat_date_idx',
        ),
        migrations.RenameIndex(
            model_name='patientfollowup',
            new_name='patients_pa_organiz_7bddbc_idx',
            old_name='patients_followup_org_date_idx',
        ),
    ]
