# Generated by Django 5.2.10 on 2026-02-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_update_visit_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='vitals_heart_rate',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='vitals_blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie (g/L)'),
        ),
    ]
