# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidderAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('otp_expires_at', models.DateTimeField(verbose_name='Expiration OTP')),
                ('session_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de session')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name="Bloqué jusqu'à")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Authentification soumissionnaire',
                'verbose_name_plural': 'Authentifications soumissionnaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_reference', models.CharField(max_length=100, verbose_name='Référence produit')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('specifications', models.TextField(blank=True, verbose_name='Spécifications')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix total')),
                ('unit_of_measure', models.CharField(default='unité', max_length=20, verbose_name='Unité de mesure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Article de soumission',
                'verbose_name_plural': 'Articles de soumission',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'événement")),
                ('event_type', models.CharField(choices=[('rfq', 'Demande de Prix (RFQ)')], default='rfq', max_length=20, verbose_name="Type d'événement")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('in_progress', 'En cours'), ('evaluation', 'Évaluation'), ('awarded', 'Attribué'), ('cancelled', 'Annulé'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut')),
                ('public_token', models.CharField(blank=True, default='', editable=False, max_length=64, unique=True, verbose_name='Token public')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Exigences')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Termes et conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('submission_deadline', models.DateTimeField(verbose_name='Date limite de soumission')),
                ('evaluation_deadline', models.DateField(blank=True, null=True, verbose_name="Date limite d'évaluation")),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget estimé')),
                ('evaluation_criteria', models.JSONField(blank=True, default=dict, verbose_name="Critères d'évaluation")),
            ],
            options={
                'verbose_name': 'Événement de sourcing',
                'verbose_name_plural': 'Événements de sourcing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En révision'), ('shortlisted', 'Présélectionné'), ('awarded', 'Retenu'), ('rejected', 'Rejeté'), ('withdrawn', 'Retiré')], default='draft', max_length=20, verbose_name='Statut')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de présentation')),
                ('technical_response', models.TextField(blank=True, verbose_name='Réponse technique')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Termes acceptés')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant des taxes')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai de livraison (jours)')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Score d'évaluation")),
                ('evaluation_notes', models.TextField(blank=True, verbose_name="Notes d'évaluation")),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'évaluation")),
            ],
            options={
                'verbose_name': 'Soumission fournisseur',
                'verbose_name_plural': 'Soumissions fournisseurs',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, default='', editable=False, max_length=64, unique=True, verbose_name="Token d'accès")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('viewed', 'Vu'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de consultation')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('invitation_message', models.TextField(blank=True, verbose_name="Message d'invitation")),
                ('decline_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
            ],
            options={
                'verbose_name': 'Invitation fournisseur',
                'verbose_name_plural': 'Invitations fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
