# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_sourcing', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_items', to='invoicing.product', verbose_name='Produit catalogue'),
        ),
        migrations.AddField(
            model_name='sourcingevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sourcing_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='bidderauth',
            name='sourcing_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_auths', to='e_sourcing.sourcingevent', verbose_name='Événement de sourcing'),
        ),
        migrations.AddField(
            model_name='supplierbid',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_bids', to=settings.AUTH_USER_MODEL, verbose_name='Évalué par'),
        ),
        migrations.AddField(
            model_name='supplierbid',
            name='sourcing_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='e_sourcing.sourcingevent', verbose_name='Événement de sourcing'),
        ),
        migrations.AddField(
            model_name='supplierbid',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='biditem',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='e_sourcing.supplierbid', verbose_name='Soumission'),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='sourcing_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='e_sourcing.sourcingevent', verbose_name='Événement de sourcing'),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_invitations', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='supplierbid',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid', to='e_sourcing.supplierinvitation', verbose_name='Invitation'),
        ),
        migrations.AddIndex(
            model_name='bidderauth',
            index=models.Index(fields=['email', 'sourcing_event'], name='e_sourcing__email_62dcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='bidderauth',
            index=models.Index(fields=['session_token'], name='e_sourcing__session_766675_idx'),
        ),
        migrations.AddIndex(
            model_name='bidderauth',
            index=models.Index(fields=['otp_expires_at'], name='e_sourcing__otp_exp_008b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvitation',
            unique_together={('sourcing_event', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierbid',
            unique_together={('sourcing_event', 'supplier')},
        ),
    ]
