# Generated by Django 5.0.3 on 2025-10-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvitation',
            name='access_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, unique=True, verbose_name="Token d'accès"),
        ),
    ]
