# Generated by Django 5.0.3 on 2025-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sourcing', '0002_supplierinvitation_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingevent',
            name='public_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, unique=True, verbose_name='Token public'),
        ),
    ]
