# Generated by Django 5.0.3 on 2025-10-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sourcing', '0003_sourcingevent_public_token'),
        ('invoicing', '0010_add_product_category_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_items', to='invoicing.product', verbose_name='Produit catalogue'),
        ),
    ]
