# Generated by Django 5.0.3 on 2025-10-23 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_sourcing', '0004_biditem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidderAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('otp_expires_at', models.DateTimeField(verbose_name='Expiration OTP')),
                ('session_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de session')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name="Bloqué jusqu'à")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('sourcing_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_auths', to='e_sourcing.sourcingevent', verbose_name='Événement de sourcing')),
            ],
            options={
                'verbose_name': 'Authentification soumissionnaire',
                'verbose_name_plural': 'Authentifications soumissionnaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'sourcing_event'], name='e_sourcing__email_62dcb1_idx'), models.Index(fields=['session_token'], name='e_sourcing__session_766675_idx'), models.Index(fields=['otp_expires_at'], name='e_sourcing__otp_exp_008b1d_idx')],
            },
        ),
    ]
