# Generated by Django 4.2.11 on 2026-01-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('accounts', '0015_client_allergies_client_blood_type_and_more'),
        ('invoicing', '0020_warehouse_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDispensing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispensing_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de dispensation')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de dispensation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('dispensed', 'Dispensé'), ('partial', 'Partiellement dispensé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('counseling_provided', models.BooleanField(default=False, help_text="Le patient a reçu des conseils sur l'utilisation des médicaments", verbose_name='Conseil fourni')),
                ('counseling_notes', models.TextField(blank=True, help_text='Instructions données au patient', verbose_name='Notes de conseil')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL, verbose_name='Dispensé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_dispensings', to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'client_type__in': ['patient', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_dispensings', to='accounts.client', verbose_name='Patient')),
                ('pharmacy_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_dispensings', to='invoicing.invoice', verbose_name='Facture pharmacie')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_dispensings', to='patients.patientvisit', verbose_name='Visite associée')),
            ],
            options={
                'verbose_name': 'Dispensation',
                'verbose_name_plural': 'Dispensations',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='DispensingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_dispensed', models.IntegerField(verbose_name='Quantité dispensée')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text="Prix d'achat au moment de la dispensation", max_digits=10, verbose_name='Coût unitaire')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix de vente', max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Prix total')),
                ('dosage_instructions', models.TextField(blank=True, help_text='Instructions de dosage pour le patient', verbose_name='Posologie')),
                ('frequency', models.CharField(blank=True, help_text='Ex: 3 fois par jour, matin et soir', max_length=100, verbose_name='Fréquence')),
                ('duration', models.CharField(blank=True, help_text='Ex: 7 jours, 2 semaines', max_length=100, verbose_name='Durée')),
                ('route', models.CharField(blank=True, help_text='Ex: Oral, IV, IM, Topique', max_length=50, verbose_name="Voie d'administration")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacydispensing', verbose_name='Dispensation')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='invoicing.product', verbose_name='Médicament')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_items', to='invoicing.stockmovement', verbose_name='Mouvement de stock')),
            ],
            options={
                'verbose_name': 'Item de dispensation',
                'verbose_name_plural': 'Items de dispensation',
                'ordering': ['medication__name'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacydispensing',
            index=models.Index(fields=['organization', '-dispensed_at'], name='pharmacy_ph_organiz_da07c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacydispensing',
            index=models.Index(fields=['patient'], name='pharmacy_ph_patient_1731fa_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacydispensing',
            index=models.Index(fields=['status'], name='pharmacy_ph_status_246966_idx'),
        ),
    ]
