# Generated by Django 5.2.10 on 2026-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingitem',
            name='dispensing_unit',
            field=models.CharField(choices=[('base', 'Unité de base'), ('sell', 'Unité de vente')], default='base', max_length=20, verbose_name='Unité de dispensation'),
        ),
        migrations.AlterField(
            model_name='dispensingitem',
            name='quantity_dispensed',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantité dispensée'),
        ),
    ]
