# Generated by Django 5.2.10 on 2026-02-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoiceitem_batch'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_items', to='invoicing.productbatch', verbose_name='Lot / Batch'),
        ),
    ]
