# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du budget')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant du budget')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel'), ('custom', 'Personnalisé')], default='monthly', max_length=20, verbose_name='Type de période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approbation'), ('reject', 'Rejet'), ('send', 'Envoi'), ('pay', 'Paiement'), ('cancel', 'Annulation'), ('restore', 'Restauration')], max_length=20, verbose_name="Type d'action")),
                ('entity_type', models.CharField(choices=[('invoice', 'Facture'), ('client', 'Client'), ('product', 'Produit'), ('purchase_order', 'Bon de commande'), ('supplier', 'Fournisseur'), ('stock_movement', 'Mouvement de stock'), ('payment', 'Paiement'), ('contract', 'Contrat'), ('user', 'Utilisateur'), ('organization', 'Organisation'), ('report', 'Rapport'), ('dashboard', 'Dashboard')], max_length=50, verbose_name="Type d'entité")),
                ('entity_id', models.CharField(max_length=100, verbose_name="ID de l'entité")),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Informations supplémentaires sur l'action", verbose_name='Métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_a_created_b5efc6_idx'), models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_abe786_idx'), models.Index(fields=['organization', '-created_at'], name='analytics_a_organiz_7c6b6a_idx'), models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__07b0c9_idx'), models.Index(fields=['action_type', '-created_at'], name='analytics_a_action__916ee8_idx')],
            },
        ),
    ]
