# Generated by Django 5.2.10 on 2026-02-08 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bi-hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20, verbose_name='Frequence')),
                ('include_healthcare', models.BooleanField(default=True, verbose_name='Inclure sante/labo')),
                ('include_inventory', models.BooleanField(default=True, verbose_name='Inclure inventaire')),
                ('include_finance', models.BooleanField(default=True, verbose_name='Inclure finances')),
                ('include_stock_alerts', models.BooleanField(default=True, verbose_name='Inclure alertes stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_configs', to='accounts.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_configs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Configuration rapport periodique',
                'verbose_name_plural': 'Configurations rapports periodiques',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
