# Generated by Django 5.0.3 on 2025-10-25 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_period', models.CharField(choices=[('today', "Aujourd'hui"), ('yesterday', 'Hier'), ('last_7_days', '7 derniers jours'), ('last_30_days', '30 derniers jours'), ('last_90_days', '90 derniers jours'), ('this_month', 'Ce mois'), ('last_month', 'Mois dernier'), ('this_year', 'Cette année'), ('custom', 'Personnalisé')], default='last_30_days', max_length=20, verbose_name='Période par défaut')),
                ('enabled_widgets', models.JSONField(blank=True, default=list, help_text='Liste ordonnée des widgets à afficher', verbose_name='Widgets activés')),
                ('favorite_metrics', models.JSONField(blank=True, default=list, help_text='Liste des métriques à mettre en avant', verbose_name='Indicateurs favoris')),
                ('compare_previous_period', models.BooleanField(default=True, verbose_name='Comparer avec période précédente')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name="Format d'export préféré")),
                ('email_report_enabled', models.BooleanField(default=False, verbose_name='Recevoir rapport par email')),
                ('email_report_frequency', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20, verbose_name='Fréquence email rapport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Configuration Dashboard',
                'verbose_name_plural': 'Configurations Dashboard',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDashboardView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la vue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('configuration', models.JSONField(default=dict, help_text='Paramètres de filtrage et affichage', verbose_name='Configuration')),
                ('is_default', models.BooleanField(default=False, verbose_name='Vue par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_dashboard_views', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vue Dashboard Sauvegardée',
                'verbose_name_plural': 'Vues Dashboard Sauvegardées',
                'ordering': ['-is_default', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
