# Generated by Django 5.0.3 on 2025-10-28 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_dashboard_config_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identifiant unique du widget (ex: products_overview)', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('products', 'Produits'), ('clients', 'Clients'), ('invoices', 'Factures'), ('purchase_orders', 'Bons de Commande'), ('ai', 'Assistant IA'), ('global', 'Global')], max_length=50, verbose_name='Module')),
                ('type', models.CharField(choices=[('stats', 'Statistiques'), ('chart', 'Graphique'), ('list', 'Liste'), ('table', 'Tableau'), ('timeline', 'Timeline'), ('gauge', 'Jauge'), ('alert', 'Alerte')], max_length=50, verbose_name='Type')),
                ('default_size', models.CharField(choices=[('small', 'Petit (1x1)'), ('medium', 'Moyen (2x1)'), ('large', 'Grand (2x2)'), ('xlarge', 'Très grand (3x2)')], default='medium', max_length=20, verbose_name='Taille par défaut')),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Configuration par défaut du widget (période, limite, etc.)', verbose_name='Configuration par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage dans la bibliothèque", verbose_name='Ordre')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: TrendingUp, Users, Package)", max_length=100, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['module', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du layout')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Layout par défaut')),
                ('global_config', models.JSONField(blank=True, default=dict, help_text='Période par défaut, filtres globaux, etc.', verbose_name='Configuration globale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Layout Dashboard',
                'verbose_name_plural': 'Layouts Dashboard',
                'ordering': ['-is_default', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.JSONField(default=dict, help_text='Position dans la grille: {x, y, w, h}', verbose_name='Position')),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Surcharge la configuration par défaut du widget', verbose_name='Configuration personnalisée')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_instances', to='analytics.dashboardlayout', verbose_name='Layout')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='analytics.widget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Instance de Widget',
                'verbose_name_plural': 'Instances de Widgets',
                'ordering': ['layout', 'order'],
            },
        ),
    ]
