# Generated by Django 5.2.10 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_batch_wilson_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreportconfig',
            name='recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Emails supplémentaires séparés par virgule (en plus du user)', verbose_name='Emails destinataires'),
        ),
    ]
