# Generated by Django 5.0.3 on 2025-10-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_widget_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetinstance',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='widgetinstance',
            name='layout',
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='layout',
            field=models.JSONField(default=list, help_text='Position et taille des widgets dans la grille', verbose_name='Configuration layout'),
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.DeleteModel(
            name='WidgetInstance',
        ),
    ]
