# Generated by Django 4.2.11 on 2026-06-16 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0005_budget_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_id', models.CharField(db_index=True, max_length=64, verbose_name='ID visiteur anonyme')),
                ('path', models.CharField(max_length=500, verbose_name='Chemin')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Référent')),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Domaine référent')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Ordinateur'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('bot', 'Robot'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=10, verbose_name="Type d'appareil")),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Pays (ISO)')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_visits', to=settings.AUTH_USER_MODEL, verbose_name='Compte créé')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_v_created_70e4a0_idx'), models.Index(fields=['anon_id', '-created_at'], name='analytics_v_anon_id_076dce_idx'), models.Index(fields=['referrer_domain', '-created_at'], name='analytics_v_referre_c40769_idx'), models.Index(fields=['utm_source', '-created_at'], name='analytics_v_utm_sou_9c5aba_idx')],
            },
        ),
    ]
