# Generated by Django 5.2.10 on 2026-01-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_budget_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardlayout',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dashboardlayout',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='saveddashboardview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saveddashboardview',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardConfig',
        ),
        migrations.DeleteModel(
            name='DashboardLayout',
        ),
        migrations.DeleteModel(
            name='SavedDashboardView',
        ),
    ]
