# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du template')),
                ('report_type', models.CharField(choices=[('supplier', 'Rapport Fournisseur'), ('supplier_all', 'Rapport Tous Fournisseurs'), ('product', 'Rapport Produit'), ('product_all', 'Rapport Tous Produits'), ('invoice', 'Rapport Factures'), ('purchase_order', 'Rapport Bons de Commande'), ('client', 'Rapport Client'), ('client_all', 'Rapport Tous Clients')], max_length=50, verbose_name='Type de rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Configuration JSON du template (colonnes, filtres, etc.)', verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Template de rapport',
                'verbose_name_plural': 'Templates de rapports',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('supplier', 'Rapport Fournisseur'), ('supplier_all', 'Rapport Tous Fournisseurs'), ('product', 'Rapport Produit'), ('product_all', 'Rapport Tous Produits'), ('invoice', 'Rapport Factures'), ('purchase_order', 'Rapport Bons de Commande'), ('client', 'Rapport Client'), ('client_all', 'Rapport Tous Clients')], max_length=50, verbose_name='Type de rapport')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Format')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Paramètres de génération (date_debut, date_fin, filtres, etc.)', verbose_name='Paramètres')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier téléchargement')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['generated_by', '-generated_at'], name='reports_rep_generat_c7e29e_idx')],
            },
        ),
    ]
