# Generated by Django 5.2.10 on 2026-02-08 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProactiveSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('learning', "Conseil d'apprentissage"), ('feature', 'Découverte de fonctionnalité'), ('best_practice', 'Meilleure pratique'), ('optimization', 'Optimisation')], max_length=50)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name="Label du bouton d'action")),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('trigger_conditions', models.JSONField(default=dict, verbose_name='Conditions de déclenchement')),
                ('priority', models.IntegerField(default=5, verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_displays', models.IntegerField(default=3, verbose_name="Maximum d'affichages")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suggestion proactive',
                'verbose_name_plural': 'Suggestions proactives',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_proactive', models.BooleanField(default=False, verbose_name='Conversation proactive')),
                ('proactive_source_id', models.UUIDField(blank=True, null=True, verbose_name='ID source proactive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('supplier_list', 'Liste fournisseurs'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin fichier')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Texte OCR')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Données extraites')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='Analyse IA')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='Création automatique')),
                ('created_entity_type', models.CharField(blank=True, max_length=50, verbose_name='Type entité créée')),
                ('created_entity_id', models.CharField(blank=True, max_length=100, verbose_name='ID entité créée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document scanné',
                'verbose_name_plural': 'Documents scannés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_calls', models.JSONField(blank=True, null=True, verbose_name='Function Calls')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20)),
                ('entity_type', models.CharField(choices=[('supplier', 'Fournisseur'), ('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('client', 'Client'), ('product', 'Produit'), ('stock', 'Stock'), ('report', 'Rapport')], max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('can_undo', models.BooleanField(default=True)),
                ('is_undone', models.BooleanField(default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_8db631_idx'), models.Index(fields=['entity_type', 'entity_id'], name='ai_assistan_entity__7c136d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Tokens du prompt')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Tokens de complétion')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total tokens')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Coût estimé')),
                ('action_type', models.CharField(default='chat', max_length=50, verbose_name="Type d'action")),
                ('model_used', models.CharField(default='mistral-large-latest', max_length=50, verbose_name='Modèle utilisé')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.conversation')),
            ],
            options={
                'verbose_name': "Log d'utilisation AI",
                'verbose_name_plural': "Logs d'utilisation AI",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_eaaaea_idx'), models.Index(fields=['organization', '-created_at'], name='ai_assistan_organiz_d9e5bc_idx'), models.Index(fields=['action_type', '-created_at'], name='ai_assistan_action__4fc36f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('supplier', 'Fournisseur'), ('product', 'Produit')], max_length=50, verbose_name="Type d'entité")),
                ('extracted_data', models.JSONField(verbose_name='Données extraites')),
                ('modified_data', models.JSONField(blank=True, null=True, verbose_name='Données modifiées')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('modified', 'Modifié')], default='pending', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('created_entity_id', models.UUIDField(blank=True, null=True, verbose_name='ID entité créée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_reviews', to='accounts.organization', verbose_name='Organisation')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_reviews', to='ai_assistant.documentscan', verbose_name='Document source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Révision d'import",
                'verbose_name_plural': "Révisions d'import",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='ai_assistan_user_id_14495d_idx'), models.Index(fields=['organization', 'status', '-created_at'], name='ai_assistan_organiz_e24e7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProactiveConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('starter_message', models.TextField(verbose_name='Message de démarrage')),
                ('context_data', models.JSONField(default=dict, verbose_name='Données contextuelles')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('dismissed', 'Ignorée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ignorance")),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proactive_source', to='ai_assistant.conversation', verbose_name='Conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_conversations', to='accounts.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation proactive',
                'verbose_name_plural': 'Conversations proactives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='ai_assistan_user_id_3f9206_idx'), models.Index(fields=['organization', 'status', '-created_at'], name='ai_assistan_organiz_0f066c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('suggestion', 'Suggestion proactive'), ('alert', 'Alerte'), ('insight', 'Analyse intelligente'), ('achievement', 'Succès débloqué')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='Label du bouton')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('data', models.JSONField(default=dict, verbose_name='Données additionnelles')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées')),
                ('priority', models.IntegerField(default=5, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_notifications', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notifications', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.proactivesuggestion')),
            ],
            options={
                'verbose_name': 'Notification IA',
                'verbose_name_plural': 'Notifications IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='ai_assistan_user_id_cc070e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSuggestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.proactivesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de suggestion',
                'verbose_name_plural': 'Historiques de suggestions',
                'ordering': ['-displayed_at'],
                'unique_together': {('user', 'suggestion')},
            },
        ),
    ]
