# Generated by Django 5.0.3 on 2025-09-23 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('supplier_list', 'Liste fournisseurs'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin fichier')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Texte OCR')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Données extraites')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='Analyse IA')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='Création automatique')),
                ('created_entity_type', models.CharField(blank=True, max_length=50, verbose_name='Type entité créée')),
                ('created_entity_id', models.CharField(blank=True, max_length=100, verbose_name='ID entité créée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document scanné',
                'verbose_name_plural': 'Documents scannés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
