# Generated by Django 5.0.3 on 2025-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_conversation_documentscan_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, null=True, verbose_name='Function Calls'),
        ),
    ]
