# Generated by Django 5.0.3 on 2025-10-25 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_message_tool_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20)),
                ('entity_type', models.CharField(choices=[('supplier', 'Fournisseur'), ('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('client', 'Client'), ('product', 'Produit')], max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('can_undo', models.BooleanField(default=True)),
                ('is_undone', models.BooleanField(default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_8db631_idx'), models.Index(fields=['entity_type', 'entity_id'], name='ai_assistan_entity__7c136d_idx')],
            },
        ),
    ]
