# Generated by Django 5.0.3 on 2025-12-15 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_currency_and_language_preferences'),
        ('ai_assistant', '0004_create_action_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='entity_type',
            field=models.CharField(choices=[('supplier', 'Fournisseur'), ('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('client', 'Client'), ('product', 'Produit'), ('stock', 'Stock'), ('report', 'Rapport')], max_length=50),
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Tokens du prompt')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Tokens de complétion')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total tokens')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Coût estimé')),
                ('action_type', models.CharField(default='chat', max_length=50, verbose_name="Type d'action")),
                ('model_used', models.CharField(default='mistral-large-latest', max_length=50, verbose_name='Modèle utilisé')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'utilisation AI",
                'verbose_name_plural': "Logs d'utilisation AI",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_eaaaea_idx'), models.Index(fields=['organization', '-created_at'], name='ai_assistan_organiz_d9e5bc_idx'), models.Index(fields=['action_type', '-created_at'], name='ai_assistan_action__4fc36f_idx')],
            },
        ),
    ]
