# Generated by Django 5.0.3 on 2025-12-15 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_ai_usage_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('learning', "Conseil d'apprentissage"), ('feature', 'Découverte de fonctionnalité'), ('best_practice', 'Meilleure pratique'), ('optimization', 'Optimisation')], max_length=50)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name="Label du bouton d'action")),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('trigger_conditions', models.JSONField(default=dict, verbose_name='Conditions de déclenchement')),
                ('priority', models.IntegerField(default=5, verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_displays', models.IntegerField(default=3, verbose_name="Maximum d'affichages")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suggestion proactive',
                'verbose_name_plural': 'Suggestions proactives',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSuggestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.proactivesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de suggestion',
                'verbose_name_plural': 'Historiques de suggestions',
                'ordering': ['-displayed_at'],
                'unique_together': {('user', 'suggestion')},
            },
        ),
    ]
