# Generated by Django 5.0.3 on 2025-12-15 06:16

from django.db import migrations


def create_initial_suggestions(apps, schema_editor):
    """Crée les suggestions proactives initiales"""
    ProactiveSuggestion = apps.get_model('ai_assistant', 'ProactiveSuggestion')

    suggestions = [
        {
            'suggestion_type': 'feature',
            'title': 'Créez des flyers professionnels avec Canvas',
            'message': 'Saviez-vous que vous pouvez créer des flyers de vente personnalisés avec notre outil Canvas? Attirez plus de clients avec des visuels percutants!',
            'action_label': 'Découvrir Canvas',
            'action_url': '/canvas',
            'trigger_conditions': {'min_products': 3},
            'priority': 8,
            'is_active': True,
            'max_displays': 3,
        },
        {
            'suggestion_type': 'feature',
            'title': 'Envoyez vos factures par email',
            'message': 'Gagnez du temps! Envoyez vos factures directement par email avec un PDF joint en un seul clic.',
            'action_label': 'Essayer maintenant',
            'action_url': '/invoices',
            'trigger_conditions': {'min_invoices': 5, 'never_used_feature': 'email_invoice'},
            'priority': 9,
            'is_active': True,
            'max_displays': 3,
        },
        {
            'suggestion_type': 'optimization',
            'title': 'Scannez vos documents au lieu de les saisir',
            'message': 'Arrêtez de perdre du temps avec la saisie manuelle! Utilisez notre scanner IA pour extraire automatiquement les données de vos documents.',
            'action_label': 'Scanner un document',
            'action_url': '/ai-chat',
            'trigger_conditions': {'min_invoices': 3},
            'priority': 10,
            'is_active': True,
            'max_displays': 3,
        },
        {
            'suggestion_type': 'learning',
            'title': 'L\'assistant IA peut créer des entités pour vous',
            'message': 'Demandez à l\'assistant IA de créer des factures, bons de commande, clients ou fournisseurs simplement en discutant avec lui!',
            'action_label': 'Essayer l\'assistant IA',
            'action_url': '/ai-chat',
            'trigger_conditions': {},
            'priority': 6,
            'is_active': True,
            'max_displays': 2,
        },
        {
            'suggestion_type': 'best_practice',
            'title': 'Organisez vos produits par catégories',
            'message': 'Utilisez les catégories pour mieux organiser votre catalogue produit et générer des rapports plus précis.',
            'action_label': 'Gérer les catégories',
            'action_url': '/products',
            'trigger_conditions': {'min_products': 10},
            'priority': 5,
            'is_active': True,
            'max_displays': 2,
        },
    ]

    for suggestion_data in suggestions:
        ProactiveSuggestion.objects.create(**suggestion_data)


def remove_initial_suggestions(apps, schema_editor):
    """Supprime les suggestions initiales en cas de rollback"""
    ProactiveSuggestion = apps.get_model('ai_assistant', 'ProactiveSuggestion')

    titles = [
        'Créez des flyers professionnels avec Canvas',
        'Envoyez vos factures par email',
        'Scannez vos documents au lieu de les saisir',
        'L\'assistant IA peut créer des entités pour vous',
        'Organisez vos produits par catégories',
    ]

    ProactiveSuggestion.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_proactive_suggestions'),
    ]

    operations = [
        migrations.RunPython(create_initial_suggestions, remove_initial_suggestions),
    ]
