# Generated by Django 5.0.3 on 2025-12-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_add_initial_suggestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('suggestion', 'Suggestion proactive'), ('alert', 'Alerte'), ('insight', 'Analyse intelligente'), ('achievement', 'Succès débloqué')], max_length=50)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='Label du bouton')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'action")),
                ('data', models.JSONField(default=dict, verbose_name='Données additionnelles')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.proactivesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification IA',
                'verbose_name_plural': 'Notifications IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='ai_assistan_user_id_cc070e_idx')],
            },
        ),
    ]
