# Generated by Django 4.2.11 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_proactive_conversations_and_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importreview',
            options={'ordering': ['-created_at'], 'verbose_name': "Révision d'import", 'verbose_name_plural': "Révisions d'import"},
        ),
        migrations.RemoveIndex(
            model_name='importreview',
            name='ai_assistan_user_sta_idx',
        ),
        migrations.RemoveIndex(
            model_name='importreview',
            name='ai_assistan_organ_sta_idx',
        ),
        migrations.RemoveIndex(
            model_name='proactiveconversation',
            name='ai_assistan_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='proactiveconversation',
            name='ai_assistan_organiz_idx',
        ),
        migrations.AlterField(
            model_name='ainotification',
            name='notification_type',
            field=models.CharField(choices=[('suggestion', 'Suggestion proactive'), ('alert', 'Alerte'), ('insight', 'Analyse intelligente'), ('achievement', 'Succès débloqué')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='importreview',
            name='entity_type',
            field=models.CharField(choices=[('invoice', 'Facture'), ('purchase_order', 'Bon de commande'), ('supplier', 'Fournisseur'), ('product', 'Produit')], max_length=50, verbose_name="Type d'entité"),
        ),
        migrations.AddIndex(
            model_name='importreview',
            index=models.Index(fields=['user', 'status', '-created_at'], name='ai_assistan_user_id_14495d_idx'),
        ),
        migrations.AddIndex(
            model_name='importreview',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ai_assistan_organiz_e24e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='proactiveconversation',
            index=models.Index(fields=['user', 'status', '-created_at'], name='ai_assistan_user_id_3f9206_idx'),
        ),
        migrations.AddIndex(
            model_name='proactiveconversation',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ai_assistan_organiz_0f066c_idx'),
        ),
    ]
