# Generated by Django 5.2.10 on 2026-03-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0012_push_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
