# Generated by Django 5.2.10 on 2026-03-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_change_payment_terms_default_to_cash'),
        ('ai_assistant', '0013_alter_notificationpreferences_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.organization', verbose_name='Organisation'),
        ),
    ]
