# Generated by Django 5.2.10 on 2026-03-24 02:17

from django.db import migrations


def backfill_organization(apps, schema_editor):
    """Backfill organization on existing conversations from user.organization"""
    Conversation = apps.get_model('ai_assistant', 'Conversation')
    for conv in Conversation.objects.filter(organization__isnull=True).select_related('user'):
        org = getattr(conv.user, 'organization', None)
        if org:
            conv.organization = org
            conv.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_add_organization_to_conversation'),
    ]

    operations = [
        migrations.RunPython(backfill_organization, migrations.RunPython.noop),
    ]
